### ISSUE TITLE
[java] The rule CloseResource should deal with IO stream as default

### ISSUE THREAD

**Issue by lonelyma1021** [pmd/pmd#1000]
As InputStream/OutputStream are also common resources in program, should you guys task them into consideration as the default value of the 'types' property? BTW, I add them into my ruleset configuration, but get no violation.
My config is here:
```
<rule ref="category/java/errorprone.xml/CloseResource" >
        <properties>
            <property name="types" value="[java.sql.Connection, java.sql.Statement, java.sql.ResultSet, java.io.InputStream]"/>
        </properties>
    </rule>
```
My code snippet:
```
InputStream is = new InputStream() {
	@Override
	public int read() throws IOException {
		// TODO Auto-generated method stub
		return 0;
	}
};
		
try {
	is.read();
} catch (IOException e) {
			
}
```

**Comment by adangel** [comment]
Currently the rule [CloseResource](https://pmd.github.io/pmd-6.1.0/pmd_rules_java_errorprone.html#closeresource) deals only with SQL types. Closing IO streams is very important, too.
However, we should probably be careful changing the defaults, since this would apply to all users automatically after an update of PMD (given, they don't already manually configure this rule).

We could decide one or more of these:
*   that it always makes sense to check for streams by default
*   to provide some preconfigured rulesets (aka starter rulesets, use case rulesets)
    (side note: this will probably bring up the problem, that we eventually want to have the same rule twice, but with different configuration. Currently I think, this is not possible without changing the rule name, since the rule name must be unique)
*   only improve the documentation and give examples
