### ISSUE TITLE
[java] Performance degradation of 250% between 6.1.0 and 6.2.0

### ISSUE THREAD

**Issue by davidburstromspotify** [pmd/pmd#1018]
**Affects PMD Version:** 
6.2.0

**Rule:**
Unknown

**Description:**
There is a performance degradation in analysis between 6.1.0 and 6.2.0. A task that previously took 3.5 minutes can now take up to 9 minutes. Running a Flight recorder indicates that part of the problem might be that ClassTypeResolver.processOnDemand logs too much. 

<img width="976" alt="screen shot 2018-04-03 at 12 51 17" src="https://user-images.githubusercontent.com/2573207/38247092-5005d394-3744-11e8-9a0d-44762c319c91.png">

**Code Sample demonstrating the issue:**
Corpus is not disclosable, sorry.

**Running PMD through:**
Gradle

**Comment by jsotuyod** [comment]
@davidburstromspotify thanks for the report. We care specially about user performance. 3.5 minutes is way more than we aim for, not to mention 9.

## As to helping you get great performance back

The logging has effectively been added in PMD 6.2.0, so it's completely plausible it's responsible for a regression. Non the less, you should consider that those logs are completely ignored unless PMD is being run in debug / verbose mode. You may want to consider not running Ant / Gradle / Maven in verbose mode (the flag is propagated) to avoid this.

You should also take into consideration, these logs indicate that your auxclasspath doesn't contain imported classes. If you are seeing LOTS of these logs, as indicated by your hotspot analysis, you are probably not correctly setting up the auxclasspath at all. You should set the `<auxclasspath>` nested element of the `<pmd>` task (I assume you are using Ant, since both Maven and Gradle have defaults for this), with a fileset containing:

1. All locations were code is compiled into (you need to make sure the code is compiled before PMD runs it's analysis)
2. All dependencies used to compile the code

Doing this will not only get rid of all these logs, but actually produce better analysis results, as PMD has far more information available to analyze.

## Other suggestions

You may want to consider using [Incremental Analysis](https://pmd.github.io/pmd-6.2.0/pmd_userdocs_getting_started.html) if you aren't yet. If running multiple PMD analysis, remember to give each one a different cache file.

## Making PMD even better

Is this a private project or a public one? If public, can you point it to me? I'd like to run some benchmarks and do some tests. As I said, 3.5 minutes still sounds like a lot, so I'd like to better understand what's going on.

In case it's private. How many Java files are part of the project? Can you get me an estimate size of the codebase? (in MB it is ok if not able to get Lines of Code easily)

Thanks in advanced

**Comment by davidburstromspotify** [comment]
Sorry for lack of response on my side.

As you correctly guessed, in these cases the classpath is not set up. This is deliberate, as PMD provides us with fast and useful feedback even without compilation. We'd prefer if we can continue doing so.
We're actually not invoking Gradle with debug or verbose logging when we get these performance numbers. `consoleOutput = true` was set, though.

Think in terms of 4k Java files and 30MB of source.

**Comment by davidburstromspotify** [comment]
It appears as if setting `consoleOutput = false` didn't make any difference.

**Comment by jsotuyod** [comment]
@davidburstromspotify thanks for the feedback. Can you please provide me with:

1. The version of gradle being used
2. the pmd task configuration set in gradle

With that I'll try to reproduce the issue.

**Comment by wkurniawan07** [comment]
Hello @jsotuyod, I can confirm the performance degradation although not as bad as 250%. Have a look at [this repo](https://github.com/wkurniawan07/repo/tree/1877c9c75318168e9d3a633bc0e7b472f138d75a).

Running PMD through Gradle 4.6:
```groovy
pmd {
    toolVersion = ...
    consoleOutput = true
    ruleSetFiles = ...
    ruleSets = []
}
```

With different versions of PMD, the time taken for `./gradlew clean pmdMain pmdTest --continue`:
- 6.1.0: 1m56s ([reference](https://travis-ci.org/wkurniawan07/repo/builds/374012743))
- 6.2.0: 3m6s ([reference](https://travis-ci.org/wkurniawan07/repo/builds/374014192))
- 6.3.0: 4m8s, plus all the false positives from #1067 ([reference](https://travis-ci.org/wkurniawan07/repo/builds/374015205))

The time taken is not only due to variance from Travis CI runs; it tallies with the time taken when running the same in my local Mac OS environment.

**Comment by jsotuyod** [comment]
@wkurniawan07 amazing, thanks! I'll review and let you know

**Comment by jsotuyod** [comment]
I've confirmed the issue. On my personal tests with the project supplied by @wkurniawan07 I see a great degradation from 6.1.0 to 6.2.0, while from 6.2.0 to 6.3.0 I see a little improvement of a few seconds per run (most probably down to #949).

The degradation introduced in 6.2.0 is effectively related to logging, and specially to those logs in `ClassTypeResolver` as stated by @davidburstromspotify. Even though the logs are guarded, when running through ant (which is the integration used by Gradle in turn), we are doing:

https://github.com/pmd/pmd/blob/dd2dcf6357103c526c238bd033fccb2c5368765b/pmd-core/src/main/java/net/sourceforge/pmd/ant/internal/PMDTaskImpl.java#L274-L275

Which effectively has the logger believe it's running in `LogLevel.FINEST`, trusting Ant will filter the output (which it does, but doesn't prevent the concatenations and logging overhead).

Unfortunately, there is no way I know of to obtain the current "log level" from an Ant `Project`, which makes it hard to set our own logging to the proper level (regardless of the logging framework). I need to investigate this further, but this could be a serious constraint on our options.

I'll keep you posted. @adangel any ideas are welcomed

**Comment by jsotuyod** [comment]
A Proof of Concept patch is available in #1080, confirming that being able to tell beforehand what Ant would log actually fixes the issue.

**Comment by adangel** [comment]
@jsotuyod The log statements have been introduced by me at 7aaa9966c2145beac7a320e93d31387473155c57 when fixing AvoidCatchingThrowable and EmptyCatchBlock. Before, we completely ignored these exceptions.
Looking at the logs, we log mostly irrelevant information, since we try with brute force any combination for on demand imports. So - at least ClassNotFoundException should be completely ignored.
I think, if we get a LinkageError, this would be an indication of an incomplete auxclasspath, correct? It means, we found the class, but could not load it, because it references other classes which are not available. We could even think about raising the log level for LinkageError.

**Comment by davidburstromspotify** [comment]
We (Spotify) would actually prefer not to care about incomplete auxclasspaths. PMD still provides us with highly useful feedback without it, and if we don't need to compile sources, this feedback can be provided through git hooks nearly instantaneously.

**Comment by jsotuyod** [comment]
@adangel your reasoning is correct. I think we can ignore `ClassNotFoundException`, but I think the underlaying issue with how we log under Ant remains. The same issue will arise over and over again as long as we remain innocently logging in `FINEST`

**Comment by adangel** [comment]
@jsotuyod That's correct - we'll need both. Could you nevertheless remove the logging in the ClassNotFoundException case in your PR #1080 ? Thanks!

**Comment by jsotuyod** [comment]
Yes I will

**Comment by jsotuyod** [comment]
@fflatorre yes, this issues specific to Ant and Gradle. Maven doesn't use PMD that way.

PMD does a lot more things in later versions, which may translate to a slightly slower run, but definitely not of the magnitude here described.

**Comment by adangel** [comment]
@fflatorre  The logging problem is also visible in maven, if you run in debug mode (`-X`). However, you can workaround this by disabling the pmd logs (`-Dpmd.showPmdLog=false`).

**Comment by jsotuyod** [comment]
but that's only when running Maven in debug mode (`-X`), on Gradle / Ant this occurred all the time, regardless of flags.

**Comment by fflatorre** [comment]
@jsotuyod @adangel thanks for the clarification !
