### ISSUE TITLE
[java] UseStringBufferForStringAppends shouldn't apply to prepending

### ISSUE THREAD

**Issue by victornoel** [pmd/pmd#1088]
Please, prefix the report title with the language it applies to within brackets, such as [java] or [apex].
If not specific to a language, you can use [core].

**Affects PMD Version:** 5.4.1

**Rule:** UseStringBufferForStringAppends

**Description:** 

When prepending, using `StringBuilder` or `StringBuffer` won't improve performances at all.
See https://stackoverflow.com/a/5931267/9046139 for a discussion about this for example.

**Code Sample demonstrating the issue:**

```java
        String name = this.source.getSimpleName() + this.suffix;
        Element parent = this.source.getEnclosingElement();
        while (parent.getKind() != ElementKind.PACKAGE) {
            name = parent.getSimpleName() + name;
            parent = parent.getEnclosingElement();
        }
        return name;
```

**Running PMD through:** *[qulice](https://github.com/teamed/qulice)*

**Comment by oowekyala** [comment]
There is still a performance improvement from using a StringBuilder in this case. The answer you linked correctly states that this is not an *optimal* usage of a stringbuilder. However, it is still more efficient than concatenation because it uses a single stringbuilder for the entire loop instead of one per iteration.

With concatenation,
```java
while(...) s = i + s;
```
is equivalent to 
```java
while(...) s = new StringBuilder().append(i).append(s).toString();
```

[This small benchmark](https://github.com/oowekyala/pmd-jmh/commit/cd5105886cc10f543fd7253ee4abc5197b4e7766) illustrates the difference, eg on OpenJDK 13:

```
    Benchmark                  Mode  Cnt   Score   Error  Units
    MyBenchmark.withConcat     avgt    4  20,481 ± 0,443  ms/op
    MyBenchmark.withSbAppend   avgt    4   0,097 ± 0,001  ms/op
    MyBenchmark.withSbPrepend  avgt    4   3,159 ± 0,048  ms/op
```

**Comment by victornoel** [comment]
@oowekyala very interesting, thank you for the explanation!
