### ISSUE TITLE
[java] ClassNotFoundException while running pmd java custom rules with gradle

### ISSUE THREAD

**Issue by nareshl119** [pmd/pmd#1132]
Please, prefix the report title with the language it applies to within brackets, such as [java] or [apex].
If not specific to a language, you can use [core].

**Affects PMD Version:** 
6.3.0
**Rule:**

**Description:**
Hi All,

We are using gradle to run pmd rules. By default gradle is using pmd 5.6. If we hard code toolversion to 6.3.0, then we are getting ClassNotFoundException for java custom Rule Class. 
Can you help us to fix this issue as we wanted to use latest version to write custom rules for xml.

And also, Can you pleas help us to understand below points.
1. We have written java custom rules and wanted to run these rules againt our internal projects. How can we acheive this? Currently these rules are getting executed against the project in which we have these custom rules.
2. We have set different rule priotities in ruleset.xml file. But, there is no change/differenciation between high priority rule violation and low priority violation in the end report. Our requirement is to be able to distinguish rule violations based on rule priority (Like, high priority rule violations in RED in color). How can we achieve this? or can we customize the end report?

Thank You in Advance.

Best Regards,
Naresh.

**Code Sample demonstrating the issue:**

We are also sharing the sample source code. Can you please verify and let us know what we are missing?
[pmd xml java rules.zip](https://github.com/pmd/pmd/files/2024762/pmd.xml.java.rules.zip)

```

```

**Running PMD through:** *[CLI | Ant | Maven | Gradle | Designer | Other]*
Gradle

**Comment by oowekyala** [comment]
My 2 cents about this

For some reason the `pmd 'com.sample:pmd-xml-java-rules:0.0.1-SNAPSHOT'` doesn't really work as expected. But:
* For this particular project structure, you may use `pmd rootProject` instead.
* To restrict the dependency to only the custom rule classes and not the rest, you could use a SourceSet. For instance, you'd declare your dependency as `pmd sourceSets.pmdCustomRules.output`, where `pmdCustomRules` is a sourceset declared beforehand which includes the sources of your custom rules.

Those only work for your current setup, ie with rules executed against the project in which they're defined. 

Since you want to have a project define your rules and other projects use them, AFAIK the solution is to use [repositories](https://docs.gradle.org/current/userguide/repository_types.html). So you could e.g. push your rule artifact to a public repository like Maven Central, use a custom Maven/Ivy repository for your org... And then declare a dependency on it in the projects that consume your rules with eg `dependencies.pmd('groupId:custom-pmd-rules:LATEST')` or in the `dependencies` block. 

I don't know if you can customize the report in pure Gradle, especially the html report which doesn't contain much info. The XML report preserves the rule priority though, so you could consider using XSLT to turn it into an HTML page if that's how you'd like to read it.
