### ISSUE TITLE
[core/java/jsp] PMD uses outdated saxon version

### ISSUE THREAD

**Issue by krzyk** [pmd/pmd#1294]
PMD uses dependency:
```
<dependency>
    <groupId>net.sourceforge.saxon</groupId>
    <artifactId>saxon</artifactId>
    <version>9.1.0.8</version>
</dependency>
```

Which is outdated (release was in 2010), newer saxons are released under net.sf.saxon groupId, and latest is (from July 2018):
```
<dependency>
    <groupId>net.sf.saxon</groupId>
    <artifactId>Saxon-HE</artifactId>
    <version>9.8.0-14</version>
</dependency>
```

Using the outdated one, causes problems in projects that use have e.g. both PMD and checkstyle as a dependency (like qulice) because checkstyle uses the newer saxon and there are conflicts between classes used.

**Comment by oowekyala** [comment]
@krzyk Unfortunately upgrading Saxon would break our APIs: the newer versions have removed support for XPath 1.0 compatibility mode, and are not binary-compatible. This change is proposed for 7.0.0 though, which is a few months down the road

@adangel @jsotuyod Until then, maybe it would make sense to shade saxon into pmd-core, like for Jaxen?

**Comment by jsotuyod** [comment]
I'm not sure... shouldn't Maven isolate each plugin's classloader to avoid these kind of issues? I've long used both PMD and Checkstyle side by side and I don't recall ever coming across something of this sort... Moreover, even after the programmed update for PMD 7, nothing prevents this from happening again as our upgrade / release cycles are not in sync with Checkstyle's nor any other tool out there (nor need to be).

I just checked the qulice code and it's embedding all tools without isolation, so they fail where Maven can succeed when using the checkstyle and pmd plugins on their own.

Shading is also a bad idea... we bloat our binaries for the sake of usecases, such as this one, that are not the norm for our users, preventing any chance people already have a saxon binary in their local repositories they may use. I think it's up to qulice to work around this if they want to be compatible and future-proof.

Also, as I checked their source I noticed qulice does not setup the auxclasspath, so the PMD results in qulice are not the same quality as using the PMD plugin directly. They are also launching a PMD analysis per file and not using the cache, so upcoming multifile analysis won't work for them and all incremental analysis support and benefits are gone. I think there are also some interesting points for them to leverage PMD's feature set.

**Comment by krzyk** [comment]
@jsotuyod Good points, I'll close this issue then.

ButI've got two questions:
- do you have a suggestions how qulice could isolate all the tools embedded together?
- what is auxclasspath and how it can help with getting better quality of code analysis?

**Comment by jsotuyod** [comment]
@krzyk I've not tested it, but you can probably define multiple instances of [`dependencies:copy-dependencies`](https://maven.apache.org/plugins/maven-dependency-plugin/copy-dependencies-mojo.html) task for each tool (rather than have them as dependencies to the main project), each using a different `outputDirectory`. This should download each tool and it's transitive dependencies into a separate folder when packaging, embedding the tools in your jar.

Then, for each tool, create a new [`URLClassLoader`](https://docs.oracle.com/javase/7/docs/api/java/net/URLClassLoader.html#URLClassLoader(java.net.URL[],%20java.lang.ClassLoader)), pointing to the jars in each folder from the previous step. This will allow each tool to run on an isolated classloader, where each can see a different version of the same classes without an issue. You will have to load classes from the classloader explicitly (`classLoader.loadClass("net.sourceforge.pmd.PMD")`) and use some reflection but other than that you are ok.

As for the auxclasspath... PMD has long supported type resolution, and since ~PMD 5.5 to date that feature has improved a lot in quality and more rules have been updated to use it. Basically, when PMD finds a type reference, method call, class definition or whatever, it doesn't just know the text (ie: `String`), but it can also know the actual Java class in use (`java.lang.String` vs `my.app.phony.String`), and all it's methods, properties, etc. This allows us to know a lot more about the classes we analyze (ie: is this class transitively implementing `Serializable`?) which avoids both False Positives *and* False Negatives.

You can find several issues related to not using type-resolution. Just to name a few:
* #936 - UnusedImports false positive with Javadoc link
* #1021 - False positive for `DoNotExtendJavaLangError`
* #1078 - MissingSerialVersionUID rule does not seem to catch inherited classes

To do this, PMD needs to take the same classpath the application would when running:
* References to all dependencies' jars
* References to all the application's classes

As you are using PMD's code directly, you can use a single call to `PMDConfiguration.prependClasspath`

https://github.com/pmd/pmd/blob/1cab291ee8ba6e96209868a2cd6bfc055c69d599/pmd-core/src/main/java/net/sourceforge/pmd/PMDConfiguration.java#L190

The string passed in, is a standard Java classpath (references to directories / .class / .jar files separated by `:` (colon))
