### ISSUE TITLE
[core] <ruleset> can't recognize absolute path

### ISSUE THREAD

**Issue by 171563857** [pmd/pmd#1332]
i was use "mvn install" in children module and "pmd" plugin was in parent module
pmd can't recognition `<ruleset>` path when i run 'mvn install' in children module
but it will success when i run 'mvn install' in parent module
thx!

**Comment by 171563857** [comment]
it's my folder tree
E:. //parent module
├─pom.xml    //parent module maven config file
│      
├─gb-manager    //children module
│  └─pom.xml    //children module maven config file
│              
└─qa
    └─pmd
            exclude-pmd.properties
            pmd-ruleset.xml    //ruleset config file

i use absolute path to set '<ruleset>' but still can't find 'pmd-ruleset.xml'

**Comment by jsotuyod** [comment]
@171563857 could you please provide the PMD plugin configuration you are using in Maven for both parent and child modules?

**Comment by adangel** [comment]
@171563857 Multimodule configuration can be a bit tricky. Please have a look at http://maven.apache.org/plugins/maven-pmd-plugin/examples/multi-module-config.html which describes a separate "build-tools" project, which will contain the ruleset, so that it can be shared across different modules in a multi-module project.

We probably should update our own doc to mention this solution here https://pmd.github.io/pmd-6.7.0/pmd_userdocs_tools_maven.html ...

Btw. - the maven-pmd-plugin resolves the ruleset and makes it available for PMD by copying the resolved ruleset into the `target/` folder.

**Comment by 171563857** [comment]
@adangel @jsotuyod 

pmd choose the child modules config plugin's path as  ROOT path if i use build
the ROOT context depend on where i was use build's path 
so it can't find the ruleset config file

i will try use internal library just like "pmd_userdocs_tools_maven"

thx : )
