### ISSUE TITLE
[doc] broken link for cyclo metric

### ISSUE THREAD

**Issue by jsotuyod** [pmd/pmd#1466]
The section for rule [`CyclomaticComplexity`](https://pmd.github.io/pmd-6.9.0/pmd_rules_java_design.html#cyclomaticcomplexity) has a "For more details on the calculation, see the documentation of the Cyclo metric.", which has a broken link.

I'm unsure where this link is supposed to link /cc @oowekyala

**Comment by oowekyala** [comment]
It's supposed to link there: https://pmd.github.io/pmd-6.9.0/pmd_java_metrics_index.html#cyclomatic-complexity-cyclo

The link in the rule is absolute which is why it fails:

https://github.com/pmd/pmd/blob/fda3aa16a368aa9ce1d3586734927b6fe8738d1b/pmd-java/src/main/resources/category/java/design.xml#L413
