### ISSUE TITLE
[core] Analysis cache fails with wildcard classpath entries

### ISSUE THREAD

**Issue by ColColonCleaner** [pmd/pmd#1477]
**Affects PMD Version:** 6.9.0

**Rule:** Runtime, no specific rule.

**Description:** We have a file path variable on the stack that ends with a * for wildcarding. For backwards compatibility reasons this cannot be removed. If I add the cacheLocation parameter to the pmd call with any path, absolute, relative, parameterized, etc, it throws the following error when running the PMD target:
c:\absolutepath\build.xml:1301: java.nio.file.InvalidPathException: Illegal char * at index 35: c:\wildcardingpath\*
Adding that parameter appears to make PMD look at other variables on the stack that aren't directly provided to it. 
We had this same issue with junit and javac but those targets allow the includeAntRuntime="false" parameter to forcibly tell them to ignore all other variables on the stack aside from what you pass into the target. This parameter for ignoring other variables doesn't appear to be allowed on PMD.

**Running PMD through:** *[Ant]*

I am running this through Java 11 64 bit on a windows 7 machine.

**Comment by adangel** [comment]
Hi, thanks for the report!

Could you copy your ant script (or at least the PMD part of it) here?

Just to make sure, I understand your problem: you are using the `<cacheLocation>c:\wildcardingpath*</cacheLocation>` and that causes a problem. Is `c:\wilcardingpath*` a valid path at all? How did you create it? The asterisk is usually expanded by a shell but here we have no shell to interpret the wildcard.

Please also note, that the cacheLocation should point to a specific file - if you use a wildcard, it is not unique anymore - we don't know, which file we should write to/read from if we are provided with multiple files (or in other words: the cacheLocation is given ambiguously...)

**Comment by ColColonCleaner** [comment]
This wildcarding path is not associated with PMD at all, it's just some path in another variable on the stack. According to the PMD docs there isn't a cacheLocation element on the pmd target, it's added as a parameter on the target. I just tried it the way you mentioned and the error "pmd doesn't support the nested 'cacheLocation' element" occured.
If I include the cacheLocation parameter the illegal char error occurs, if I do not include the cacheLocation parameter PMD runs as normal without caching.

Here ${env.DCSDIR}/${cache.file} translates to: c:\dev\workspace\181branch\wmd/pmdrules.cache

Github's system really hates XML huh. Linking a picture. 
![image](https://user-images.githubusercontent.com/1903507/48805361-ce208c80-ecdc-11e8-836f-e285949103e5.png)

**Comment by ColColonCleaner** [comment]
Here is the Illegal character error. This path it mentions is not passed into PMD at all, it's just present in the ant environment at runtime, one of the paths we use for another product.
![image](https://user-images.githubusercontent.com/1903507/48805732-bf86a500-ecdd-11e8-97cb-90c1d4d6ccea.png)

**Comment by adangel** [comment]
>  it's added as a parameter on the target. I just tried it the way you mentioned and the error "pmd 
> doesn't support the nested 'cacheLocation' element" occured.

Oh, yes. My bad.

The snippet from build.xml and the stacktrace help a lot, however:
It happens not when we try to read/write the cacheLocation file, but when we try to determine, whether the execution classpath or the auxclasspath has changed from the last run (therefore we compute a checksum over the classpath).

-> The problem is, that we obviously can't deal yet with a wildcard classpath entry.

Until this bug is fixed, the only workaround is, that you explicitly specify `pmd.classpath` without a wildcard.

One note to your PMD task configuration though:

For the auxclasspath element, you are using the same classpath as you use for executing PMD itself:

```xml
<auxClasspath>
    <path refid="pmd.classpath"/>
</auxClasspath>
```

You should actually use the classpath, that you are using for compiling your project. This means, the auxclasspath should contain all the jars that you need during compilation. This makes sure, that PMD has the same knowledge as the compiler does and can figure out the types of various statements.

**Comment by adangel** [comment]
Or of course, can disable the cache:

```xml
<pmd ... noCache="true">
...
 ```
