### ISSUE TITLE
Feature request: Warn on throwing exceptions

### ISSUE THREAD

**Issue by mcandre** [pmd/pmd#1572]
Now that Java 8+ supports Optionals, we can improve our API's by returning errors as values, as opposed to using convoluted try/catch logic. Could we get a rule, disabled by default, that warns when:

* RuntimeException's or child classes are thrown, as these can lead to surprising production failures
* A method or interface declares that exceptions are expected to be thrown
* Checked exceptions are thrown

**Comment by jsotuyod** [comment]
@mcandre Optionals are designed to avoid returning null values in an attempt to avoid null-checking / NPEs, not to replace exceptions altogether. Exceptions are still needed to, well, deal with exceptional cases.

Think for instance when building a REST API, in a standard 3-layered system of controller -> service -> DAO. Having a database unreachable and not finding a row in the database can hardly be reduced to the same scenario of returning `Optional.empty()` from the DAO. Otherwise, neither the service nor the controller can tell the difference, and the response would be inconsistent: is this a 404 Not Found or a 500 error?

This is therefore not something we should encourage / ship with PMD. It may be something that applies particularly to you and your project, and if so, you are encouraged to [create an XPath rule](https://pmd.github.io/pmd-6.10.0/pmd_userdocs_extending_writing_xpath_rules.html) for this in [your personal ruleset](https://pmd.github.io/pmd-6.10.0/pmd_userdocs_making_rulesets.html). The designer should be a great aid in doing so, and as you want to flag all `throw` and `throws` it should be very easy!

If you need assistance in this process, feel free to ask. In the meantime I'm closing this as the request to include this in PMD is rejected.
