### ISSUE TITLE
[java] Turn off AvoidLiteralsInIfCondition

### ISSUE THREAD

**Issue by mcandre** [pmd/pmd#1599]
**Affects PMD Version:**

4.2.6+

**Rule:**

AvoidLiteralsInIfCondition

**Description:**

This rule creates unnecessary variables in many algorithms, especially for well known numerical constants. A case could be made for encouraging string literals to move out of source code into .PROPERTIES files, but in general this rule does more harm than good. What, you're telling me I can't `if (y > 1)` without declaring `x = 1; if (y > x)` every time?!

As a workaround, I am configuring this in my rulesets.xml:

```xml
<rule ref="category/java/errorprone.xml">
    <exclude name="AvoidLiteralsInIfCondition" />
</rule>
```

**Comment by mcandre** [comment]
> Which other "well known numerical constants" do you think are good candidates to be whitelisted rather than asking to be included as a descriptive constant?

All numerical values.

Yes, a good precept is to declare sensitive values as constants, such as Pi. But the exceptions are of a significant magnitude that this rule is practically more trouble than it is worth.

**Comment by adangel** [comment]
Cross-Post: https://sourceforge.net/p/pmd/discussion/188194/thread/336c5befc3/?limit=25#328c

**Comment by jsotuyod** [comment]
Closing as stale.

PMD 4.2.6 literally implemented this as:

```
//IfStatement/Expression/*/PrimaryExpression/PrimaryPrefix/Literal
```

Since then PMD has:
- whitelisted null and boolean literals
- included a `ignoreMagicNumbers` property that allows by default `0` and `-1`
- included a `ignoreExpressions` property (defaults to `true`) to only look at literals within the condition (this wasn't part of the rule at the time of the issue report)

I'm not saying the rule is perfect, but for sure it should be significantly less noisy than it was in the version against which this issue was created.
