### ISSUE TITLE
[java] Drop DataClass

### ISSUE THREAD

**Issue by mcandre** [pmd/pmd#1608]
**Affects PMD Version:** 

6+

**Rule:**

DataClass

**Description:**

This rule demands that all classes feature do-something methods, when in fact, most classes are just data classes. Yes, some coders may make the mistake of declaring two classes, one with data and another with methods manipulating the data. But in practice, this risk is low, and the benefits of data classes are high.

**Running PMD through:** *[CLI | Ant | Maven | Gradle | Designer | Other]*

Gradle

**Comment by jsotuyod** [comment]
@mcandre this rule is intended to avoid the [Anemic Domain Model](https://en.wikipedia.org/wiki/Anemic_domain_model) anti-pattern in favor of using [Domain-Driven Design](https://en.wikipedia.org/wiki/Domain-driven_design).

Of course data classes may have it's usages (specially under the guise of Data Transfer Objects), but that's a usage that's easily whitelisted (ie: suppressing the rule for a given `dto` package).

As already stated in #1600, #1601 and #1602, PMD rules are available for any team that wants to enforce them. Please, stop asking to drop rules simply because you don't personally use them. We won't drop a rule unless:
* it's very clearly harmful
* it's being superseded by a broader / more powerful rule.
