### ISSUE TITLE
UseVarargs -> AvoidVarargs

### ISSUE THREAD

**Issue by mcandre** [pmd/pmd#1620]
Oracle officially discourages varargs. Varargs often present performance loss and bugs and bad things. Let's reverse UseVarargs as AvoidVarargs.

https://docs.oracle.com/javase/8/docs/technotes/guides/language/varargs.html

**Comment by oowekyala** [comment]
I don't see anything in that link that mentions performance issues or bugs. Oracle doesn't discourage varargs, it merely warns about overloading:

> Generally speaking, you should not overload a varargs method, or it will be difficult for programmers to figure out which overloading gets called. 

Performance-wise the only *potentially* undesirable side-effect of using varargs is that varargs invocation creates a new array each time, which could be avoided when all the arguments are known constants. But 
* this only matters at call sites. It's none of the concern of the API designer.
* some APIs actually rely on that behaviour, e.g. `Arrays.asList`. Generally speaking any varargs method that uses the array in other ways than just to extract its elements can't be blamed for the array creation, since it *expects* that behaviour.
 

DontOverloadVarargs would be a good fit for a new built-in rule. I think AvoidVarargs wouldn't.

**Comment by oowekyala** [comment]
This is not justified and can be closed I think
