### ISSUE TITLE
[core] regex for multivalue delimiter

### ISSUE THREAD

**Issue by Vampire** [pmd/pmd#1680]
It would be nice if the multivalue delimiter could be a regex, this way you could e. g. define `\s*,\s*` as delimiter and so could write more readable values like `foo, bar, baz` or `foo | bar | baz` instead of `foo,bar,baz` or `foo|bar|baz` or could maybe even make the value multi-line like
```
foo |
bar |
baz | bam
```

**Comment by Vampire** [comment]
Oh, just have seen that you cannot modify the delimiter, it is valid according to the XSD, but has no effect, I guess it is also just for rule declaration currently, maybe it would make sense to make this configurable on rule usage configuration too?

**Comment by oowekyala** [comment]
Delimiters will be mostly dropped from 7.0.0, instead, a more flexible XML syntax will be introduced. This is described on [the wiki](https://github.com/pmd/pmd/wiki/Schema-version-7.0.0#properties). The fact that the delimiter is valid according to XSD is because the schema is way too lax. Like the `type` attribute, that attribute is supposed to only be used in property definitions. Separating property definition from property overriding to avoid unexpected stuff like that is a primary design goal of the new ruleset schema for 7.0.0.

**Comment by Vampire** [comment]
Ah, I see, nice, then forget it. :-)
