### ISSUE TITLE
[java] argument for star import

### ISSUE THREAD

**Issue by zenglian** [pmd/pmd#1732]
**Affects PMD Version:** 
6.7

**Rule:**
"Avoid unused import statements to prevent unwanted dependencies. This rule will also find unused on demand imports, i.e. import com.foo.*."

https://github.com/pmd/pmd/blob/master/pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/UnusedImportsRule.java

**Description:**
(1) Star import would not introduce unwanted dependencies as java compiler automatically converts star import to single imports (check the .class file).
(2) Star import is not bad, see page 307, "Clean Code" by Robert Martin.

**Code Sample demonstrating the issue:**
import static j2html.TagCreator.*;

**Running PMD through:** *[Idea plugin]*

**Comment by jsotuyod** [comment]
Thanks for the report.

I think the problem here lies with the rule description, as "dependency" is foreign to Java code.

The rule itself does not in any way consider on demand imports bad. It simply flags **unused** imports (which may happen to be on demand) to unclutter the code.

If you use any member / type imported from an on demand import the rule will simply ignore it.

**Comment by zenglian** [comment]
`import *` does not mean import all, thus the word "usused" is not accurate here.

**Comment by jsotuyod** [comment]
I never said "all", I actually said "any".

The rule **doesn't** intend you to rewrite the on demand import as explicit imports. It's not flagging all on demand imports indiscriminately. 

If the import statement can completely be removed without further changes and the code is still able to compile, then the import is unused, and flagged by the rule for removal.

I'm unsure there is an actual case for writing an import the code doesn't actually need. But if there is one, please enlight me.

**Comment by zenglian** [comment]
No it may not working the way as you thought. In the code sample above, though *many* (static functions) are used (and of course many compile errors if the line is removed), it's still reporting the issue.

**Comment by jsotuyod** [comment]
Hmmm, interesting. If that's the case, this may be a false positive...

Can you provide a full working sample to reproduce your issue?

**Comment by jsotuyod** [comment]
Oh, I think I know what the problem is...

You have no auxclasspath information available.

There are 2 problems here:

Firstly, we are flagging in the absence of information, which we may fix easily.

Secondly, the idea plugin you are using (which isn't an official plugin by the PMD team) is failing to provide pmd with all information required for analysis, so the results are poorer than they should.

We should change the default on this rule, and you should consider other means of running pmd / raising an issue with the people developing that plugin.

**Comment by zenglian** [comment]
o... it works fine with gradle pmd plugin. shall I close it?
