### ISSUE TITLE
[java] Effectively-final variable used in try-with-resources causes PMDException

### ISSUE THREAD

**Issue by jiangty-addepar** [pmd/pmd#1766]
**Affects PMD Version:** 
5.8.1, 6.6.0, 6.13.0

**Rule:**
n/a

**Description:**

When trying to parse code that uses language change 2 in [JEP-213](https://openjdk.java.net/jeps/213), "Allow effectively-final variables to be used as resources in the try-with-resources statement", PMD throws `PMDException: Error while parsing <file>`.

(In v5.8.1, the error was `Error while parsing <file>`, without `PMDException`.)

**Code Sample demonstrating the issue:**

Old code before JEP-213:
```java
private void process(Stream<?> stream) {
    try (Stream<?> forClose = stream) {
      forClose.forEach(o -> {});
    }
}
```

New code after JEP-213, causing `PMDException: Error while parsing <file>`
```java
private void process(Stream<?> stream) {
    try (stream) {
        stream.forEach(o -> {});
    }
}
```

**Running PMD through:** *CLI*

**Comment by jsotuyod** [comment]
@jiangty-addepar I can't reproduce your error. Concise try-with-resources have been supported since PMD 6.0.0, provided you are analyzing your source as Java 9+.

Please, provide the full command line being used, as well as a complete stacktrace (if using xml reports, the full error is available in the report itself).

**Comment by jiangty-addepar** [comment]
@jsotuyod Looks like I was using language level 1.8 still... oops! The warnings are gone now :) Thanks!
