### ISSUE TITLE
Issue while downloading pmd-plugin from Eclipse Mars(4.5.2)

### ISSUE THREAD

**Issue by trishul14** [pmd/pmd#187]
I get the following exception:

> [Unable to read repository at https://sourceforge.net/projects/pmd/files/pmd-eclipse/update-site/site.xml.
sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target]

**Comment by adangel** [comment]
Hi, thanks for reporting.

This seems to be a known problem with an older JVM (see https://sourceforge.net/p/pmd/bugs/1528/).

Make sure, you have at least java8 update 101 installed - otherwise Java doesn't trust "Let's Encrypt" certificates.

If it still doesn't work, you can also download the update file from github: https://github.com/pmd/pmd-eclipse-plugin/releases/latest

**Comment by jsotuyod** [comment]
@trishul14 any luck with this? Can we close this or do you need any further assistance?

**Comment by adangel** [comment]
I'll close this issue here. Please use pmd/pmd-eclipse-plugin#19 to continue the discussion.
