### ISSUE TITLE
[doc] Error in changelog 6.16.0 due to not properly closed rule tag

### ISSUE THREAD

**Issue by Dichotomia** [pmd/pmd#1896]
Error in this section:

"The Java rule CommentDefaultAccessModifier (java-errorprone) now by default searches for any unclosed java.lang.AutoCloseable resource. This includes now the standard java.io.*Stream classes. Previously only SQL-related resources were considered by this rule. The types can still be configured via the types property. Some resources do not need to be closed (e.g. ByteArrayOutputStream). These exceptions can be configured via the new property allowedResourceTypes. In order to restore the old behaviour, just remove the type java.lang.AutoCloseable from the types property and keep the remaining SQL-related classes."

I think the rule is "CloseResource"

**Comment by adangel** [comment]
Thanks for catching this!

We actually changed both rules CommentDefaultAccessModifier and CloseResource, but the text got mixed up due to a syntax error in the liquid macro we use (I used unfortunately `%)` instead of `%}` for closing the rule tag).

The full text is here: https://github.com/pmd/pmd/blob/pmd_releases/6.16.0/docs/pages/release_notes.md

I'll update the release notes manually for now.

For the future, we should do this (since this is not the first time this happened):
*  integrate the changelog renderer into the build, that means, that it is executed during `mvn clean verify`
* make the changelog renderer fail (and the build), if the rule_tag has more than one argument, which is a indication of this problem.
