### ISSUE TITLE
[all] Integrate new PMD logo

### ISSUE THREAD

**Issue by adangel** [pmd/pmd#1931]
With #1663 we decided for a new logo, now we need to integrate it into the various locations for PMD 7.

- [x] #2496
- [x] #2497
- [x] #2498

## Related issues

*   Depends on
    *   [x] [Call For Logo #1663](https://github.com/pmd/pmd/issues/1663)
    *   [x] [[core] Host own javadoc on docs.pmd-code.org #2417](https://github.com/pmd/pmd/pull/2417)

### Probably for PMD 7
* #4307
* pmd/pmd-designer#43
* pmd/pmd-eclipse-plugin#122

**Comment by rsoesemann** [comment]
@adangel @oowekyala any objection to already use the new logo for our Twitter account?

**Comment by adangel** [comment]
@rsoesemann :+1: feel free, to update the logo there

**Comment by jborgers** [comment]
I am very late in the game here. I really like changing the pistol logo to this one, it is much of an improvement.
I just have my doubts about the words: "Code Quality Matters". This seems to me as said by someone who is ignored too much. 

I would prefer an stronger statement because it deserves that, since fixing things in de code immediately will save a lot of effort, bug hunting and costs later, what you get with bad quality in production.

So, I like to suggest the following words: PMD - "Code Quality is Key". 
I also think the rhyme helps to be catchy.
What do you think?

**Comment by rsoesemann** [comment]
@jborgers  "Code Quality Matters" was only part of my initial proposal. it will not be part of the new logo. @adangel and @oowekyala had similar objections. I just put the old version as Twitter background but none of official places will show it.

**Comment by jborgers** [comment]
Okay, good to know. Is there a new phrase? What about the one I propose?

**Comment by adangel** [comment]
Closing this tracking issue as done. The remaining tasks are either tracked by #3898 or are postponed.
