### ISSUE TITLE
[core] Enable type resolution by default for XPath rules

### ISSUE THREAD

**Issue by oowekyala** [pmd/pmd#2048]
Type resolution has been enabled by default for all rules extending AbstractJavaRule for a while. The only place where the `typeresolution` attribute needs to be mentioned in XML is for XPath rules, which extend directly AbstractRule. This behaviour is surprising, and as pointed out in pmd/pmd-designer#28, the designer wasn't aware of it.

So instead of making the designer add a `typeresolution='true'` attribute, I would rather remove the need for it altogether before 7.0.0. Java is the only language that supports type resolution anyway, and the XML attribute as well as the method on the Rule interface will disappear.

**Comment by adangel** [comment]
I think, the only reason, why it is not enabled by default, is potential performance slowdown. But I would question that, since typeResolution is enabled anyway, if at least one rule in the ruleset uses typeRes, and the chances are very high I'd say, that you have at least one such rule...

Hm... we don't even seem to mention that fact in our documentation: https://pmd.github.io/latest/pmd_userdocs_extending_writing_pmd_rules.html#i-need-some-kind-of-type-resolution-for-my-rule

I'm fine with enabling typeResolution by default for 6.19.0.

> and the XML attribute as well as the method on the Rule interface will disappear.

In 7.0.0, you mean? Just to be sure....

**Comment by caseyduquettesc** [comment]
@adangel @oowekyala  IMO, this should have been given more attention in the release notes. I was upgrading from 6.15 to 6.30 and was facing a tremendous performance degradation. We use our own ruleset files and all of our rules are `XPathRule`'s. It took a while to track down the version that introduced the regression due to the performance hit and then look at the change list for suspects. PMD 6.19 introduced a performance degradation for us where an analysis that previously took 2 minutes with no analysis cache began taking >30 minutes.
