### ISSUE TITLE
[core] Shortnames parameter does not work with Ant

### ISSUE THREAD

**Issue by mriddell95** [pmd/pmd#2062]
**Affects PMD Version:** 
6.18.0

**Rule:**
N/A

**Description:**
I previously was able to run the short-names parameter in my ant buildscript and it would output in the report with the relative path. In 6.18.0 it appears that shortnames has stopped working with Ant. The short-names parameter does work with the PMD CLI however.

**Code Sample demonstrating the issue:**

```
<target name="pmd">
        <taskdef name="pmd" classname="net.sourceforge.pmd.ant.PMDTask">
            <classpath>
                <fileset dir="${pmdLibFolder}">
                    <include name="*.jar"/>
                </fileset>
            </classpath>
        </taskdef>
        <pmd shortFilenames="true" cacheLocation="pmd.cache">
            <formatter type="xml" toFile="pmd_report.xml" toConsole="true"/>
            <ruleset>ruleset.xml</ruleset>
            <fileset dir="${src}">
                <include name="**/Application.java"/>
            </fileset>
        </pmd>
    </target>
```

**Running PMD through:** *[CLI | Ant | Maven | Gradle | Designer | Other]*
Ant

**Comment by adangel** [comment]
Seems to be a regression of https://github.com/pmd/pmd/issues/1923

The parameter has moved to the renderers, since shortnames is just relevant for the renderers. But the renderers in the ant task are created in a different way than the renderers created by the cli. So the renderers in the ant task no nothing about shortnames and the directory prefix, that should be removed.
