### ISSUE TITLE
Remove codeclimate specific rules from Apex rulesets

### ISSUE THREAD

**Issue by AndrewRayCode** [pmd/pmd#2109]
This file has lots of Codeclimate hard coded configuration settings that aren't related to PMD nor Apex: https://github.com/pmd/pmd/blob/master/pmd-apex/src/main/resources/rulesets/apex/quickstart.xml

Codeclimate blocks engineers from getting linting parity between local development and linting in the cloud, and their rules should not be included in Apex best practice XML files. CC @adangel

**Comment by rsoesemann** [comment]
@adangel I know that we removed that old waste in an upcoming release branch but I am unsure if that was already released. @oowekyala was it 7.0?!

**Comment by adangel** [comment]
@AndrewRayCode There are no codeclimate specific rules. All rules, that PMD provides, can be used without code climate. What you see here are rule properties, that are used when generating the report format for code climate, so that sensible issue categories that code climate knows about are used. These properties are only used by the [CodeClimateRenderer](https://github.com/pmd/pmd/blob/master/pmd-core/src/main/java/net/sourceforge/pmd/renderers/CodeClimateRenderer.java) and are ignored otherwise.

We discontinue to support the code climate renderer with PMD 7, so with the next version, these properties are anyway gone - see also #1648 / #1702 .

> Codeclimate blocks engineers from getting linting parity between local development and linting in > the cloud, and their rules should not be included in Apex best practice XML files.

Just to clarify: We have no code climate rules in PMD - we have only our own rules. And you can use PMD independently of code climate...

Therefore I'm closing this issue.
