### ISSUE TITLE
[java] ExcessiveClassLength and ExcessiveMethodLength should be cognizant of lone curly braces

### ISSUE THREAD

**Issue by Fernal73** [pmd/pmd#2123]
**Affects PMD Version:** 
All.

**Rule:**

[ExcessiveClassLength](https://pmd.github.io/latest/pmd_rules_java_design.html#excessiveclasslength), [ExcessiveMethodLength](https://pmd.github.io/latest/pmd_rules_java_design.html#excessivemethodlength)

*Note:* There is a similar rule for Apex, e.g. [ExcessiveClassLength](https://pmd.github.io/latest/pmd_rules_apex_design.html#excessiveclasslength).

**Description:**

https://stackoverflow.com/q/53470043/3924108
The above StackOverflow question sought to omit curly braces from line counts.
It's worth configuring the rule to allow lone braces in a line to be ignored.

**Code Sample demonstrating the issue**

https://www.processdash.com/static/help/Topics/AdvancedTopics/CustomLOCCounter.html#CountingStandard

**Running PMD through:** *[CLI | Ant | Maven | Gradle | Designer | Other]*

**Comment by adangel** [comment]
The two mentioned rules simply look at the beginLine and endLine properties of the corresponding nodes. This means, they simply look at the raw source and just count the **lines**. If the class/method has many empty lines or has comments, these are counted as well. This means, these rules are more dependent on coding style. If you are using a coding style, that e.g. says: only one statement per line (and putting comments, empty lines aside for now), then it becomes very similar to NCSS metric (non-commenting source statements).

For NCSS there exists the rule [NCSSCount](https://pmd.github.io/latest/pmd_rules_java_design.html#ncsscount), which

> ignores comments, blank lines, and only counts actual statements

So, this rule would already ignore curly braces, since these are not statements.
Since NCSS counts statements, it doesn't matter how the code is formatted (agnostic to code style).

**Comment by Fernal73** [comment]
I'm inclined to count comments as lines of code for this rule. If comments
are necessary, they're  as important as the code, if not more.

The rule is agnostic to how curly braces are used in the three cases listed
in the referred document.

**Comment by oowekyala** [comment]
I agree with @adangel that NCSSCount is the better rule. For what it's worth, I think raw lines of code is practically worthless as a source code metric, and I'd even argue for removing those rules from PMD. I don't think those rules are worth being complicated.

**Comment by Fernal73** [comment]
I'd argue for retaining it. NCSS requires a learning curve and not everyone
is familiar with it, right away. Users could be encouraged to use NCSS via
the documentation or an informative message or both. I don't see how
allowing the option of omitting lone curly braces makes it more complex
than NCSS. It may make its implementation a bit more complicated than it
already is. That's neither here nor there.

**Comment by oowekyala** [comment]
>  I don't see how allowing the option of omitting lone curly braces makes it more complex than NCSS

I don't mean "more complex than NCSS", I mean more complex than what such a braindead metric should be allowed to get. This issue tries to address one of the shortcomings of the metric, but there are many others (like eg counting empty lines). Patching the metric would muddy its definition, and set a precedent for doing so, as well as raise questions like "why didn't they patch that other special case?" 
The thing is, the metric is by definition noisy, so there will always be "another special case". At least this definition is simple and understood by all, and for the purposes of PMD I think it's easier for everyone if that metric sticks to convention.

I agree with you that the differences between LoC and NCSS should be explained in the doc of both rules though.

> It may make its implementation a bit more complicated than it already is.

As a matter of fact it's currently impossible to implement. Nodes don't have access to their text, though I intend to fix that in an upcoming PR for 7.0.

**Comment by Fernal73** [comment]
If you don't implement stuff because the API doesn't allow it, it's a sorry
state of affairs. Why does this need nodes?

Will getting rid of this rule will increase usage of NCSS? Go ahead and
deprecate it in the upcoming releases.

I have a feeling that you'll lose more adopters than you'll gain.

(I haven't looked at the NCSS rule in depth; I have other priorities and it
doesn't throw up any errors in my code. Does it support everything you need
for it to be a more than  adequate replacement for this rule?)

https://docs.oracle.com/javase/7/docs/technotes/guides/javadoc/deprecation/deprecation.html#when


"Valid reasons to deprecate an API include:

   - It is insecure, buggy, or highly inefficient
   - It is going away in a future release
   - It encourages bad coding practices"

Do you think any of the above reasons apply or will be applicable?

**Comment by oowekyala** [comment]
To make it clear, I'm not arguing for deprecating those rules here. If anything, this is very low in my agenda and would need another discussion.

I'm arguing against handling the special case of lines with curly braces, and for retaining the current definition of "lines of code". Effectively for closing this issue as a "won't fix".

> If you don't implement stuff because the API doesn't allow it, it's a sorry state of affairs. 

I just pointed out the implementation is more complex than you imagine. That's an aside, not an argument against your suggestion. We don't dismiss valid suggestions just because the implementation is complex. Besides, I pointed out that the API will be improved to support it anyway, so I don't know where this is coming from. 

> Why does this need nodes?
 
Because those rules count the LoC of eg classes and methods and not just files. So you need to select just the text of those specific nodes if you want to filter out some lines.

> Are you mad at me or the metric?

We're talking about your suggestion, there's nothing personal about it.

> How about creating an issue that addresses rules that could be deprecated or merged and phased out?

Yes, maybe we need a designated place to collect those ideas. Off the top of my head, there's already #1629 for some of them, also the rules mentioned in https://github.com/pmd/pmd/wiki/Property-framework-7-0-0#use-case, and the currently deprecated rules everywhere.

> Also, since renaming rules is evidently breaking backwards compatibility , how about introducing a feature that allows rules to have synonyms that will be part of the documentation? A rule can thus be addressed by multiple identifiers .

I'm not sure about that. I think our current policy works pretty well (#2114). If you'd like to expand on that please create another ticket.

**Comment by Fernal73** [comment]
Why was this issue marked as an 'enhancement' if it was to be argued
against?

Secondly, the StackOverflow OP was asked to submit a PR, for the change.
That , by itself, suggests that the change was acceptable.

I was implying that if the change needs to be implemented it could be done
at the text level, rather than using the Xpath Node-based API. But I see
your point that it would mean supporting two different APIs and ways of
doing it.

Finally, you convinced me that it's worth deprecating this rule since it is
duplication of the NCSSCount rule to an extent. The salutary effect of
either rules would lead to refactoring of code. At least, that's the
intended purpose.

**Comment by adangel** [comment]
> Why was this issue marked as an 'enhancement' if it was to be argued against?

It was marked as an enhancement prior we started discussing the details. Now we know more about it.

> Secondly, the StackOverflow OP was asked to submit a PR, for the change.

If the OP would have raised the issue here earlier, we would have had this discussion earlier. You know, the Stackoverflow question is 1 year old...

> Finally, you convinced me that it's worth deprecating this rule since it is duplication of the 
> NCSSCount rule to an extent. The salutary effect of either rule would lead to refactoring of code.
> At least, that's the intended purpose.

Right, that's how I see it. Both rules have the same purpose: avoid creating classes, methods that are "too big" (whatever that means).

After the discussion here, I'm not sure, whether we really need to deprecate this rule. If we deprecate it, we need to explain, why. And if we don't, we need to extend the description of the rules. The content could be very similar, something along the lines: "The rule is based on the Lines of Code (LOC) metric. This metric is very noisy in the sense, that it can be easily bypassed by developers. E.g. if they hit this rule, they could just stuff multiple statements on single lines to "save" lines of code, which contradicts the purpose of the rule. So, if you want to use the rule, you should have a mechanism in place to enforce a code style (such as checkstyle)."

Since you can bypass the rule by just writing your big method in a single line, I don't think, that it matters, whether the curly braces are counted or not (it would be anyway +/- 1 or two lines).

**So, what are the next steps here?**

* Can we get an agreement what do? Here are the options I see:
    * Deprecate the rules? -> if yes, I'll change the label from "enhancement" to "documentation"
    * Leave the rules but update their description? -> if yes, I'll change the label from "enhancement" to "documentation"
    * Enhance the rules (somehow - as Clément pointed out, would be very difficult at the moment) to ignore curly braces. And risk, that we will next add code to ignore blank lines. And then comments. And then ...
    * Do you see other options?


> Another point to note: The visible top menu bar on a phone is Code, Issues, Pull Requests, 
> Projects. The other elements are not visible unless scrolled to. There is no scroll indicator either.

Sorry, but that's horribly off topic! That's a github platform issue, raise a bug with them. But they will tell you, the scroll bar indicator is shown once you scroll. And that's standard user experience.

**Comment by Fernal73** [comment]
My suggestion, with the synonyms, is that the rules be mapped to NCSSCount
so that if the rules are used, NCSSCount is invoked instead.

It's worth educating developers about NCSS metrics rather than dumbing down
anything of the sort.

If the rules are to be retained as they are, then it's worth implementing
this issue since I foresee this point being raised in the future as well.
And, then, the whole circle starts once more.

The decision is yours.

**Comment by oowekyala** [comment]
I'm not sure it would be sensible to map the LoC rules to NCSSCount. If the point is to educate developers about NCSS, then I think people must understand entirely what's NCSS, how it's different from LoC, and how it's still not perfect, then take a conscious decision to either
* upgrade to NCSS,
* not replace the rule,
* or reimplement their own LoC rule because that's really what they want (trivial in XPath).

Choosing the first option is not a no-brainer, because:
* properties of those rules are not named the same, which could cause crashes
* threshold values need to be updated manually, because LoC is typically much greater than NCSS for the same piece of code
* *both* rules suffer from a certain problem of noisiness (even though NCSS is better than LoC in some respects).
  * I'd expect many methods that are larger than average are so legitimately, but neither rule can know that (might depend on some semantic info, eg "logic can't be broken down", "this is acceptable because it's well commented", etc).
  Reporting a violation for those is at best noise in the report, at worst a complete roadblock, because a loosely configured ruleset may eg make a Maven build fail for what amounts to a false positive. That depends on rule priority and other configuration that's mostly in control of the user
  * This is not to say that either rule is useless. They can be useful to point out methods requiring review, but users need to be aware that they're quite noisy, and that they should configure them carefully

So I'm for deprecating the rules normally, and updating their description with why they're deprecated and how NCSS can be used as a replacement (and why it's not necessarily a great rule either).

Another question: should we do that for every language that has Excessive*Length rules apart from Java? I think NCSSCount is only implemented for Java.

**Comment by Fernal73** [comment]
@adangel The point about mobile phone access is not entirely off-topic. The wiki has to be either read off-line or cloned locally. There is no facility to generate ebooks, like Wikibooks, to be read off-line. That would make it more accessible.

**Comment by Fernal73** [comment]
These rules serve as flags to the user. They don't actually provide a clear-cut decision criteria, by themselves, whether to refactor or not. (A few lines more doesn't mean much.) Metrics  such as CyclomaticComplexity can help there.
Not aware of the other languages not having NCSSCount. You , obviously, keep them until you have NCSSCount.  Is there some implementation issue in other languages that I'm missing here? There's a separate component jar for JavaNCSS that can be run outside of PMD that provides the same functionality. I haven't tried it as yet, though.

**Comment by oowekyala** [comment]
> The point about mobile phone access is not entirely off-topic. The wiki has to be either read off-line or cloned locally.

Come on, it's obviously off-topic, this issue has nothing to do with wiki accessibility. Besides you can access the desktop version of the site on mobile, [regardless of your browser](https://user-images.githubusercontent.com/24524930/69495278-786d5a00-0ec5-11ea-9934-91bce80b47a5.png)

> You , obviously, keep them until you have NCSSCount.

Yeah I kind of agree, though there's no schedule to add NCSS support to other languages yet.

>  Is there some implementation issue in other languages that I'm missing here? 

No, it's not even complicated, someone just needs to pick it up.

> There's a separate component jar for JavaNCSS that can be run outside of PMD that provides the same functionality. I haven't tried it as yet, though.

NCSS is already implemented in pmd-java, I don't see why we would use JavaNCSS 

---

I think if we've reached a consensus about deprecating the rules, then for clarity this issue should be closed as `was:wont-fix`, and new issues about 1. deprecating LoC rules for Java and 2. implementing NCSS for other languages should be opened.

**Comment by Fernal73** [comment]
https://github.com/isaacs/github/issues

Raise Github issues here.

**Comment by Fernal73** [comment]
Where do I find a list of these labels and their  significance?

**Comment by oowekyala** [comment]
> Where do I find a list of these labels and their significance?

https://github.com/pmd/pmd/labels

> I think it's incumbent on projects to raise issues to Github that will help them function better. Are you telling me Github has no input from the projects it hosts? Or this issue is unimportant to you?

I'll just say that you should probably raise an issue to Github yourself, because I'm certainly not doing it.

I'm closing this.

**Comment by Fernal73** [comment]
Ok. And I'm not going to be raising the issues about NCSS for other languages and deprecating LOC rules. Good luck with that.

**Comment by Fernal73** [comment]
Another point: Why isn't a code of conduct instituted for PMD?
