### ISSUE TITLE
[maven] Classloader not being closed after PMD run

### ISSUE THREAD

**Issue by cwholmes** [pmd/pmd#2163]
**Affects PMD Version:** 
Unknown: Definitely 6.18.0+

**Rule:**

**Description:**
Classloader is being constructed in the configuration and then never closed.

https://github.com/pmd/pmd/blob/master/pmd-core/src/main/java/net/sourceforge/pmd/PMDConfiguration.java#L196

This classloader is then never closed and is being left to be close the open jar file references when finalized. This seems to be keeping open file references to jarfiles. (Also duplicating them across threads).

**Code Sample demonstrating the issue:**

Example of classloader that isn't closed:

[maven-pmd-plugin](https://github.com/apache/maven-pmd-plugin/blob/6c1f0a25d5af6a403b4e851c18caf5d084c4a3d9/src/main/java/org/apache/maven/plugins/pmd/PmdReport.java#L796)

**Running PMD through:** *[Maven]*

**Comment by adangel** [comment]
Inside PMD - meaning, when running PMD from commandline or via the provided ant task, there is no problem:
* For the ant task, we close it at the end: https://github.com/pmd/pmd/blob/d115ca59f73490c771abfe754414722512b4ac9b/pmd-core/src/main/java/net/sourceforge/pmd/ant/internal/PMDTaskImpl.java#L287
* For CLI invocations, we close it here: https://github.com/pmd/pmd/blob/d115ca59f73490c771abfe754414722512b4ac9b/pmd-core/src/main/java/net/sourceforge/pmd/PMD.java#L265

It seems, how the maven-pmd-plugin calls PMD, the classloader is **not** closed, though.

I'll keep this issue open, maybe we can improve the API, so that such situation is not even possible. The API caller shouldn't have to deal with that problem.

There might be a similar problem for the [https://github.com/pmd/pmd-eclipse-plugin](pmd-eclipse-plugin).

**Comment by adangel** [comment]
This is still open - we still use a classloader via PMDConfiguration, which needs to be closed.

This is not a problem, as long as PMD is used as described in https://pmd.github.io/latest/pmd_userdocs_tools_java_api.html.

But if PMD is used differently, or a PMDConfiguration is created without calling PmdAnalysis, then one might still run into this issue.

**Comment by jsotuyod** [comment]
@adangel so if I understand correctly, this lies 100% on the Maven plugin, that is tightly bound to PMD using it's internal APIs (part of the reason why the `pmd-compat6` module was needed); with nothing to do on this end.

Do you want to keep it here? or do you have a corresponding issue on the Maven plugin's JIRA?

**Comment by adangel** [comment]
The closing part has been fixed in m-pmd-p 3.14.0 already.
As #4949 / #4899 showed, the classloader is definitely closed in maven-pmd-plugin still today. So, there is no problem in this regard anymore.

The only thing left here is:

> I'll keep this issue open, maybe we can improve the API, so that such situation is not even possible. The API caller shouldn't have to deal with that problem.

That's an API problem: Whoever calls PMDConfiguration#prependAuxClasspath might create an Classloader, that might not be closed.

Right now, when calling PMD via PmdAnalysis, the classloader is closed when PmdAnalysis is closed. So, it should not be a problem anymore, if PmdAnalysis is closed.

However, I find it still surprising, that PMDConfiguration manages a classloader instead of a classpath... 

Two things, I'd suggest:

1. document in the API for [PMDConfiguration#prependAuxClasspath](https://docs.pmd-code.org/apidocs/pmd-core/7.0.0/net/sourceforge/pmd/PMDConfiguration.html#prependAuxClasspath(java.lang.String)) and the related methods (setClassloader, getClassloader) the implications of not properly closing the classloader.
2. deprecate setClassloader/getClassloader, refactor PMDConfiguration to deal with a list of strings (a "classpath") and create the classloader only later, fully internally and not exposing this classloader in any way.

**Comment by adangel** [comment]
Closing this one now in favor of #4952 and #4953.
