### ISSUE TITLE
[core] Allow XML dumps of ASTs

### ISSUE THREAD

**Issue by oowekyala** [pmd/pmd#2215]
> Checkstyle provides a command-line option that displays the AST tree for a single file. I know this can be done through the Rule Designer. Is there a possibility that PMD will allow for the AST tree to be output via the CLI? Better still, output the AST as an xml doc?

> I assume the Xpath works on elements specified in the grammar. It would be easier to work with an xml document that mimics the tree structure so that the Xpath can be tested independently and then integrated into rule changes, if needed. JavaParser allows for xml to be output for a Java source.

> We could add an "export to XML" option in the designer. We could even let this XML document be dumpable from the designer CLI, without starting the GUI. But I don't think the value added to adding this to the PMD CLI would justify the added complexity.

**Comment by Fernal73** [comment]
@oowekyala 

I seem to have missed that.

On further thought, it might be a good idea to provide an xsd or dtd for the generated XML file so that the user has an idea of all the elements and attributes in the tree. There are only two ways to list all elements and attributes: use the designer or surmised them from the JavaCc grammar. 
It might be possible to generate this every time the grammar is updated.

Also, is there any documentation that provides a list of the Xpath functions provided by PMD? I couldn't find any.

**Comment by oowekyala** [comment]
> On further thought, it might be a good idea to provide an xsd or dtd for the generated XML file so that the user has an idea of all the elements and attributes in the tree. There are only two ways to list all elements and attributes: use the designer or surmise them from the JavaCc grammar.
It might be possible to generate this every time the grammar is updated.

Yes this could be nice, I'll add it to our TODOs for 7.0. The mapping from Java to DOM is not yet documented but it's very regular. A node's name is the class name without the "AST" prefix. Its attributes are all getters with a name starting with "is", "get", or "has" and a return type that is primitive, string, or enum. Knowing this you can look at the javadocs and find out.

> Also, is there any documentation that provides a list of the Xpath functions provided by PMD? I couldn't find any.

This here: https://github.com/oowekyala/pmd/blob/docs-rules-newer/docs/_data/xpath_funs.yml
This is pending work I haven't finished.. 

> Furthermore, what version of Xpath is supported?

https://github.com/oowekyala/pmd/blob/docs-rules-newer/docs/pages/pmd/userdocs/extending/writing_xpath_rules.md

**Comment by Fernal73** [comment]
It'll be simpler to create an Xml doc such as the one you provided with all
the possible constructs of the Java language and generate an xsd for it.

The other option is to provide a list of elements and attributes manually.

Is this something the designer can do more easily?

https://stackoverflow.com/questions/74879/any-tools-to-generate-an-xsd-schema-from-an-xml-instance-document

**Comment by Fernal73** [comment]
@oowekyala 
Is both generating the xml and xsd file to be put off to release 7.0.0? If not, let's split this into two issues with one marked for an earlier release and the other for 7.0.0.

Also, I've noticed there are issues that have been edited and cetegorised, but no milestone has been assigned. What happens to these 'hanging' issues?

**Comment by Fernal73** [comment]
https://sourceforge.net/p/pmd/discussion/188194/thread/7ba34487/

An old link from SourceForge

**Comment by oowekyala** [comment]
> Is both generating the xml and xsd file to be put off to release 7.0.0? If not, let's split this into two issues with one marked for an earlier release and the other for 7.0.0.

Only the XSD. I  think generating it from the grammar will be simpler in the long run. Splitting the issue is a good idea

> Also, I've noticed there are issues that have been edited and categorised, but no milestone has been assigned. What happens to these 'hanging' issues?

They're waiting to be picked up.

> Is there a dictionary for the elements and attributes? 

-> The javadocs

>  I can't get my head around 'FindBoundary'.

This is only relevant for java rules. It shouldn't be an attribute. I'll open an issue about that.

>  I also can't understand why static="false" has to be present in a normal import declaration.

The attribute is true if the import is declared static, false otherwise. I don't see the problem

**Comment by Fernal73** [comment]
> 
> The attribute is true if the import is declared static, false otherwise. I don't see the problem

This makes xsd and the ability to specify default values for attributes relevant. Will this impact Xpath querying?

**Comment by adangel** [comment]
@Fernal73 I'm not sure, I understand this issue yet. Here's what I got from reading the discussion:

* It all started, that you wanted to write a xpath expression to be used as a violation xpath expression for a specific problem.
* So, the problem, we are tackling is: "Easy/Simply/Lightweight way to write and verify xpath expressions". Is this correct?
* One possible way to tackle this problem as discussed here: export the AST into a XML document and let a generic xpath processor evaluate the expression.
* Another possible way (which was immediately discarded): Improve the [pmd-designer](https://github.com/pmd/pmd-designer). Why was this discarded? IMHO, we should improve the designer to help developing xpath expressions for violation suppression (currently the designer focuses on developing xpath expressions for rules).
* Are there any other ways?
* I'm telling this, because I'm afraid, we add a "solution", but it doesn't solve your problem...

Looking at the solution: Dumping XML for the AST
* I see it useful for documentation purposes. It might be more lightweight than taking a screenshot of the AST. In the past, I sometimes used the DumpFacade for this, but nowadays, I usually just start the designer, to have a look at the AST
* It can be used to illustrate how simple XPath-based PMD rules work (so, again: documentation)
* I'm not sure, how useful this XML dump would be to actually develop/execute PMD rules: You need to use PMD in order to use PMD-specific functions like `pmd-java:typeIs`. Which means, it would be very limited.
* It might be useful however for something completely different, I don't have in mind. We would basically expose the AST as a different API, ship it and see if someone finds a use-case. This however means, we provide a solution for a unknown problem...
* In summary: I'm not against this feature. But I'm not convinced, that it solves your problem.

> What custom Xpath functions are you referring to? Can't these be exported or made available?

There are functions for typeresolution, metrics, and comments. typeresolution and metrics can't be easily made available, since they take an argument - so, they need to evaluated at runtime. We can't execute them before with all possible inputs.


>>  All-in-all the designer is the best way to run XPath queries on an AST and be sure they come out
>> exactly the same when run by PMD. Also it allows using our custom XPath functions, like those to 
>> query the type of a Java node.
> No, it's not since it's not easily accessible except through the UI unless you're looking to tie users 
> exclusively to the designer. A system lock-in, if you may.

I don't understand, why you don't seem to want to use a UI for developing? Are you not using a IDE?
About system lock-in: IMHO the problem we are solving is to develop XPath based rules or xpath expressions for violation suppressing. Therefore it doesn't matter, whether it's UI or not: the developed xpath expression is created to be executed by PMD, then why not use a UI for PMD? The system lock-in is to PMD and not to the UI: the rules you develop to analyze your code can only be executed by PMD (unless someone adds a way to execute PMD rulesets in their product). The AST PMD produces is also PMD specific (hence "PMD DOM").

**Comment by adangel** [comment]
I found one possible use case for XML dumps: We could use it to verify, we don't make breaking changes in the AST APIs. A simple tool could create dumps from some reference source files and compare them with the expected XML documents. That way, we would see, if we break any AST API user, if we accidentally change something....

**Comment by Fernal73** [comment]
Wrt SLI, my concern is that users can't use Xpath expressions without PMD. That's understandable if they're intent on utilising the custom Xpath functions provided. That's what customization implies. A lock-in to the custom provider. 
This also implies that PMD is dependent on Jaxen and its implementation. Switching to another Xpath processor will not be easy should PMD need to.

**Comment by Fernal73** [comment]
I'll look at the rest of your response later.

**Comment by oowekyala** [comment]
> Wrt SLI, my concern is that users can't use Xpath expressions without PMD.

PMD is not a general purpose XPath engine. Its purpose is also not to turn an AST into XML. Why would you even expect that the XPath expressions we accept can be used without PMD? What would you do with such an XPath expression?

> This also implies that PMD is dependent on Jaxen and its implementation. Switching to another Xpath processor will not be easy should PMD need to.

In fact we're deprecating Jaxen support and will move to Saxon for good in the next major release. But why would that matter to you, that we use that library to run XPath?

**Comment by Fernal73** [comment]
It doesn't matter to me, personally.
It should matter to PMD, though , and evidently it does. Saxon is the more
well-known Xpath engine and is well-supported too. Moving to Saxon
mitigates an architectural risk that Jaxen might become obsolete that the
system is dependent on.
I had not heard of Jaxen until PMD bit then , what do I know?

**Comment by oowekyala** [comment]
> All I'm saying is that I'd like to use the same Xpath outside of PMD in a
more lightweight fashion.

*What* *for*? Our XPath expressions don't exist in a vaccuum, they're meant to be PMD rules. Why would you require that an XPath expression match the same results as PMD would if you're not using PMD afterwards? What do you mean by *lightweight*? In what way is PMD not lightweight enough here?

> It should matter to PMD, though , and evidently it does. 

It does, but honestly these are things that you shouldn't concern yourself with. As far as users are concerned it shouldn't matter whether we use Jaxen, Saxon, or an in-house engine as a backend, provided the implementation matches the spec. You should view PMD as the XPath engine itself, a black box.

**Comment by Fernal73** [comment]
I don't see how you can stop anybody checking out an Open-Source project.
So whether you like it or not, you will find people checking up on PMD.
Isn't that what Open-Source projects are about, anyway?
You should be more concerned with achieving the best result possible.

As far as users are concerned, it shouldn't matter as long as you keep
supporting their XPath rules.
How you do it is up to you as long as it's usable and usability is
critical. If it's not easily usable, it will not be used. Period. It
doesn't matter if there's rocket fuel under the hood.

I don't have a use-case for exporting the Xml other than the above. It does
not mean that there will be none. Not everything can be foreseen with 20-20
vision.




-- 
Thanks,
Linus Fernandes.

**Comment by oowekyala** [comment]
> I don't see how you can stop anybody checking out an Open-Source project.
So whether you like it or not, you will find people checking up on PMD.
> You should be more concerned with achieving the best result possible.

No problem with that. But this whole debate feels like a waste of time. You're asking for a feature to be implemented, without being able to describe a use case, or why what currently exists is not appropriate. You're finding problems where there are none. Of course we care about supporting existing XPath rules. Of course we care about using up to date libraries. The problem is not that you're giving your advice, it's that you're out of your depth and behave as if we don't know what we're doing.


> Wrt SLI, my concern is that users can't use Xpath expressions without PMD.

I think you misunderstand why we use XPath. XPath expressions are a simpler way to express a Java rule, but people are just as dependent on the AST structure with XPath rules as with Java ones, and this is *expected*. If you were writing a Java rule you would be expecting to depend on pmd's runtime library to even classload, and you wouldn't be describing PMD as "locking you in" to its API. It's the same thing with XPath. Our XPath API is not meant as a tool-independent format you can reuse in an external XPath client, it's just not the point.

Dumping trees to XML has some use cases but not the one you so elusively describe

**Comment by Fernal73** [comment]
I asked if it's possible for the AST to be output as Xml. I'd find it
useful to look at to understand the tree structure rather than have to look
at PMD's javacc grammar. And figure it out from there. Xml is something
people are more familiar with. So it helps to understand the AST with it.
(I've already said all this and I don't like repeating myself).

As for being out of my depth, that's subjective. Yes, I haven't been
techological in a long time. I make no bones about it.

As for you suggesting that I'm implying that you don't know what you're
doing, that's your conclusion, not mine.

If you had said 'No', I would have done it myself for my own purposes, just
not with PMD's grammar or API instead.

You have not given me any uses for the Xml output yourself.

**Comment by Fernal73** [comment]
As for Xpath not being the only way to create PMD rules, yes, I'm aware of
that, too.

**Comment by adangel** [comment]
FYI - a simple cli utility will be included with 6.21.0. Here's the doc preview with usage example: https://pmd.sourceforge.io/snapshot/pmd_devdocs_experimental_ast_dump.html
