### ISSUE TITLE
[java] Ignore Return Statement after Control Statement

### ISSUE THREAD

**Issue by numeralnathan** [pmd/pmd#2221]
**Affects PMD Version:** 

6.20.0

**Rule:**

ControlStatementBraces

**Description:**

Please add an option to ignore return statements after a control statement.  In the sample code below, I would like to configure ControlStatementBraces to not flag the return statement.

**Code Sample demonstrating the issue:**

```
if (viewer == null)
   return;   // ControlStatementBraces flags a problem
```

**Comment by numeralnathan** [comment]
Please add an option to ignore `continue` statements after a control statement. In the sample code below, I would like to configure ControlStatementBraces to not flag the `continue` statement.

Code Sample demonstrating the issue:

```
if (!(value instanceof JoinLink))
   continue;   // ControlStatementBraces flags a problem
```

**Comment by numeralnathan** [comment]
Please add an option to ignore `throw` statements after a control statement. In the sample code below, I would like to configure ControlStatementBraces to not flag the `throw` statement.

Code Sample demonstrating the issue:

```
if (row == null)
   throw new IllegalStateException("row is null");  // ControlStatementBraces flags a problem
```

**Comment by numeralnathan** [comment]
Please add an option to ignore `break` statements after a control statement. In the sample code below, I would like to configure ControlStatementBraces to not flag the `break` statement.

Code Sample demonstrating the issue:

```
if (isValid(connection))
   break;
```

**Comment by oowekyala** [comment]
I think these are instances that the rule is supposed to flag. I'd suggest suppressing the violation with an xpath query, eg `IfStatement/Statement/*[self::BreakStatement or self::ThrowStatement or self::ReturnStatement or self::ContinueStatement]`.

**Comment by Fernal73** [comment]
@oowekyala No, not really.
If and when this happens to be a common enough occurrence, i.e., it is the style used by a majority of developers, then it ought to be a configurable option provided by PMD's default implementation. The Xpath suppresion can be used if and when the OP cannot wait for the issue to be implemented as requested.

**Comment by numeralnathan** [comment]
@oowekyala Thank for the XPath query.  I will use this until PMD provides the configurable options.

**Comment by oowekyala** [comment]
> If and when this happens to be a common enough occurrence, i.e., it is the style used by a majority of developers, then it ought to be a configurable option provided by PMD's default implementation

Indeed, this is how we choose to include configuration options. Is this really a common enough occurrence though?

This is the first time I've heard of a convention for braces that makes a special case for control statements. 

* Google: https://google.github.io/styleguide/javaguide.html#s4.1.1-braces-always-used
  > Braces are used with if, else, for, do and while statements, even when the body is empty or contains only a single statement.
* Sun: https://www.oracle.com/technetwork/java/javase/documentation/codeconventions-142311.html
  > Braces are used around all statements, even single statements, when they are part of a control structure, such as an if-else or for statement. 
* Intellij coding conventions also [mandate braces](https://github.com/JetBrains/intellij-community/blob/master/.idea/codeStyleSettings.xml#L151-L154), though they mention [elsewhere](https://www.jetbrains.org/intellij/sdk/docs/basics/intellij_coding_guidelines.html#Code%20formatting) that they're lax about it
* OpenJDK: https://cr.openjdk.java.net/~alundblad/styleguide/index-v6.html#toc-braces
  > Braces are recommended even where the language makes them optional, such as single-line if and loop bodies.
* The [Eclipse coding conventions](https://wiki.eclipse.org/Coding_Conventions) has this interesting passage:
  > . All code written for the Eclipse Platform should follow these [the Oracle] conventions except as noted below. We deviate only in places where our needs differ from Oracle's; **when we do deviate, we explain why.** 
* This source mandates single-statement blocks to be without braces, but makes no exception for control statements: https://www.mindprod.com/jgloss/codingconventions.html
  > Put single line if and else clauses without {} on the same line. This is one place where the Immuexa conventions override rather than augment Oracle’s.

None of those make an exception for some control statements.

Our rule is already one of the most configurable brace check tool available. Checkstyle has the option to [allow single line statements](https://checkstyle.org/config_blocks.html#NeedBraces), which is equivalent to disabling our rule, and otherwise the same options as us. I know of no IDE that makes an exception for these cases, AFAIK they also have the same options as us (force braces selectively depending on the type of control statement). I think if there ever was sufficient demand for such a feature, some IDE company would have implemented it, given that's how they make a living.

Besides the fact that there is no clear demand or justification for this feature, I think implementing it would open the door to a lot of complexity, and pushback from some developers. Some might just prefer to whitelist `continue` & `break` but not `return`, others might want to whitelist more kinds of control statements, eg `if`, `try` or loops. Others might even want to allow this not only under an `if` but also in loops. What about `else`? What about an `if .. else` where the `else` has braces but not the `if`? 

Is there a set of configuration options that can satisfy everyone? Would it instead be enough for PMD to stick with widely accepted conventions and let users customize the rule if it doesn't fit? This is what suppression does here, it's not really correcting a bug in PMD, it's allowing a user to tailor a check to their preference. Nothing negative about it. 

So honestly I don't think this is something PMD has good reason to include, and suppressing the rule for the cases you want should be enough.

**Comment by Fernal73** [comment]
IMO, something like this would either fall under formatting options and/or auto-correction. As for how many developers would prefer it (and since it's not that big a deal), most will take what's offered to them by tools rather than written coding standards. In fact, that's how standards come about. 

https://github.com/checkstyle/checkstyle/issues/7427

**Comment by oowekyala** [comment]
> most will take what's offered to them by tools rather than written coding standards.

This doesn't justify that tools should deviate from written coding standards. Quoting the same Eclipse doc again:

> when we do deviate, we explain why

This thread doesn't mention a single reason why deviating from the convention would be a good idea. OTOH there are many arguments for sticking to the convention, one of the main ones being that since it's conventional since the birth of Java, so many tools support it very well.

> and since it's not that big a deal

This is a bold assumption.

**Comment by Fernal73** [comment]
It isn't that big a deal or else you'd have a stampede on this post arguing
for the rule. Do you?

**Comment by tweimer** [comment]
> I know of no IDE that makes an exception for these cases, AFAIK they also have the same options as us (force braces selectively depending on the type of control statement). I think if there ever was sufficient demand for such a feature, some IDE company would have implemented it, given that's how they make a living.

While I also don't think it is worth adding it, I would like to add that eclipse has indded such option (Java > Code Style > Cleanup)

![image](https://user-images.githubusercontent.com/2698843/74109688-cbca7c80-4b85-11ea-9ccb-0adf8e7cbafc.png)
