### ISSUE TITLE
[doc] Update doc on communication channels

### ISSUE THREAD

**Issue by oowekyala** [pmd/pmd#2249]
See https://pmd.github.io/#support

* This links to the sourceforge forum -> link to gitter instead?
* This info should be present on the README too

I think [this format](https://meta.stackexchange.com/a/3974/334230) is helpful:
> Where-to-post summary:
> * How do I? -- StackOverflow!
> *    I got this error, why? -- StackOverflow!
> *   I got this error and I'm sure it's a bug -- file an issue!
> *  I have an idea/request -- file an issue!
> *   Why do you? -- the mailing list!
> *  When will you? -- the mailing list!
> *  You suck and I hate you -- contact us privately at me@glennbeck.com!
> *  You're awesome -- aw shucks!

We should clarify what we expect from Gitter/Sourceforge/Stackoverflow 

Refs #2238

**Comment by Fernal73** [comment]
So we're still continuing with SourceForge?
How do users subscribe to all these messages?
https://sourceforge.net/p/pmd/discussion/

**Comment by adangel** [comment]
> So we're still continuing with SourceForge?

Maybe - why not?

> How do users subscribe to all these messages?

https://sourceforge.net/user/registration

> https://sourceforge.net/p/pmd/discussion/

After you are logged in, you can subscribe and you also get email notifications.

**Comment by adangel** [comment]
@oowekyala  One other thought: Would it make sense to add github issue templates, like you did for the designer? We could provide the following templates:
* Bug - crash etc. - you should have a stacktrace
* Rule violation false/positive - a code sample is required
* Rule suggestion - should ask for a code example, suggestion for the category
* Question - anything else

That way, the users wouldn't need to switch to other sites and everything would be on github...

**Comment by jsotuyod** [comment]
@adangel 👍 I didn't even know github now allows more than one template, it's an awesome idea!

**Comment by oowekyala** [comment]
Issue templates are a good idea!

**Comment by adangel** [comment]
I noticed today a different way of dealing with user questions on spotbugs: they use the issue tracker of a dedicated repository for this: https://github.com/spotbugs/discuss
Is that maybe something we want to do as well? It would have the advantage, that we stay on the same platform (as opposed to route the users to sourceforge or another platform) and we would have questions separated from issues.

**Comment by Fernal73** [comment]
Consolidated and concentrated...makes sense....

**Comment by oowekyala** [comment]
So, if I understand correctly, we'd use a separate issue tracker (in a new repo) for general questions about PMD, and continue using this repo for bug reports? This sounds like a good idea, but I'm not sure where we'd draw the line exactly. Eg, where would feature requests belong? 

Wouldn't it be easier to just use this issue tracker for everything, and just use the [`a:question`](https://github.com/pmd/pmd/labels/a%3Aquestion) label to split questions from issues? (ie just keep doing what we're doing). I think this lowers the maintenance effort tbh

Alternatively, we could have a separate repo for all issues, and close this issue tracker altogether. This is what eg [scala/bug](https://github.com/scala/bug) does. This may scale better when there are a ton of issues, that concern multiple repos, but the maintenance effort is still a bit higher (it's less easy to reference issues from another repo)

**Comment by pzygielo** [comment]
> a separate repo for all issues

However such solution has some cons IMO, for example linking to source code that is inlined by GH for the-same-repo reference, like https://github.com/pmd/pmd/blob/d115ca59f73490c771abfe754414722512b4ac9b/Gemfile#L9-L10 will not work in separate repo. Example for the pmd org but different repo: https://github.com/pmd/pmd-designer/blob/4ac4ddab997cf93442f18980f4e9d2c48e9bbbf4/pom.xml#L6-L7.

And probably more, that I can't think of now.

**Comment by Fernal73** [comment]
Is there a way to have a tag cloud for the labels so that users can directly navigate to all such tagged issues? 

How about a super-repo with all the other repos as sub-repositories? This should allow linking to source code in every sub-repo? Am I mistaken?

Or we could not care and let this new repo not have access to source? That wouldn't be quite different from a Google group.  Why should this forum need to address source code issues? It's for users to ask queries about the issues they're facing while using PMD.

**Comment by adangel** [comment]
> Is there a way to have a tag cloud for the labels so that users can directly navigate to all such tagged issues?

There is indeed: https://github.com/pmd/pmd/labels - well, not exactly a cloud, but ... at least you can see all questions: https://github.com/pmd/pmd/labels/a%3Aquestion

> How about a super-repo with all the other repos as sub-repositories? This should allow linking to source code in every sub-repo? Am I mistaken?

Do you mean something like git submodules? Not sure if that would work. Submodules will need to be handled specially when updating your local clone (e.g. it is not a simple git pull anymore....). That might create more problems than it solves.

> 
> Or we could not care and let this new repo not have access to source. That wouldn't be quite different from a Google group. Why should this forum need to address source code issues? It's for users to ask queries about the issues they're facing while using PMD.

That's a good point: The questions are a general discussion forum, it just happens that we "misuse" the issue tracker as a forum (in case we go that route...).

I think, we have an agreement for the issue templates.

The remaining question is: where do we point users to, when they have a question? Currently, we tell them: go to stackoverflow, or go to the forum on sourceforge or go to the mailing list.
The forum on sourceforge and mailing list are rarely used, so we should probably not point them there (the chances to get an answer are higher anywhere else).

I believe, pointing them to stackoverflow still makes sense (since there are more developers active).
I would also say, gitter (https://gitter.im/pmd/pmd) makes sense to have it included in the list.

And I'd suggest, for starters, we just use the main repo for now with the label "question" (this is - as @oowekyala  pointed out - what we already do) and explicitly mention this on the support section (https://pmd.github.io/#support / https://github.com/pmd/pmd.github.io/blob/master/_includes/support.html), so that users know, that they can also create an issue for just a question.
In case, we see, that this is used more often (IMHO we are talking here about theoretical problems...), we can always decide later on to move the questions to a separate repository.

What do you think?
Pull-Requests are welcome :smile:

**Comment by Fernal73** [comment]
A label cloud would have been nice.

Could one be generated and added to the readme.md and the website with the
links as in the labels page?

The labels page is not user-friendly.

(Another feature request for GitHub).

Yes, I meant submodules.

Yes, I'm aware that submodules are difficult to set up and need to be
continually updated to remain in sync. An automated script will be needed
if you choose to go down that route.
