### ISSUE TITLE
[java] Write all rules as XPath queries

### ISSUE THREAD

**Issue by numeralnathan** [pmd/pmd#2270]
**Affects PMD Version:** 

6.21.0

**Description:**

I recommend converting all rules over to XPath queries.  This will ensure that XPath queries can express the entire power of PMD rules.  If an XPath query cannot implement a PMD rule, then the gap will show how XPath queries need to be enhanced.

Furthermore, implementing all rules as XPath queries will allow for easy customization of the rules.  For example, I do not like that the `UselessParentheses` rule flags a particular code construct (e.g. `((a > 5) && (b < 3))`).  Since `UselessParentheses` rule is implemented as a XPath query, I copied the XPath query into a custom rule and removed the parts of the XPath that I do not like.

This may be a pre-mature optimization concern; however, it might make sense to automate converting the XPath queries into Java code.  The Java code can then be compiled and the rules will hopefully run faster.  To show how much this optimization will impact performance, you could manually implement a rule with XPath query and Java code and then measure the performance difference.

**Comment by oowekyala** [comment]
>  This will ensure that XPath queries can express the entire power of PMD rules.

I agree with the general motive, but XPath as a language also has very clear limitations. Sometimes Java is the best tool for the implementation. So, I don't think implementing all rules in XPath is a reasonable way for us to achieve the goal you state (make the XPath API as powerful as the Java one). Maybe for starters, people could request additions to the XPath API when they think something is missing. I mean they obviously already can do so, but we don't get such requests often, if ever

Also I don't think the use case you describe with UselessParentheses is something we should support. This is typically a case where, whether the rule is implemented in Java or XPath, you could use an XPath expression to suppress the violations you don't like. Otherwise what you're doing is equivalent to implementing a rule that's completely unrelated to our UselessParentheses, which means you don't benefit from updates we make (improvements, bug fixes). Nothing wrong with that per se, I just don't think this is how PMD should work. PMD has a rule library for the languages it supports. The goal of any library is code reuse, and not through copy-paste.

**Comment by numeralnathan** [comment]
@oowekyala You make an interesting point.  Instead of writing my own rule, use XPath to suppress the violations I do not like.  How do I do that?  Is there some documentation on this?

**Comment by oowekyala** [comment]
https://pmd.github.io/latest/pmd_userdocs_suppressing_warnings.html#the-property-violationsuppressxpath

**Comment by Fernal73** [comment]
> > This will ensure that XPath queries can express the entire power of PMD rules.
> 
> I agree with the general motive, but XPath as a language also has very clear limitations. Sometimes Java is the best tool for the implementation. So, I don't think implementing all rules in XPath is a reasonable way for us to achieve the goal you state (make the XPath API as powerful as the Java one). Maybe for starters, people could request additions to the XPath API when they think something is missing. I mean they obviously already can do so, but we don't get such requests often, if ever
> 
> Also I don't think the use case you describe with UselessParentheses is something we should support. This is typically a case where, whether the rule is implemented in Java or XPath, you could use an XPath expression to suppress the violations you don't like. Otherwise what you're doing is equivalent to implementing a rule that's completely unrelated to our UselessParentheses, which means you don't benefit from updates we make (improvements, bug fixes). Nothing wrong with that per se, I just don't think this is how PMD should work. PMD has a rule library for the languages it supports. The goal of any library is code reuse, and not through copy-paste.

Any rule that's implemented in Java must be given careful thought and attention as to whether it can be made as configurable as possible. Xpath rules can be easily modified by users familiar with the Xpath syntax and API. Not so much for Java implementations and that's a concern since users will have to wait much longer for a fix or improvement.

**Comment by oowekyala** [comment]
>  Any rule that's implemented in Java must be given careful thought and attention as to whether it can be made as configurable as possible. Xpath rules can be easily modified by users familiar with the Xpath syntax and API. Not so much for Java implementations and that's a concern since users will have to wait much longer for a fix or improvement.

The same care about configurability should be given to XPath rules.

For all intents and purposes whether a rule is implemented via XPath or not should be opaque to a user, otherwise we'll have compatibility problems when converting a rule to use one implementation or the other. XPath expressions are exposed as documentation, but the API they provide is identical to that of a Java rule: properties.

I don't think writing all rules as XPath queries is something we should reach for, so I'm going to close this issue.

**Comment by Fernal73** [comment]
> 
> The same care about configurability should be given to XPath rules.

Agreed. That's a given. Did I forget to mention it?
> 
> For all intents and purposes whether a rule is implemented via XPath or not should be opaque to a user.

The documentation currently exposes the implementation and that's perfectly all right. It makes it easier for a savvy user to decide whether they can try their hand at updating it or changing it and that's all right as well.
