### ISSUE TITLE
Classpath in ruleset XML file for custom rules written in Java

### ISSUE THREAD

**Issue by numeralnathan** [pmd/pmd#2291]
**Affects PMD Version:** 

6.21.0

**Rule:**

Any custom rule implemented with a Java class

**Description:**

I created a custom rule with a Java class.  I added the `<rule>` tag into the PMD ruleset XML file.  PMD (and PMD Eclipse plugin) are unable to find the Java class.  I opened `pmd.bat` and added the Java class to `java`'s `-classpath` argument.  The PMD CLI now works but the PMD Eclipse plugin cannot find the class.

Editing `pmd.bat` is cumbersome.  Every time I upgrade PMD, I have to edit this file.  If I have multiple projects with different custom rules then the `-classpath` argument will require a path to each of the different projects.  Furthermore, plugins that run PMD (e.g. PMD Eclipse plugin) also have to be configured to find the custom rules.

I propose that the ruleset file (XML file) allows for specifying the classpaths where to find the custom rules.  This way each project can specify its own.

Is there a better way to specify the classpath?

**Running PMD through:** CLI and Eclipse

**Comment by adangel** [comment]
You can bundle your custom classpath into a custom PMD distribution. An example can be found here: https://github.com/pmd/pmd-examples/tree/java

For the eclipse plugin, this is a bit more complicated. The approach here is, to create a [fragment-plugin](https://wiki.eclipse.org/FAQ_What_is_a_plug-in_fragment%3F), which is able to extend the classpath of the main PMD plugin. The fragment uses the extension points to register custom rules and might provide its own libraries to enrich the classpath.

I have no real/ready to use example, but we have a test-fragment in the code, which uses the extension points of the pmd-eclipse-plugin:
https://github.com/pmd/pmd-eclipse-plugin/tree/master/net.sourceforge.pmd.eclipse.plugin.test.fragment

> I propose that the ruleset file (XML file) allows for specifying the classpaths where to find the custom rules. This way each project can specify its own.

That's an interesting idea. However, ideally the ruleset is already loaded via the some classpath (and not from a file) - so that the ruleset + the rule implementations are always together on the same classpath... (avoids problems when mixing different versions...). 

For maven builds, this is easily achieved by adding an additional jar to the plugin's classpath. The jar is created via the pmd-examples project, and the doc for extending maven-pmd-plugin is this: https://maven.apache.org/plugins/maven-pmd-plugin/examples/multi-module-config.html (via "build-tools").

Ideally, the pmd-eclipse-plugin would have a lightweight extension point that can be used - instead of creating a fragment and installing it.

**Comment by adangel** [comment]
Refs: https://github.com/pmd/pmd-eclipse-plugin/issues/117
