### ISSUE TITLE
[c#] CPD suppression with comments doesn't work

### ISSUE THREAD

**Issue by jsotuyod** [pmd/pmd#2551]
https://pmd.github.io/pmd-6.24.0/pmd_userdocs_cpd.html#suppression

The docs state:

> Arbitrary blocks of code can be ignored through comments on Java, C/C++, Dart, Go, Javascript, Kotlin, Lua, Matlab, Objective-C, PL/SQL, Python and Swift by including the keywords CPD-OFF and CPD-ON.

But C# is also supported. See #2550 

Double checking for any other missing languages would be nice.

**Comment by prashanthr84** [comment]
Doesn't look like the suppression works for C# in the latest release.

I tried with the following code

public void Method1()
        {
            // CPD-OFF

            int x = 1 + 2;
            Console.WriteLine(x);
            Console.WriteLine(x);
            Console.WriteLine(x);
            Console.WriteLine(x);
            Console.WriteLine(x);

            // CPD-ON
        }
But the cli as well as the windows form app shows that the duplicate is present. I set the minimum-tokens to 5. 
Not sure whether it is right or not?

**Comment by jsotuyod** [comment]
True… as discussed on Gitter.

C# uses an Antlr4 grammar, fully backed by an `AntlrTokenFilter`, but, the grammar itself is using an ad-hoc channel for comments:

https://github.com/pmd/pmd/blob/bc4a1d67eb091eeebcad26983eeeafbc68aa2698/pmd-cs/src/main/antlr4/net/sourceforge/pmd/lang/cs/antlr4/CSharpLexer.g4#L21-L24

and the `AntlrToken` is only considering the default and hidden channels:

https://github.com/pmd/pmd/blob/bc4a1d67eb091eeebcad26983eeeafbc68aa2698/pmd-core/src/main/java/net/sourceforge/pmd/cpd/token/AntlrToken.java#L79-L85

There are 2 possible solutions here…

1. change the grammar to use the `HIDDEN` channel (not sure it would be wise, grammars are usually taken as-is from Antlr's grammars repository, and this is not the only usage of other channels).
2. change `AntlrToken` to treat all non-default channels as hidden (which is sane, as the parser actually ignores everything that is not on the channel being currently processed, which unless explicitly told so, is only the default channel)

I'd personally go for 2, by changing `AntlrToken.isHidden()` to.

```java
    public boolean isHidden() {
        return !isDefault();
    }
```

**Comment by adangel** [comment]
I'd also use solution 2. Otherwise we would need to check all other grammars, which channel they use...

Here's a pointer to a simple unit test (note, that's java):
https://github.com/pmd/pmd/blob/bc4a1d67eb091eeebcad26983eeeafbc68aa2698/pmd-java/src/test/java/net/sourceforge/pmd/cpd/JavaTokensTokenizerTest.java#L115-L129

The test should be added here for C#: https://github.com/pmd/pmd/blob/master/pmd-cs/src/test/java/net/sourceforge/pmd/cpd/CsTokenizerTest.java

If you wrap the whole code into `//CPD-OFF` and `//CPD-ON`, then you should get back only one token, which is the EOF (end-of-file) token.
