### ISSUE TITLE
[java] Java 13 code analysis in case of Java 13 Preview feature is used in code

### ISSUE THREAD

**Issue by niranjanh** [pmd/pmd#2562]
[Java-13]  [pmd-6.24.0]

**Affects PMD Version:** 
6.24.0

**Description:**

I did not enable the preview features for java 13 by env variables `PMD_JAVA_OPTS`.

But when I run code analysis on code which has a preview feature let us say text block, then it doesn't return any issues.

However, if the same code and I comment out the text block code part, then it does return the issues.

**Comment by jsotuyod** [comment]
@niranjanh let me check if I understand correctly…

You are not enabling preview features, possibly using the default language version for Java analysis.


When you remove the usage of preview features, PMD correctly reports violations on that file.
When you parse code that uses preview features (invalid for the PMD settings) it shows no violations.

**Comment by adangel** [comment]
You'll need to configure at least the java version to be used for parsing (as @jsotuyod explained).
By default, PMD uses java14 without any preview features, which means, it fails to parse any preview feature.

See https://pmd.github.io/latest/pmd_userdocs_cli_reference.html#supported-languages

You'd need this cli argument: `-language java -version 13-preview`.

But even then, you might not get accurate results or get other errors - if you actually compiled your code (which you should - using auxclasspath). PMD uses the compiled code to understand your code (aka type resolution). In order to compile your code with javac, you need to enable preview, otherwise javac won't parse your code either.
I think, you need to decide whether to use preview features or not - there is no valid/supported/useful configuration "in between".

**Comment by niranjanh** [comment]
Okay.

Thanks for the feedback.

I am closing this issue.
