### ISSUE TITLE
[cpd] Error Loading stylesheet cpdhtml.xslt

### ISSUE THREAD

**Issue by cosmoJFH** [pmd/pmd#2637]
**Error Loading stylesheet cpdhtml.xslt**

We have recently migrated to the 6.25 pmd and we have also updated the latest version of the style sheet /pmd-src-6.25.0/pmd-core/etc/xslt/cpdhtml.xslt used in the cpd.

We execute the cpd by an ant target that includes the following tag:

``<xslt in="${report}/cpd/report.xml" style="${sofcommon}/${mpdVersion}/etc/xslt/cpdhtml.xslt" out="${report}/cpd/report.html"/>``

The problem is that now we get the following error message:

cpd:
      [cpd] Starting run, minimumTokenCount is 100
      [cpd] Tokenizing files
      [cpd] Starting to analyze code
      [cpd] Done analyzing code; that took 24 milliseconds
      [cpd] Generating report
     [xslt] Processing /scratch/workspace/gaia.Decoder/reports/cpd/report.xml to /scratch/workspace/gaia.Decoder/reports/cpd/report.html
     [xslt] Loading stylesheet /scratch/workspace/common/pmd-bin-6.25.0/etc/xslt/cpdhtml.xslt
  **[xslt] : Error! line 4: Illegal attribute 'xpath-default-namespace'.**

We are using openjdk version "11.0.5"

It looks like the error is related to the attribue _xpath-default-namespace_ that is valid for xslt 2.0.  The default namespace is not used for XPath 1.0 expressions.

I wonder if we should update any library in our system in order to property execute this style sheet.

We have locally fixed this issue removing the previous attribute, but we have checked that it is present in all the xslt files defined in pmd, and we are not sure whether this issue could affect the execution of other tasks.

**Comment by adangel** [comment]
That's strange. I don't remember, that we changed this stylesheet for a while....https://github.com/pmd/pmd/blob/master/pmd-core/etc/xslt/cpdhtml.xslt

I guess, you are simply using the ant task xslt for this, like

```xml
<xslt in="cpd.xml" style="etc/xslt/cpdhtml.xslt" out="cpd.html" />
```

So maybe, you need to update ant? This is a XSLT 2.0 feature (https://www.w3.org/TR/xslt20/#unprefixed-qnames)

Which version of PMD did you use before 6.25.0?

But looking at the history, this attribute was introduced via #1168 and #1169. Looking at the CPD XML renderer, I don't see, that we use a namespace here - and the namespace given in the attribute is actually the PMD xml format -- and not CPD...

So, even if you used a XSLT processor that supports this, the stylesheet is probably broken: So right now, I would actually consider this as a bug, since the generated XML report for CPD (e.g. https://pmd.github.io/latest/pmd_userdocs_cpd_report_formats.html#xml) does *not* contain a namespace.

**Comment by cosmoJFH** [comment]
Thank you for your quick answer.

Our previous version was 6.3.

And yes we are making use of an ant target similar to the one you pointed out.

**Comment by adangel** [comment]
> Our previous version was 6.3.

Ok, that explains it. The change/bug was introduced in 6.5...

I'll change this issue to a bug, thanks for reporting!

The attribute "xpath-default-namespace" is definitively wrong for this stylesheet. For CPD XML reports, we don't use namespaces.

**Comment by adangel** [comment]
Note, while the error "[xslt] : Error! line 4: Illegal attribute 'xpath-default-namespace'." is printed, the transformation is still executed successfully. However, if the xslt processor would understand this attribute, the result would be wrong (because we don't use namespaces here).
