### ISSUE TITLE
[core] Analysis cache classpath checksum should check ABI and not jar binary blob

### ISSUE THREAD

**Issue by jsotuyod** [pmd/pmd#2704]
The current implementation hashes the complete jars in the classpath in order

https://github.com/pmd/pmd/blob/b01dc8371b72a655a2b517b1050136b5ecd1a774/pmd-core/src/main/java/net/sourceforge/pmd/cache/AbstractAnalysisCache.java#L216-L233

However, this could be further improved.

We do care about jar order in the classpath, and we do care about the contents of each class in the JAR. However, the jar itself is a zip, and as such contains not only the contents of the class files, but also metadata. In particular:

1. The order of the entries (class files) within the jar may differ, but as each file name is unique this change on it's own means nothing.
2. The timestamp for each file entry may differ, but once again, this change on it's own means nothing.
3. Non-java classes resources and entries may be present (`META-INF`, properties files, etc.), that have no impact on the ABI

Furthermore, as for type resolution analysis, we only care about the ABI, not the implementation… so a further refinement would be to simply check for exposed symbols and signatures. There is a trade-off however between potential saves due to cache vs effort needed to fingerprint the classpath. Multiple level hashes could be used in an optimistic approach (ie: first try complete binary match for each jar, in case of differences, look deeper to see if it's avoidable).

Looking more deeply into the jars may therefore avoid cache invalidations.

**Comment by oowekyala** [comment]
Yes especially since,
1. we require an up-to-date classpath for analysed sources
2. any change to the classpath invalidates the cache

So if I edit 2 files, recompile, to satisfy point 1., then run PMD, point 2 means the entire cache is invalidated? Maybe, I'm missing something

Anyway we need more granularity. We could track dependencies of individual files in the analysis. With the TypeSystem object of pmd 7, which is the only place where a type can be created, we can actually place some kind of listener on type creation events, that is scoped to a single file. When the analysis of the file finishes, we have collected the set of external dependencies of the file. (footnote)

Without having to checksum the ABI of each JAR entry, we can then just checksum each entry as a blob, and if it changed, invalidate cache entries for every dependent file. This gives us much more granularity, and can be later extended to checksum the ABI if we need to.

If that's the route we take, this should be implemented in a java-specific way, and not in pmd core. I mentioned some ideas about making file dependency management language-specific [in this comment](https://github.com/pmd/pmd/issues/2667#issuecomment-665642427)

(footnote): This works provided we did type resolution strictly, ie, resolved types of everything, in a deterministic order. I think this will anyway end up being needed, because many rules in PMD 7 scan the tree for "every expression of type X", or some rather big subset of "any expression". And you only need one of those rules in your ruleset to lose the benefits of lazy type resolution. So it could actually really make sense to do type resolution strictly, after parsing, since it's anyway really fast in pmd 7. From an implementation standpoint, it's as easy as: `root.descendantsOrSelf(TypeNode.class).foreach(TypeNode::getTypeMirror)`.

**Comment by jsotuyod** [comment]
This is actually two-fold…

We check 2 classpaths when validating the cache:
1. We check the *runtime* classpath under which we are running PMD. Here, any changes are probably right to invalidate the cache. ie: a jar containing custom rules may include bug fixes, which change the binary, without necessary changing the ABI. This applies to all languages regardless of type resolution and is definitely within the realm of the core module.
2. We check the auxclasspath (if using type resolution at all), in which case we may be more nitpicky and look just at ABI changes.

As for tracking each individual type's dependencies… even though it would prevent the current all-or-nothing approach, it would still require lots of extra metadata stored and in memory, as we would have to store fingerprints per class (the current implementation keeps a single checksum for the whole classpath); along with a complete list of each class referenced from each file under analysis (with their complete hierarchy of super classes, annotations and interfaces for each referenced type - I may use directly class A from my class, but if A extends B which implements C and is annotated as D, changes to any of those 4 classes invalidates my class analysis). Such overhead is not gonna be free, and we should probably try a Proof of Concept to properly understand the gains and costs across a wide range of scenarios to properly assess it.


I already have a working implementation of a finer fingerprinting strategy that addresses the bogus change detection of jars stated on my previous post (PR coming soon). This alone is enough and probably as good as it gets for *runtime* classpath. It is still an improvement for auxclasspath, even if ABI analysis and / or per-class dependency tracking were to be implemented down the road.

**Comment by oowekyala** [comment]
It occurs to me, that the ClassLoader we use for the auxclasspath currently falls back on the runtime classpath. This means the type resolution (and PMD results) could change depending on the JDK version used to run PMD. I think we should eventually deprecate this behaviour (maybe in PMD 8), as PMD 7 decouples the JDK version used to run PMD and the JDK version of the analysed sources. In PMD 7, emitting a warning when fallback is happening would be nice, but we should also explicitly encourage users to put JDK jars/jmods on their auxclasspath. Maybe build tools like maven or gradle already do this.

**Comment by adangel** [comment]
> Maybe build tools like maven or gradle already do this.

Not that I'm aware of. The bootclasspath is usually not handled at all - it's just there. Yes, that's definitely something to keep in mind...

**Comment by jsotuyod** [comment]
Marking this as resolved. The 3 main issues with jar processing were tackled in #3324, and actually checking ABI compatibility would require to load all classes proactively and fingerprinting all non-private members… hardly going to be a net benefit on performance.

The bootclasspath has always been considered for cache validity. Also, since #4628 we can look at classes from the Java runtime in the auxclasspath separately from the bootclassloader.
