### ISSUE TITLE
Upload of pmd-regression-tester not available (301 moved permanently)

### ISSUE THREAD

**Issue by oowekyala** [pmd/pmd#2711]
The latest reports on PRs output "301 - moved permanently" instead of a link to the diff. Maybe there was a change in the chunk.io API?

Earliest example afaik: https://github.com/pmd/pmd/pull/2697#issuecomment-668521200

**Comment by adangel** [comment]
There is still an issue with chunk.io, e.g. https://chunk.io/pmd/51c1807282c84d08a77a8f1ad230936c/diff/index.html returns just "Don't know how to extract the given file". It seems, there is a problem detecting the correct mime-type of the file, since `curl --head https://chunk.io/pmd/51c1807282c84d08a77a8f1ad230936c` returns "Content-Type: inode/x-empty" when it should be "application/x-tar".

**Comment by adangel** [comment]
The whole archive can still be downloaded and extracted locally to have a detailed look into the results...

**Comment by adangel** [comment]
But this: https://chunk.io/pmd/02e399db65de4d919d1013285e359982/diff/index.html (from #2703) works...
(the other was from #2702)

**Comment by adangel** [comment]
This seems to work again, e.g. on #2714 the link https://chunk.io/pmd/65fecafd107d461a9829fa423c5b9ac0/diff/index.html works.
