### ISSUE TITLE
[core] Should PMD track quality history of project sources?

### ISSUE THREAD

**Issue by linusjf** [pmd/pmd#2942]
**Description:**
@fernal73:
How do you track improvements in the code-base? Do you think this is something PMD can or should do?

@numeralnathan:

What do you mean by track improvements? Do you mean fewer PMD violations over time? If so, we use SonarQube. SonarQube integrates with PMD rules nicely. With SonarQube, we require 0 PMD violations in changed code. The hope is that this will drive the number of PMD violations to 0 over time.

@fernal73:

Yes. I haven't used Sonar but I think it tracks improvements i.e.,
violation count etc... in a database and even provides graphs to display
the progress.

https://www.sourceallies.com/2013/05/code-quality-metrics-with-sonar-part-ii-overview-of-sonar-features/

@adangel:

About tracking improvement, see also #2568 - CI systems or any system that tracks history can visual improvements.

@fernal73:

Thanks for linking in, @adangel .

At the very least, PMD could support comparison with the previous run, as I stated [elsewhere](https://github.com/pmd/pmd/issues/1995#issuecomment-546620414).

While I don't expect PMD to become a SonarQube clone, maybe, we can consider an in-memory dB or a facility to configure a remote database where pmd logs can be stored instead of text or xml. What the users then choose to do with these logs is up to them.

@numeralnathan:

We set the quality gate in SonarQube for new/changed code. The hope is that over time the old code will slowly get fixed. We do not set a quality gate for the entire project because we have many projects. It would be difficult to set a quality gate for the entire project for every project since the thresholds would be different for each one.

To determine new/changed code, SonarQube compares the previous version of the branch to the current version. So, let's say I do one run through SonarQube. It flags a ton of problems in the new/changed code. I can change 1 line and submit it to SonarQube. SonarQube only sees that 1 line as changed. So, all of the previous problems slip pass the quality gate.

So, I recommend PMD establishes a baseline and keeps that baseline. If a new rule introduced, then PMD will need to add the violations to the baseline.

I suggest the baseline tracks the violation name and file but not line number. This way as lines move around the baseline won't get confused.

@fernal73:

My suggestion is quite simple. We compute a weighted score based on summation(priority * no. of violations for that priority). This is the quality score of the codebase. Our aim will be to reduce the score as violations are fixed. If new rules are added and fresh violations discovered, the score increases. The comparison usually would be to the previous execution.

Do we track suppressions as well?

Your way would need the entire history to be stored.

One concern would be housekeeping of this data. If it's a local dB, this would have to be done quite often. If it's stored to an enterprise dB, you could set a time or run based parameter or size before archiving the data or deleting it completely. It depends on how large the project is and the number of violations generated on average.

I do like the idea of base-lining a project score.

@numeralnathan:

Using a quality score sounds like a good idea.

I would ignore suppressions since there are sometimes good reasons to violate the rule.

**Comment by Fernal73** [comment]
Few questions about history and resetting a project's baseline:

1) There should be little impact when rules are simply renamed.

2) When rules are merged or deprecated, there will be a need to reset the baseline. How do you compare quality scores then?

**Comment by adangel** [comment]
See also the discussion at https://gitter.im/pmd/pmd?at=5e57c62baaf81d4d5481d70a

> Artem
@KroArtem
Feb. 27 14:37
@jsotuyod , thanks for more verbose explanation! I was thinking, though, about an option for incremental cache. Right now in case we want to introduce it, we need to fix all violations and then use in in our pipeline process. (So that the build will be always green). Some analyzers have an option called like Mass Suppression that suppresses old violations and warns only about new ones. As far as I understand there is no such possibility in current implementation?
Andreas Dangel
@adangel
Feb. 29 18:11
No, there is currently no feature like that built-in in PMD. The cache is the closest - in that it is the only feature, that considers historic data. I think, that would be an interesting feature, e.g. run PMD once and produce sth. like a "violation snapshot" and then use this snapshot in later runs. The simplest (and naive) implementation would be, to just look at the line numbers of the violation to determine, whether a violation is new or already existing.
I guess, you could implement something like this outside of PMD by using the XML report format and do a diff between a previously recorded report ("the snapshot") and the new one.
Ullrich Hafner
@uhafner
März 01 00:52
How do you run your pipeline? If you are using Jenkins then you can use the Warnings plugin to highlight and select only new PMD warnings. It already has such algorithm implemented that detects new warnings between two different builds.
Andreas Dangel
@adangel
März 20 15:01
@KroArtem I've written up the documentation now: pmd/pmd#2370 - and I remembered a similar question earlier: see pmd/pmd#2063 - atm you can only share the cache, if the full absolute path names stay the same

Related topics might be as well: incremental analysis, caching

**Comment by adangel** [comment]
Similar question: see #2915

**Comment by Fernal73** [comment]
We could normalise the quality score to make it comparable across PMD executions irrespective if rules have been added or new files added. With new files added, you could simply divide the weighted sum by total nccs count  of the code-base. Should we normalize for new rules as well or simply reset the baseline?

**Comment by rsoesemann** [comment]
TL:DR; But my answer is YES. PMD should natively support this. Many tool providers (e.g. Codacy.com) that internally leverage PMD use Incremental Analysis as a means to make that work.

**Comment by Fernal73** [comment]
> Normalise the quality score to make it comparable across PMD executions irrespective if rules have been added or new files added. With new files added, simply divide the weighted sum by total nccs count of the code-base. Should we normalize for new rules as well or simply reset the baseline? This is simply comparable over time for the same project.

We could have two versions of this score: 
1) One which has the denominator as total LOC and the weighted sum of violations as numerator 

2) One which has the denominator as total nccs count (including import statements) and the weighted sum of violations (excluding documentation rules) as numerator.

**Comment by Fernal73** [comment]
> TL:DR; 

It'll be good to simply make a list of which metrics you'd definitely like to see in PMD even if you have to comparison shop across static analysers.

**Comment by Fernal73** [comment]
It appears that Sonar Qube does have a metric similar to the proposed quality score or index.

https://docs.sonarqube.org/plugins/servlet/mobile?contentId=6947961#content/view/6947961

It's termed a rule compliance index.

I suggest we model the quality score on its lines with a few modifications to retrofit PMD priorities which range from 1 to 5, with one being most severe.

Let's modify the weights as (6 - priority) / 5.

Then , the quality score would be:  1 -  (Weighted Sum / TLOC)

You can multiply this by 100 to get the %age.

The above two variations on the quality score where comments and relevant rule violations  are either included or excluded still apply.

**Comment by Fernal73** [comment]
> > TL:DR;
> 
> It'll be good to simply make a list of which metrics you'd definitely like to see in PMD even if you have to comparison shop across static code analysers.

For starters, I'd like:

**File Churn Index**
**Maintainability Index**
**Technical Debt Indicator or Calculation**.
