### ISSUE TITLE
[GSoC] Clean Code

### ISSUE THREAD

**Issue by YaroslavTER** [pmd/pmd#298]
Hi, I'm interesting in your organization which is participating in Google Summer Of Code and I want to be accepted. I'm study in National Aviation University (Ukraine) on Software Engineering 3 year. I have tryed to implement my own code analyzer on Java using regex. Also I have some experience in implementation of own small games in JavaScript that is hosted on my GitHub account.  I have some experience with languages C#, HTML, CSS and use version control system Git. Hope on answer.

**Comment by jsotuyod** [comment]
@YaroslavTER welcomed! And thanks for your interest in PMD!

The next step would be for you to choose an idea to work on, and start drafting a proposal. There are several ideas to be found [on our wiki](https://github.com/pmd/pmd/wiki/Project-Ideas-%5BMature%5D), and some general thoughts of [interesting areas of development](https://github.com/pmd/pmd/wiki/Project-Ideas-%5BInception%5D); and of course, you could propose your own ideas.

Feel free to contact us if you have doubts or would like feedback on your ideas.

**Comment by YaroslavTER** [comment]
@jsotuyod thanks for answer.

**Comment by YaroslavTER** [comment]
@jsotuyod I choose the project "Сlean Сode Rules". I must iplement project into PMD or make own programm?

**Comment by jsotuyod** [comment]
@YaroslavTER great! The point of all proposed projects is to extend PMD's functionality, not to create new projects.

I'd start by cloning PMD, building it locally to ensure all tools are working. Then import it into your favorite IDE (if you hadn't already do that). And I'd start to create a high-level plan of the steps ("building blocks") you want to do, so that we can better assess whether it's realistic in terms of time. We can always adjust the plan on the way, don't worry. Feel free to start a new page in the wiki https://github.com/pmd/pmd/wiki for your proposal of the Metrics Framework (bare in mind, there is already a proposal draft from another student for this same project, make sure to create a separate document).

**Comment by YaroslavTER** [comment]
Thanks for advices,

**Comment by YaroslavTER** [comment]
The text below describes my vision of how project will work. After discussion, I'll add it to proposal. 
1) set rules for writing clean code;
2) collect metrics of the files of the selected project that are necessary for matching with the rules of clean code;
3) to correlate collected metrics with the rules and find the differences; 
4) bring out the differences and tips for writing.

**Comment by jsotuyod** [comment]
Marking this as closed to keep the tracker tidy. Proposals has been submitted, and review will go on over GSoC's formal channels.
