### ISSUE TITLE
[GSoC] Contributing into the project

### ISSUE THREAD

**Issue by bmthanki** [pmd/pmd#302]
Hi Guys,

I am currently a grad student at University of South Florida in Business Analytics and Information Systems. I have extensive experience in web development in last 2 years. 

I started my professional journey  in Java domain where I learned about Spring and Hibernate frameworks. My main role was Java Developer where I have worked with Remote Method Invocation as well as SAOP and REST based web services. I have also worked with Maven, Jasper, Spring Data and Spring Batch and Quartz for Batch processing. My work was not just limited to middle Java and mid layer but to also a lot of work in HTML and JavaScript in front end and native queries and procedure in SQL for Postgres. In deployment with Jenkins and Hudson we have used PMD plugin as code analyser.

I am interested to contribute to pmd project Easy Installation Packages or Auto fixable issues as a part of GSOC 2017. Please provide some more details about the project so that I can study and understand for it before applying. Please suggest if any bug fix is there, in which I can help.

**Comment by jsotuyod** [comment]
@bmthanki welcome, and thanks for your interest on PMD!

I'll gladly give you some extra insight into those 2 projects.

# Easy Installation Packages

As you may know, over the years PMD has moved away from a Java code analyzer into a full multi-language analyzer. However, our tooling remains mostly focused on Java (Ant, Maven, Gradle). Even if the last 2 allows to build other kinds of projects besides Java, for some of our supported languages, they do not (ie: building an iOS app with Objective-C / Swift, or building a Ruby on Rails app).

For those scenarios, the only way to currently use PMD is downloading a distribution package from Github / Sourceforge, unizpping, and manually running `run.sh`. This has several problemas:

 * it's hard to keep up to date with new releases
 * it's hard to make sure the whole team is on the same version
 * setting up the path to simplify PMD execution is cumbersome

So, we would like to provide packages for some of the most adopted systems out there (apt for linux, homebrew for Mac, and chocolatey for Windows), so that users can have easier access to PMD and it's updates.

The goal would be to be able to produce these packages easily, ideally streamlined into our release process / scripts, so that whenever we make a new release, we don't only publish it to maven central, but push it to these systems. I know for apt there is a nice Maven plugin, but I'm unsure of the other 2.

# Auto fixable issues

PMD is able to detect code violations by analyzing a program's code through the Abstract Syntax Tree produced by the parser. For most of these violations, fixes are trivial modifications to the AST (adding braces, renaming a variable, removing a modifier keyword, etc.). The goal of this project is to be able to produce such changes.

The fixes would have to be exposed on different ways, so that each use case can make the most of it:
 - an API, so that IDE plugins for instance can obtain them and suggest them as quick fixes
 - reports, along the violations, for tools relying on parsing the report (specially xml).
 - adding flags to PMD so that it can apply the changes automatically

This lowers greatly the barrier of entry for PMD on legacy codebases (where there are usually tons of violations), since the most trivial and common violations can be fixed automatically.

The main challenges are:
 - defining a way to express the AST modifications that is versatile enough to cover all scenarios
 - allowing to define such modifications both for rules written in Java (easy), and for rules defines as an XPath expression on an XML file (harder)

**Comment by jsotuyod** [comment]
Marking this as closed to keep the tracker tidy. Proposals has been submitted, and review will go on over GSoC's formal channels.
