### ISSUE TITLE
[ci] Cleanup github action logs

### ISSUE THREAD

**Issue by oowekyala** [pmd/pmd#3067]
Logs of github actions are bloated with tens of thousands of lines that look like this:

```
Progress (4): 3.6/4.9 MB | 2.1 MB | 295/306 kB | 0.4/1.4 MB
```

See eg https://github.com/pmd/pmd/pull/3064/checks?check_run_id=1714765470#step:6:20262

Those are emitted for the downloading of every dependency, I'm not sure why, but it's annoying as the log takes a long time to load.

There's also another INFO level log which lists all maven plugins that were resolved

It would be nice if there was a way to make the build more quiet

**Comment by adangel** [comment]
> It would be nice if there was a way to make the build more quiet

That's on the task list of #2967

The main problem is the dokka plugin which makes us to download the dependencies first, because it doesn't care about the standard maven timeout configurations for http connections. Github Actions runs in Microsoft's Azure cloud, there the timeouts are short. Maven pools the connections and fails, if the connection is used after it is dropped by Azure. Dokka unfortunately uses an unconfigurable pool... Hence I download in a first run all dependencies in the hope, that we don't need to download anything when the real build is running, since the http connection will be broken after Dokka.

Eventually this workaround can be removed, once https://github.com/Kotlin/dokka/pull/1644 lands into a new release of Dokka.

Using batch mode definitely makes sense, regardless of the other issues.
