### ISSUE TITLE
[core] Update beta version of asm with current version

### ISSUE THREAD

**Issue by regrog** [pmd/pmd#3093]
**Is your feature request related to a problem? Please describe.**
In my build beta and alpha version are not allowed to ensure stability.
This is not really a problem but stable versions are better that beta.

**Describe the solution you'd like**
PMD is using a beta version on org.ow2.asm:asm:9.0-beta
Actually version 9 is available https://mvnrepository.com/artifact/org.ow2.asm/asm/9.0
Can you please update asm to the latest stable version?

**Comment by oowekyala** [comment]
Thanks for reporting this. We can do that for the next version, which also is supposed to support JDK 16 language features (#3079). Apparently no classfile changes are planned for jdk 16, so ASM 9 is enough.

[ASM 9 announcement](https://mail.ow2.org/wws/arc/asm/2020-09/msg00000.html)

**Comment by regrog** [comment]
great, I just read this hehehe
https://github.com/pmd/pmd/issues/3079

**Comment by Fernal73** [comment]
@regrog So what does PMD use this for? And , more pertinently, in my case, will this allow me to disable an interface in a class? Say, Cloneable?

**Comment by adangel** [comment]
We'll probably update to the latest asm version, which is currently 9.1 (https://asm.ow2.io/versions.html)

> So what does PMD use this for?

PMD uses this for a small part of type resolution. In PMD 7, this library is an essential part of type resolution, allowing us to load class files and figure out the types without loading them into the current java application and avoid using reflection - which makes it much faster.
In PMD, we use the reading part of ASM.

> And , more pertinently, in my case, will this allow me to disable an interface in a class? Say, Cloneable?

Not sure, what you mean by that. This sounds more like a question for stack overflow: "How do I ...".
With ASM you can also generate byte code (the writing part), which you can then load into your application. But maybe, you need to look at java's agent instrumentation API - there you can use ASM to transform a class (read, manipulate, write) - and with the agent, you can modify the class before it gets loaded (because once a class is loaded, you can't change it - you'll need another classloader -> osgi). Another term what this is, is "load time weaving".

**Comment by Fernal73** [comment]
@adangel Yes, I spent some time reading up about this. From what I've discovered, only the Java Platform Debugger Architecture (JPDA) in conjunction with JavaAssist's hot swapping of classes allows for modified classes to be loaded and used within the same JVM.

**Comment by adangel** [comment]
I actually forgot to mention the most important feature for PMD 7 by leveraging more ASM instead of reflection: PMD run in a java8 jvm can then analyze projects developed for e.g. java16 - right now, you need to use the same jvm to run PMD that you use to compile your project, otherwise PMD can't load these classes (UnsupportedClassVersionError...)
