### ISSUE TITLE
[GSoC] Project Contribution (kthanky)

### ISSUE THREAD

**Issue by kthanky** [pmd/pmd#319]
Hello

I am currently pursuing **Bachelors of Engineering in Information Technology** at Birla Vishvakarma Engineering College in Gujarat, India and i am really interested in your organization and the work you are doing and I would really like to contribute to your project. I have extensive experience in coding and you can review my [Github](https://github.com/kthanky) for same. 

I have worked with Backend technologies such as Python, Java and PHP and also have worked on Frontend technologies such as HTML,CSS and JavaScript apart from that I have an experience of handling SQL and NoSQL Databases and also have a good experience with Android, was a part of Google program Applied CS with Android.

It would be an honor for me to work on your project and I really liked the idea of Easy Installation Packages and I have good knowledge about chocolatey and I feel that I can contribute for the same. Please provide some more details about the project so that I can study and understand for it before applying. Please suggest if any bug fix is there, in which I can help with.

Thankyou.

**Comment by jsotuyod** [comment]
Hello @kthanky and thanks for your interest on PMD. As requested, I'll provide you some extra info of the requested project:

# Easy Installation Packages

As you may know, over the years PMD has moved away from a Java code analyzer into a full multi-language analyzer. However, our tooling remains mostly focused on Java (Ant, Maven, Gradle). Even if the last 2 allows to build other kinds of projects besides Java, for some of our supported languages, they do not (ie: building an iOS app with Objective-C / Swift, or building a Ruby on Rails app).

For those scenarios, the only way to currently use PMD is downloading a distribution package from Github / Sourceforge, unizpping, and manually running `run.sh`. This has several problemas:

 * it's hard to keep up to date with new releases
 * it's hard to make sure the whole team is on the same version
 * setting up the path to simplify PMD execution is cumbersome (`run.sh` doesn't seem like the best script name in retrospective)

So, we would like to provide packages for some of the most adopted systems out there (apt for linux, homebrew for Mac, and chocolatey for Windows), so that users can have easier access to PMD and it's updates.

The goal would be to be able to produce these packages easily, ideally streamlined into our release process / scripts, so that whenever we make a new release, we don't only publish it to maven central, but push it to these systems. I know for apt there is a nice Maven plugin, but I'm unsure of the other 2.

Also, we would love for these packages to include nicer aliases (ie: `pmd`, `pmd-designer`, `cpd`, etc.) than the current `run.sh pmd`, `run.sh designer`, etc.

Let me know if you have any further doubts.

**Comment by kthanky** [comment]
Hello,
Thanks for that, I went through the details and did some research about it, also I have developed a simple chocolatey package for windows directory stat installing you can kindly check it over [here](https://github.com/kthanky/ChocolateyPackage-WinDirStat) , I have done some research on the other package distribution too like brew and apt and my work in chocolatey i have already showed and I feel that I can really work on this project, and as part of it i will submit a proposal by tomorrow so kindly check it and let me know if any feedback is there and also if there any bug or any other thing that I can work on kindly let me know.

**Comment by jsotuyod** [comment]
@kthanky that's great! Looking forward to it.

You can contact us on the [PMD development list](https://lists.sourceforge.net/lists/listinfo/pmd-devel)

**Comment by kthanky** [comment]
Hello,

I have submitted a proposal in GSOC and if there is anything that i can do to start contributing then please let me know or if there is any bug or anything that i can start working on then kindly do let me know.

**Comment by jsotuyod** [comment]
@kthanky that's really kind of you!

Any open issue that is tagged with anything but `question` is considered "accepted", and could be taken over. Feel free to go over them, and leave a comment at any one you feel confident tackling indicating you want to resolve it, and submit a PR.

**Comment by jsotuyod** [comment]
Marking this as closed to keep the tracker tidy. Proposals has been submitted, and review will go on over GSoC's formal channels.
