### ISSUE TITLE
[GSOC] Full Antlr Support

### ISSUE THREAD

**Issue by KirillZubov** [pmd/pmd#321]
Hello, 

I'm study on Master program at Department of Computation Physics, St Petersburg State University.

I'm fond of java development, compilers  and computer science.

My Bachelor's Graduate work was Develop the program complex for the cross-platform compilation of source code of virtual laboratories  to Java byte code. I used Antlr parser generator  for writing grammar. The code generator is written in Java. 

It would be excellent to participate in the PMD project as part of the Google Summer of Code and to find use of my modest skills. 

I would like to help with the solution of the problem "Full Antlr Support".

Looking forward to your response

**Comment by KirillZubov** [comment]
**my proposal**  
This is my proposal for a plan to solve this problem:
- First of all, I would try to make support in Pmd for a simple grammar (for example, grammar for [Сalculator](https://github.com/antlr/grammars-v4/blob/master/calculator/calculator.g4) or )
- Second, try to do a support additional language for some grammar from [an Antlr based grammar](https://github.com/antlr/grammars-v4)  (for example Fortran, why not this)
- Third, add support for other languages from the Antlr based grammar
- Fourth, write an unrealized grammar using Antlr ([Swift preference is given in the wiki](https://github.com/pmd/pmd/wiki/Project-Ideas-%5BMature%5D#full-antlr-support))

Unfortunately, it's hard to say something about time

**Comment by adangel** [comment]
That's great!

I'd suggest to think about, what the outcome would be for your for milestones. E.g., what would be the functionality (even though it might be incomplete at that point) for which you could create a pull request? I'd rather see many small pull requests, that gradually improve PMD, than one giant one at the end.

 I'm a bit unsure about the usefulness of the calculator grammar. As in the end, we want to write rules, that work on the AST. One example rule might be Unnecessary Parenthesis... While it might be a small grammar and might be useful for getting a feeling about the task, I don't think, it makes sense that we would merge this particular grammar into PMD :)  So, if you find another simple grammar, that would be awesome. 

We could make your second step a bit more fine grained: I'm absolutely OK with Fortran. There are a couple of steps, until we have the support for an additional language:
* integrate the grammar into the build process, so that the AST is generated (only the ANTLR part)
* add a language module for the new language. The language module makes the parser known to the pmd-core infrastructure. Use this new language module in unit tests, to try to parse some example files. Verify parsing, the node tree structure, the line numbers
    * I'd expect here at the moment a lot of boiler plate code. Currently we need to write for each ANTLR AST Node an adapter to make the class available for PMD's internal representation of the tree: each AST node needs to implement `net.sourceforge.pmd.lang.ast.Node`. Maybe - I don't know this - ANTLR allows to customize how the AST nodes are generated from the grammar and allows to automatically let each node implement this interface. That's kind of the approach we use for the javacc based languages. But for other languages, which bring already precompiled AST classes, we use the adapter approach (javascript and apex use this).
    * The **Designer** tool is very useful at this stage
* Once the parser is ready, think about one or two sample rules, that make sense for this new language. Ideally, one rule, that is implemented directly in Java and another rule, that uses an XPath expression. That way, we have the minimum covered. Depending on time, you might add more rules.
* Now it would be a good time, to write up some documentation: How to add a new ANTLR-grammar based language to PMD?

* If time permits, I'd try out the documentation with another fresh grammar.

Please don't forget to post an official proposal via the GSoC site...
> All proposals must be submitted by April 3, 2017 18:00 (CEST). 

Let me know, if I can help you further with your proposal.

**Comment by KirillZubov** [comment]
@adangel 
Thank you very much for your detailed reply and also for the detailed description of the second step.
Today I'm going to write a proposal for GSoC.

**Comment by jsotuyod** [comment]
Marking this as closed to keep the tracker tidy. Proposals has been submitted, and review will go on over GSoC's formal channels.
