### ISSUE TITLE
[core] designer.bat errors when JAVAFX_HOME contains spaces

### ISSUE THREAD

**Issue by zzzzfeng** [pmd/pmd#3328]
**Affects PMD Version:** 

version 6.35.0
Windows

**Description:**

error code:
`[%JAVAFX_HOME%] EQU []`

runtime error:
` if [C:\Program Files\javafx-sdk-11.0.2\] EQU [] (`
`此时不应有 Files\javafx-sdk-11.0.2\]。`

**fix:**
`["%JAVAFX_HOME%"] EQU [""]`

**Comment by LY1806620741** [comment]
I have the same problem as you.
This bug exists in windows10 cause space symbol.
https://github.com/pmd/pmd/blob/81739da5caff948dbcd2136c17532b65c726c781/pmd-dist/src/main/resources/scripts/designer.bat#L40

**Comment by adangel** [comment]
In this example:

```
> set JAVAFX_HOME="C:\Program Files\javafx-sdk-17.0.1"
> bin\designer.bat
Fehler: Hauptklasse Files\javafx-sdk-17.0.1\lib\* konnte nicht gefunden oder geladen werden
Ursache: java.lang.ClassNotFoundException: Files\javafx-sdk-17.0.1\lib\*
```

my error is a bit different: it can't find the main class - which means the command line for calling java is messed up.

Adding the suggested fix makes things worse:
```
"Files\javafx-sdk-17.0.1""]" kann syntaktisch an dieser Stelle nicht verarbeitet werden.
```

After reading http://windowsinspired.com/understanding-the-command-line-string-and-arguments-received-by-a-windows-program/ the problem is actually here: 

https://github.com/pmd/pmd/blob/7173f65a8733aef2e98cf7ade3828e0acaf8c6d8/pmd-dist/src/main/resources/scripts/designer.bat#L51

The quotes around "%classpath%" are wrong.
