### ISSUE TITLE
JavaTokenKinds class is missing

### ISSUE THREAD

**Issue by suren39** [pmd/pmd#3465]
**Affects PMD Version:** 
Project does not compile, missing following class
import net.sourceforge.pmd.lang.java.ast.JavaTokenKinds;

Make sure, to test with the latest PMD version.

**Description:**

**Exception Stacktrace:**

```
# Copy-paste the stack trace here
```

**Code Sample demonstrating the issue:**

```

```

**Steps to reproduce:**

Please provide detailed steps for how we can reproduce the bug.

1.  ... (e.g. if you're using maven: `mvn clean verify`)
2.  ...

**Running PMD through:** *[CLI | Ant | Maven | Gradle | Designer | Other]*

**Comment by adangel** [comment]
Unfortunately, you didn't give much context of what you are trying to do.

Since you are missing somehow the class "JavaTokenKinds", I assume, you are trying to compile pmd 7? (branch `pmd/7.0.x`).

Regardless of the version of PMD, the basic approach of how to build still holds true: See https://github.com/pmd/pmd/blob/master/BUILDING.md
See also https://github.com/pmd/pmd/wiki/Setup-IDE if you want to use a IDE.

If you run `./mvnw clean verify` everything will simply work.

The class you are missing is generated - hence it is not in source control. After you have executed maven to build the project, you find the generated sources under `pmd-java/target/generated-sources/javacc`.
