### ISSUE TITLE
[core] Add integration tests against real projects

### ISSUE THREAD

**Issue by adangel** [pmd/pmd#360]
Ideally we would run the current PMD against a few other (open-source) projects like Spring, Solr, openjdk, ...

This should help in finding NPE, ClassCastExceptions, Parser errors earlier.

**Comment by ryan-gustafson** [comment]
I'm experimenting with a Gradle build script to try this, since it's pretty easy to pull down and analyze dependencies dynamically, allowing multiple versions of PMD and real projects.  My thought would be to run a combination matrix of sorts, with some analysis of results between PMD versions.  Not far into it, I'll share when I have something interesting.  Reach out if you'd like to pick it up in the meantime.

**Comment by jsotuyod** [comment]
@ryan-gustafson sorry it took me this long to look at it, but that report is amazing! It would be of great help to both avoid regressions, and battle test fixes and improvements beyond our test cases before a release.

One interesting thing of those diffs is the number of differences between builds for DFA results.... specially considering we haven't touched that code directly in quite some time (check [this](https://github.com/pmd/pmd/tree/master/pmd-java/src/main/java/net/sourceforge/pmd/lang/java/dfa) and [this](https://github.com/pmd/pmd/blob/master/pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/controversial/DataflowAnomalyAnalysisRule.java))... seems that module is more fragile than I ever thought...

We definitely need to move this forward with master vs PR for PRs. We could upload diffs to chunk.io for free from Travis :) Please, contact me if you need help to set this up.

**Comment by ryan-gustafson** [comment]
@jsotuyod I've been so busy lately I've not been able to get back to this.  This weekend however is looking rather clear, so I'll see about getting a PR up, that should enable progress on other fronts.  I've not looked at all into chunk.io or Travis, I assume one of you guys could work on that.

Glad you found it interesting.  My hope is it has practical promise for allowing greatly expanding coverage and regression detection.  But not just between release, but for comparing your local dev against latest CI SNAPSHOT build, or on a PR basis.

The two thinks I know I'd like to add, but likely not before I send a PR, would be:

- Multiple language support.  Currently just doing Java, but that's a _gimme_ with Gradle and Maven repositories.  Any non-Java repositories out there?
- The recent CPD related issue https://github.com/pmd/pmd/issues/431 makes me think that would be good to add a CPR report too.

As for DFA, it's heavily dependent upon analysis of the symbol table data ([here](https://github.com/pmd/pmd/blob/master/pmd-java/src/main/java/net/sourceforge/pmd/lang/java/dfa/VariableAccessVisitor.java)), so changes there could indirectly change DFA results (for better or worse).

**Comment by jsotuyod** [comment]
> @jsotuyod I've been so busy lately I've not been able to get back to this. This weekend however is looking rather clear, so I'll see about getting a PR up, that should enable progress on other fronts. I've not looked at all into chunk.io or Travis, I assume one of you guys could work on that.

That's exactly the kind of things I was offering my assistance with. Let me know if you need anything.

> Glad you found it interesting. My hope is it has practical promise for allowing greatly expanding coverage and regression detection. But not just between release, but for comparing your local dev against latest CI SNAPSHOT build, or on a PR basis.

Definitely, as I said, I'm really looking forward to have this on all PRs by making Travis do PR vs master.

 > * Multiple language support. Currently just doing Java, but that's a gimme with Gradle and Maven repositories. Any non-Java repositories out there?

Not sure how you are getting the sources now, but for JS at least there are several big open source projects to look at. For Apex, Visualforce, PLSQL, Apache Velocity, XML and XSL things may be harder... But we can ask our Salesforce guys if there is a good OSS for Apex / VF to use as benchmark.

> * The recent CPD related issue #431 makes me think that would be good to add a CPR report too.

Definitely, but as you said, at a later stage. Just rolling this out as is is most valuable.

> As for DFA, it's heavily dependent upon analysis of the symbol table data (here), so changes there could indirectly change DFA results (for better or worse).

I had no idea, good to know. Reports should be better then, assuming the DFA code is right, since we improved symbol table a lot for some scenarios such as anonymous inner classes.

**Comment by jsotuyod** [comment]
@ryan-gustafson any chance we can get our hands on this, whatever state it's in? We would love for this to see the light, maybe even as part of GSoC 2018, and what you had shown us would be an amazing starting point.

**Comment by ryan-gustafson** [comment]
@jsotuyod I totally missed the ask for the code on this.  My apologies!  GSoC is in flight already, is it too late for the code to be useful?  I could dig it up this week sometime yet.

**Comment by jsotuyod** [comment]
@ryan-gustafson it's never late! @djydewang has already started on his own version, but yours may give him some insight or ideas.

**Comment by ryan-gustafson** [comment]
See attached ZIP.  It is Gradle Groovy based, version 3.5 using the Gradle wrapper.  Depending on the available Source dependencies/configurations, and PMD versions, it will dynamically create the appropriate tasks (a lot of them!).  The `pmdRegressionDiffReport` task will run everything, it can take a long time depending on _product_ of the number of PMD versions and Source dependencies.  There are other smaller tasks for the different parts, you need to look at the code to understand how they are all wired together.  Roughly the parts are:

* a clean target to delete the regression directory
* extract source code for all dependencies into regression directory
* run all PMD versions setup against all dependencies, save off stdout, stderr, and pmd report
* generate diffs between adjacent PMD versions for a given dependency
* generate the HTML report

The code isn't pretty, but it worked.  There's no shortage of kludges and work arounds, not all PMD versions worked right.  The `FIXME` comments, in the code that creates the task that runs PMD, outlines quite a few of the considerations I never got to.

[pmd-regression.zip](https://github.com/pmd/pmd/files/1982696/pmd-regression.zip)

**Comment by djydewang** [comment]
@ryan-gustafson Amazing! I have never thought of using dependency to generate PMD reports. Maybe I can refactor my code to generate PMD reports in this way. But since I'm not familiar with gradle, I may not be able to use the code directly.  There is no doubt that your code has inspired me a lot e.g. TODO and FIXME in the code are worth thinking about. Thank you for showing us a amazing starting point again:)
