### ISSUE TITLE
[test] Move pmd-test to java 8

### ISSUE THREAD

**Issue by oowekyala** [pmd/pmd#3758]
So I'm implementing #3302 and it would be nice to use Java 8. Could we do that for pmd 6.43.0? I think our test sources also use Java 8:

https://github.com/pmd/pmd/blob/de41d2cdbc1f5d7a2e05816d4167477efd1fb96b/pom.xml#L83-L84

**Comment by adangel** [comment]
Since for all the test sources, we already use java8, I think using it for pmd-test, should be ok. It must be mentioned in the release notes however, because if someone uses pmd-test for building own rule tests, that would require then java8.
So in other words: This change is compatible in terms of the binary distribution (the modules, that are still on pmd7 like pmd-core and pmd-java etc. stay at pmd7). But it's incompatible for third-party extensions, that use pmd-test as a (test-scoped) dependency.
