### ISSUE TITLE
[core] Improve build time on travis

### ISSUE THREAD

**Issue by adangel** [pmd/pmd#376]
Currently the build takes about 30 minutes on [travis](https://travis-ci.org/pmd/pmd). Depending on the load on travis-ci.org, it sometimes reaches the time limit for build jobs of 50 minutes...

These are the current big steps, that are executed on a regular push to master branch:

1.  mvn deploy -Possrh -B -V - takes ~ 10 min
2.  mvn site site:stage -Psite -B -V - takes ~ 10 min
3.  uploading the releases and site to sourceforge - takes ?
4.  mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.host.url=https://sonarqube.com -Dsonar.login=${SONAR_TOKEN} -B -V - takes ~ 10 min

Step 1 is essential, Step 2+3 will update http://pmd.sourceforge.net/snapshot/ and Step 4 will update https://sonarqube.com/dashboard?id=net.sourceforge.pmd%3Apmd

Any ideas on how to improve the build time? If we take for documentation something like https://readthedocs.org/ we could get rid of step 2 and part of step 3...

**Comment by jsotuyod** [comment]
We may split the build using a build matrix, so that 2-3 are done in one machine, and step 4 in another. That way wall clock time can be reduced by ~10 minutes according to your measurements.

For reference, you can check [here]( https://github.com/Monits/static-code-analysis-plugin/blob/staging/.travis.yml) how I used the env and script blocks to achieve thia on another project.

We may want to enable fail fast (one worker fails, all workers stop) on this case.

**Comment by adangel** [comment]
I'll give that a try: executing step 1,2,4 in parallel (step 3 is merged either into 1 or 2).

**Comment by adangel** [comment]
Hopefully, the release part will still be working with multiple build jobs...

**Comment by jsotuyod** [comment]
Wall clock seems to be down to ~22 mins. Amazing work!

**Comment by adangel** [comment]
Longest time takes the build-site step (building maven site + uploading zip and rsync the homepage to http://pmd.sourceforge.net/snapshot/).
There were some hickups with the release afterwards, I've one commit pending for that ...

**Comment by jsotuyod** [comment]
I just realized, the build doing the site is running all PMD unit tests. We could probably speed it a little by adding `-D maven.skip.tests=true` to that run.

And we still can make use of `travis_wait` instead of the ad-hoc keep alive function. I'll try a few changes tomorrow if that's ok with you.
