### ISSUE TITLE
"version_number" key in release/latest JSON return

### ISSUE THREAD

**Issue by dschach** [pmd/pmd#3834]
**Is your feature request related to a problem? Please describe.**
We are setting up some automated workflow and are using https://api.github.com/repos/pmd/pmd/releases/latest for information about the latest release (so we can download the newest version automatically).
However, we need to pull the release number by itself (e.g. "6.43") so we can update some files with that value.
None of the items in the latest release information have just "6.43" as the value, and we'd rather not parse it out of other items.

**Describe the solution you'd like**
Would it be a heavy lift to add a key/value in the output that says 
`  "version_number": "6.43.0"`

**Describe alternatives you've considered**
We are looking at parsing the URL of the download URL, but the more code we write, the more that we may write bad code :)

**Additional context**
This is a first step on making the ApexPMD repo able to call-out to the endpoint regularly, decide if the new release value is higher than the existing stored one, download and unzip the zip file, and automate a new package release.

**Comment by oowekyala** [comment]
I don't think we control this, this is the GitHub API. Many of those attributes are stable though, for instance the "tag_name" format has not changed since 2011 (the first tagged release). I think the easiest way for you is to parse this value.

@adangel may have better ideas.

**Comment by dschach** [comment]
I found a workaround to use in a script:
`VERSION=$(curl -s https://api.github.com/repos/pmd/pmd/releases/latest | grep '.tag_name' | sed 's:.*/::' | sed 's:",::')`

**Comment by adangel** [comment]
Yes, as @oowekyala described, GitHub (a Microsoft company) is providing all the services we are using. So, if you want to change the API of the GitHub platform, you'll need to request it directly by GitHub.

The tag_name is, what should be used to determine the version number. Since we moved to GitHub, the pattern is always "pmd_releases/<version>".

An easy bash script way to extract the version:

```
VERSION=$(curl -s https://api.github.com/repos/pmd/pmd/releases/latest | jq -r .tag_name)
VERSION=${VERSION##pmd_releases/}
```

See also https://github.com/ChuckJonas/vscode-apex-pmd/pull/104

I'm closing this, as we won't change anything here at PMD.
