### ISSUE TITLE
[java]  BeanMembersShouldSerialize : add a property to ignore class not implementing the Serializable interface

### ISSUE THREAD

**Issue by TehBakker** [pmd/pmd#403]
**Rule Set:**
I used PMD 5.4.1 though the Eclipse plugin.

**Description:**
The BeanMembersShouldSerialize rule : https://pmd.github.io/pmd-5.4.1/pmd-java/rules/java/javabeans.html#BeanMembersShouldSerialize
Since PMD has noway to determinate what is a bean and what is a Service, it would be great to have a property allowing to easily apply this rule only to Bean implementing the Serializable interface.
Kinda like Sonar now does it with its _Fields in a "Serializable" class_ rule.

I see a lot of people asking about it on Stackoverflow and it leads to people adding transient everywhere without really knowing why.

**Comment by jsotuyod** [comment]
Seems reasonable, since implementing `Serializable` is a requirement for Java Beans... We may want to use type resolution for this (to cover using `Externalizable` instead for instance).

The name of the rule is confusing too, since it's not checking that members should be serializable (which would be interesting on it's own), but rather if the getter / setters are in place. I suggest renaming this rule accordingly.

Also of note, Java Beans require a default constructor, currently no rule checks for this within the `java-javabeans` ruleset.

**Comment by Fernal73** [comment]
This rule could be enhanced to add a regex property to check if 'Bean' is in the class name and check for user-configurable package names and class names. That would help mitigate the number of false positives i.e., reduce the noise it produces.

**Comment by jsotuyod** [comment]
Marking this as resolved. Since PMD 6.52.0 this rule is no more.

It was superseded by 2 rules:
1. `NonSerualizableClass`, which will only look at classes already implementing `Serializable`
2. `InvalidJavaBean`, which will ensure compliance with the Java Bean Specification, is constrained by packages to analyze, and the actual implementation of `Serializable` is behind a property that defaults to `false`
