### ISSUE TITLE
[web] Release date is not properly formatted

### ISSUE THREAD

**Issue by jsotuyod** [pmd/pmd#407]
The release date for PMD 5.7.0 is read as `20-Mai-2017 - 5.7.0` on https://pmd.github.io/pmd-5.7.0/overview/changelog.html. There seems to be a locale issue here when generating the site from Travis.

**Comment by adangel** [comment]
Oops...
It's actually the helper script, that guides me through the release. It's not happening on travis, since travis will build from the tag, but someone needs to prepare the release and push it...
On [github releases](https://github.com/pmd/pmd/releases/tag/pmd_releases%2F5.7.0), the title of the release is correct, but the description (which is essentially a copy of the changelog) it's wrong.
