### ISSUE TITLE
[core] Explicitly name all language versions

### ISSUE THREAD

**Issue by oowekyala** [pmd/pmd#4120]
**Is your feature request related to a problem? Please describe.**
Some languages have a single language version with the empty string as a name. This is not a problem today but #4059 aims to make `--use-version` more useful by allowing to explicitly state a version to use for all languages. The goal of this is to have a failsafe in case the version is changed or removed, and to document versions better. This is not possible if versions have empty names.

**Describe the solution you'd like**
Give an explicit name for all language versions.

**Describe alternatives you've considered**
#4048 was an alternative to this but doesn't help with the `--use-version` use case described above, indeed making it worse.

**Additional context**
See full thread in https://github.com/pmd/pmd/pull/4059#discussion_r957793823

## PMD Language and version mappings

Language Id=Terse Name (Name) | Extensions | Rules | Version(s) in PMD 6 (*default) | Proposed Version(s) in PMD 7
------|------|-----|-----|-----
apex (Apex) | cls, trigger | :heavy_check_mark: | 54* | 52, 53, 54, 55, 56, 57*
ecmascript (Ecmascript) | js | :heavy_check_mark: | 3* | 3, 5, 6 (alias: ES6, ES2015), 7 (ES2016), 8 (ES2017), 9* (ES2018)
html (HTML) | html, htm, xhtml, xht, shtml | :heavy_check_mark: | ""* | 4, 5*
java (Java) | java | :heavy_check_mark: | 1.3, 1.4, 1.5, 5, 1.6, 6, 1.7, 7, 1.8, 8, 9, 1.9, 10, 1.10, 11, 12, 13, 14, 15, 16, 17, 18, 18-preview, 19*, 19-preview | same
jsp (Java Server Pages) | jsp, jspx, jspf, tag | :heavy_check_mark: | ""* | 2, *3
kotlin (Kotlin) | kt, ktm | :heavy_check_mark: | n/a - only PMD 7 | 1.6, 1.7*
modelica (Modelica) | mo | :heavy_check_mark: | ""* | 3.4, 3.5*
plsql (PLSQL) | sql, trg, prc, fnc, pld, pls, plh, plb, pck, pks, pkh, pkb, typ, tyb, tps, tpb | :heavy_check_mark: | ""* | 11g, 12c Release 1 (alias: 12.1), 12c Release 2 (alias 12.2), 18c, 19c, 21c*
text (Plain text) | plain-text-file-goo-extension | :x: | default* | :question: 
pom (Maven POM) | pom | :heavy_check_mark: | ""* | 4.0.0*
scala (Scala) | scala| :x: | 2.13*, 2.12, 2.11, 2.10 | same
swift (Swift) | swift | (:x:) :heavy_check_mark: | n/a (only CPD) | 4.2, 5.0, 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7*
vf (Salesforce VisualForce) | page, component | :heavy_check_mark: | ""* | 52, 53, 54, 55, 56, 57*
vm (VM) (=Velocity Template Language) | vm | :heavy_check_mark: | ""* | 2.0, 2.1, 2.2, 2.3*
wsdl (WSDL) | wsdl | :x: | ""* | 1.1, 2.0*
xml (XML) | xml | :heavy_check_mark: | ""* | 1.0, 1.1*
xsl (XSL) | xsl, xslt | :heavy_check_mark: | ""* | 1.0, 2.0, 3.0*

## PMD Languages that only support CPD

all except "go" are deprecated on PMD 6, as they don't support PMD
They will be/have been deleted in PMD 7

<details>

Language Id=Terse Name (Name) | Extensions |
-----|-----
cpp (C++) | h, c, cpp, cxx, cc, C
cs (C#) | cs
fortran (Fortran) | for, f, f66, f77, f90
go (Golang) | go
groovy (Groovy) | groovy
matlab (Matlab) | m
objectivec (Objective-C) | h, m
php (PHP: Hypertext Preprocessor) | php, class
python (Python) | py
ruby (Ruby) | rb, cgi, class
swift (Swift) | swift

</details>

## CPD Languages

Language Id=Terse Name (Name) | Extensions |
-----|-----
any (Any Language) | n/a
apex (Apex) | .cls
cpp (C++) | .h, .hpp, .hxx, .c, .cpp, .cxx, .cc, .C
cs (C#) | .cs
dart (Dart) | .dart
ecmascript (JavaScript) | .js
fortran (Fortran) | .for, .f, .f66, .f77, .f90
gherkin (Gherkin) | .feature
go (Go) | .go
groovy (Groovy) | .groovy
html (HTML) | .html
jsp (JSP) | .jsp, .jspx, .jspf, .tag
java (Java) | .java
kotlin (Kotlin) | .kt
lua (Lua) | .lua
matlab (Matlab) | .m
modelica (Modelica) | .mo
objectivec (Objective-C) | .h, .m
php (PHP) | .php, .class
plsql (PL/SQL) | .sql, .trg, .prc, .fnc, .pld, .pls, .plh, .plb, .pck, .pks, .pkh, .pkb, .typ, .tyb, .tps, .tpb
perl (Perl) | .pm, .pl, .t
python (Python) | .py
ruby (Ruby) | .rb, .cgi, .class
scala (Scala) | .scala
swift (Swift) | .swift
vf (VisualForce) | .page, .component
xml (XML) | .xml

**Comment by jsotuyod** [comment]
@oowekyala I edited the issue to include a list of languages and versions to set when we pick this up.

I took the freedom of setting values for those we know / can for sure. We can discuss others on this thread and add them there as a summary as we reach agreements.

**Open questions:**
- HTML should work for HTML5 and 4.01… it should also work for XHTML 1.1, do we handle that as a different version somehow? or should it be a completely different language?
- As for VLT, and given the nature of it (they version the engine, and changes to VTL are usually limited to reserved var names / predefined variables, with plenty of configuration flags to revert back to previous behavior), it may be good to just list "2.x" as version and not tie to a particular release.
- Visualforce: Visualforce and Apex versions go hand in hand. They are released at the same time and share the same number, so normally this would currently be "48", but is there a way for us to enforce both languages stay in sync?

**Comment by jsotuyod** [comment]
@adangel I'd argue this actually is required for PMD 7.0.0 release… otherwise, the `--use-version` arg for these languages don't comply with the documentation and would change in a breaking way in future releases.

https://github.com/pmd/pmd/blob/510f41ae1989a0fe2995973c8295ea4850b308a8/pmd-dist/src/test/java/net/sourceforge/pmd/it/BinaryDistributionIT.java#L32-L41

We may not be exhaustive in PMD 7 (although the cost is probably marginal), but at least 1 version per language would be required for proper compliance.

**Comment by adangel** [comment]
Yes, that makes sense. The language-version-combination `html-` looks weird.... I'll add it to the list. Maybe it can/is part of #4060.

**Comment by adangel** [comment]
Let me try to summarize the discussion:

* we don't want to have "empty" versions anymore, that is "". This results in invalid language-version strings when
  selecting a version at the CLI via `--use-version`.
  * no "versionless" modules anymore
* we don't ever talk about "defaults"
  * one of the versions will be marked as default - it will be used, if the user doesn't select a specific version.
    But it won't be named "default".
  * the default version might change in new versions of PMD. It is usually a minor version update (not breaking).
    That's what we do in Java.
  * the "empty" version is *not* equal to "default"
* naming a version "latest" is also not productive - it has similar consequences as providing a version named "default".

Approaching a solution:

* What do the version represent?
  * IMHO, they represent the languages' version. If we in PMD change the implementation or make breaking change in
    the AST (like in Java), these versions don't change.
  * They should be represent "well-known" versions for the language, whatever this means.
  * They say, which versions of the language is supported by PMD. E.g. we can mostly parse the version.
    That's one usage of the version in pmd-java - since newer java version often change the grammar, which requires
    a parser change.

* What are the versions used for?
  * in pmd-java for two things:
    * configuring the parser to only allow language syntax for the given version.
    * enabling/disabling rules, that only apply to specific language versions (minimumLanguageVersion, maximumLanguageVersion).
      This includes Java API changes (e.g. a rule suggesting a fix that is only possible since a specific Java version)
  * the only other language with multiple versions is pmd-scala. But there we don't have any rules. However,
    the parser is configured with the specific version, so there is a difference in theory.
  * no other language module than pmd-java uses minimumLanguageVersion / maximumLanguageVersion for rules
    * However, some Apex rules could use this
  * My assumption: Basically, when a user selects a specific language version when running PMD, he wants to make sure,
    that he don't sees violations, that are not relevant (because a problem was only relevant for older language
    versions).

Suggestion:
* For each language, we should list always all versions, that PMD can parse without immediate problems (the remaining
  problems can just be considered as usual bugs - like we have for Java or PL/SQL).
* That means e.g. for Apex, we list many versions. Starting now, we might just use the last 5 version, as I think the
  older versions are not really relevant.
  * for apex, we assume that jorje is backwards compatible. That means, it can parse always the latest version,
    but still supports code written in older versions (like Java). We don't need to configure the parser in a
    special way, it just parses with the latest version.
  * when we integrate the replacement for jorje (#3766), we have a better insight, what exactly the grammar changes
    are. See also #4368
  * Listing the versions enables rule writers, to use them as minimumLanguageVersion / maximumLanguageVersion
* Since only pmd-java uses minimumLanguageVersion / maximumLanguageVersion, selecting a specific version of other
  languages has virtually no effect right now - PMD does the same thing.
* We could (that's probably for PMD 8) consider, to not differentiate in pmd-java's parser between different version
  and always parse with the latest language features enabled. We assume anyway, that we only see compilable code, so
  we don't need to check this again. The language version would then really only be used to select applicable rules.

Suggested tasks:
- [ ] Research official versions for our supported languages. If there is no version, use the year of the
  latest specification. Document the location of the specifications.
- [ ] Add the versions. Always select the latest version as "default".
- [ ] Make the version name be required - empty version names are not allowed anymore
- [ ] Make sure for each PMD language, that the names are reused for the CPD language (e.g. Ecmascript / JavaScript)
- [ ] Make sure for each PMD language, that the same extensions are used for CPD language
- [ ] Change extension for pom to xml (fixes #1540)
    - we probably have anyway some extension clashes, at least for CPD (cpp vs. objectivec)

Wdyt?

**Comment by adangel** [comment]
I've done the research now and collected the specs etc.

### apex:
* [Apex Developer Guide](https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_dev_guide.htm)
* [Apex Reference Guide](https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ref_guide.htm)
* Versions currently (2023-02-03) documented online
    * v57.0 (Spring '23 (API version 57.0)) internal: 242.0
        * [Salesforce Spring ’23 Release Notes - Development - Apex](https://help.salesforce.com/s/articleView?id=release-notes.rn_apex.htm&release=242&type=5)
        * [Apex: New and Changed Items](https://help.salesforce.com/s/articleView?id=release-notes.rn_apex_nc.htm&release=242&type=5)
    * v56.0 (Winter '23 (API version 56.0)) internal: 240.0
        * [Salesforce Winter ’23 Release Notes - Development - Apex](https://help.salesforce.com/s/articleView?id=release-notes.rn_apex.htm&release=240&type=5)
        * [Apex: New and Changed Items](https://help.salesforce.com/s/articleView?id=release-notes.rn_apex_nc.htm&release=240&type=5)
    * v55.0 (Summer '22 (API version 55.0)) internal: 238.0
    * v54.0 (Spring '22 (API version 54.0)) internal: 236.0
    * v53.0 (Winter '22 (API version 53.0)) internal: 234.0
    * v52.0 (Summer '21 (API version 52.0)) internal: 232.0
* Enum in Jorje: `apex.jorje.services.Version`
* https://github.com/nawforce/apex-parser

Proposed versions: 57, 56, 55, 54, 53, 52


### ecmascript:
* https://262.ecma-international.org/
* https://github.com/tc39/ecma262/releases
    * ES2022, 13.0
    * ES2021, 12.0
    * ES2020, 11.0
    * ES2019, 10.0
    * ES2018, 9.0
    * ES2017, 8.0
    * ES2016, 7.0
* https://en.wikipedia.org/wiki/ECMAScript_version_history
    * ES2015, 6.0, ES6
    * 5.1
    * 5
    * 3
    * 2
    * 1
* Rhino: https://github.com/mozilla/rhino/releases
    * The parser can only be instructed to version `VERSION_ES6` (https://github.com/mozilla/rhino/blob/a73af65f1dc5f041c7c098b6b3aba951f5fbf79c/src/org/mozilla/javascript/Context.java#L102-L103)
    * But according to the compatibility table https://mozilla.github.io/rhino/compat/engines.html
      partial support for the following versions is there (scroll down):
      * ES2015
      * ES2016
      * ES2017
      * ES2018
      * "ESNEXT"

Proposed versions: 3, 5, 5.1, 6 (alias: ES6, ES2015), 7 (ES2016), 8 (ES2017), 9 (ES2018)

### html:
* https://en.wikipedia.org/wiki/HTML
    * 2.0
    * 3.2
    * 4.0
    * 4.01
    * 5
    * 5.1
    * 5.2
* https://en.wikipedia.org/wiki/HTML5
    * 5.3
* https://html.spec.whatwg.org/multipage/ | https://github.com/whatwg/html
    * "living standard": https://whatwg.org/faq#living-standard
    * "is this html5": yes (https://html.spec.whatwg.org/multipage/introduction.html#is-this-html5?)
* Our parser: [jsoup](https://jsoup.org/)

Proposed versions: 5, 4

### java:
* https://javaalmanac.io/
* Java Language Specification (JLS): https://docs.oracle.com/javase/specs/jls/se19/html/index.html
* https://openjdk.org/projects/jdk/

### jsp:
* formerly JavaServerPages
* https://en.wikipedia.org/wiki/Jakarta_Server_Pages
* https://projects.eclipse.org/projects/ee4j.jsp
    * 4.0.0 (to be released in 2024-03-31)
    * 3.1.1 (2023-02-01)
    * 3.1.0
    * 3.0 (first jakarta)
    * 2.0
    * 2.3.5
    * 2.3.4
* https://github.com/jakartaee/pages
* https://search.maven.org/artifact/javax.servlet.jsp/jsp-api
    * 2.2
    * 2.1
    * 2.0

Proposed versions: 2, 3, 4?

### kotlin:
* https://kotlinlang.org/
* https://kotlinlang.org/docs/releases.html#release-details
    * 1.8.10
    * 1.8.0
    * 1.7.21
    * 1.7.20
    * 1.7.10
    * 1.7.0
    * 1.6.21
    * 1.6.20
    * 1.6.10
    * 1.6.0
    * 1.5.32
    * 1.5.31
    * 1.5.21
    * 1.5.20
    * 1.5.10
    * 1.5.0
    * 1.4.x
    * 1.3.x
* [Kotlin language specification](https://kotlinlang.org/spec/introduction.html)
    * https://github.com/Kotlin/kotlin-spec/releases

* Proposed versions: 1.6, 1.7, 1.8 (and also update the grammar)

### modelica:
* https://modelica.org/modelicalanguage.html
* [Modelica Language Specification 3.5](https://modelica.org/documents/MLS.pdf)
    * See Appendix D.1 for changelog, "Minor updates of syntax, appendix A."
    * Older versions: 1.0, 1.1, 1.2, 1.3, 1.4, 2.0, 2.1, 2.2, 3.0, 3.1, 3.2, 3.3
* https://github.com/modelica/ModelicaSpecification/releases
    * 3.5
    * 3.4
* https://github.com/antlr/grammars-v4/tree/master/modelica

* Proposed versions: 3.5, 3.4

### plsql:
* https://en.wikipedia.org/wiki/PL/SQL
* https://www.oracle.com/database/technologies/appdev/plsql.html
    * Oracle Database 18c, 18.1 [Database PL/SQL Language Reference](https://docs.oracle.com/en/database/oracle/oracle-database/18/lnpls/)
    * Oracle Database 12c Release 2, 12.2 [Database PL/SQL Language Reference](https://docs.oracle.com/en/database/oracle/oracle-database/12.2/lnpls/toc.htm)
    * Oracle Database 12c Release 1
    * Oracle Database 11g Release 2
* https://docs.oracle.com/en/database/oracle/oracle-database/index.html
    * Oracle Database 21c [Database PL/SQL Language Reference](https://docs.oracle.com/en/database/oracle/oracle-database/21/lnpls/index.html)
    * Oracle Database 19c [Database PL/SQL Language Reference](https://docs.oracle.com/en/database/oracle/oracle-database/19/lnpls/index.html)
* https://en.wikipedia.org/wiki/Oracle_Database

* Proposed versions: 11g, 12c Release 1 (alias: 12.1), 12c Release 2 (alias 12.2), 18c, 19c, 21c

### pom:
* https://maven.apache.org/pom.html
    * "Notice that `modelVersion` contains 4.0.0. That is currently the only supported POM version, and is always required."
* https://maven.apache.org/ref/3.8.7/maven-model/maven.html
    * https://maven.apache.org/xsd/maven-v3_0_0.xsd for Maven 1.1
    * https://maven.apache.org/xsd/maven-4.0.0.xsd for Maven 2.0 (and 3.x)

Proposed versions: 4.0.0

### scala:
* https://www.scala-lang.org/
* https://www.scala-lang.org/download/all.html
    * 3.2.1
    * 2.13.10
    * 2.12.17
    * 2.11.12
    * 2.10.7
* Language Specification
    *   https://scala-lang.org/files/archive/spec/2.13/
    *   Changelog: https://github.com/scala/scala/commits/2.13.x/spec
    *   https://docs.scala-lang.org/scala3/reference/syntax.html
* Scala 3 releases: https://github.com/lampepfl/dotty/releases

### swift:
* https://docs.swift.org/swift-book/ReferenceManual/AboutTheLanguageReference.html
* Revisions: https://docs.swift.org/swift-book/RevisionHistory/RevisionHistory.html
    * 5.7
    * 5.6
    * 5.5
    * 5.4
    * 5.3
    * 5.2
    * 5.1
    * 5.0
    * 4.2
    * 4.1
    * 4.0.3
    * 4.0
    * 3.1
    * 3.0.1
    * 3.0
    * 2.2

Proposed versions: 4.2, 5.0, 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7

### Salesforce VisualForce:
* [Visualforce Developer Guide](https://developer.salesforce.com/docs/atlas.en-us.pages.meta/pages/pages_intro.htm)
    * "The Visualforce framework includes a tag-based markup language similar to HTML"
* Same versions as Apex (57.0 (Spring '23))

Proposed versions: 57, 56, 55, 54, 53, 52

### vm:
* https://velocity.apache.org/engine/devel/vtl-reference.html
* https://velocity.apache.org/engine/2.3/changes.html
    * 2.3
    * 2.2
    * 2.1
    * 2.0
    * 1.7
    * 1.6.4
    * 1.6.3
    * 1.6.2
    * 1.6.1
    * 1.6
    * 1.5
* https://github.com/apache/velocity-engine/blob/master/velocity-engine-core/src/main/parser/Parser.jjt
* VTL Reference Source: https://github.com/apache/velocity-site/blob/main/src/content/engine/devel/vtl-reference.mdtext

Proposed versions: 2.0, 2.1, 2.2, 2.3

### wsdl:
* https://en.wikipedia.org/wiki/Web_Services_Description_Language
  * 1.1 https://www.w3.org/TR/2001/NOTE-wsdl-20010315
  * 2.0 https://www.w3.org/TR/wsdl20/

Proposed versions: 1.1, 2.0

### xml:
* https://en.wikipedia.org/wiki/XML
* https://www.w3.org/XML/
* https://www.w3.org/XML/Core/#Publications
    * 1.0 https://www.w3.org/TR/2008/REC-xml-20081126/
    * 1.1 https://www.w3.org/TR/2006/REC-xml11-20060816/

Proposed versions: 1.0, 1.1

### xsl:
* https://en.wikipedia.org/wiki/XSLT
* https://www.w3.org/TR/xslt/
  * 1.0 https://www.w3.org/TR/1999/REC-xslt-19991116
  * 2.0 https://www.w3.org/TR/xslt20/
  * 3.0 https://www.w3.org/TR/xslt-30/

Proposed versions: 1.0, 2.0, 3.0

**Comment by adangel** [comment]
This is fixed for PMD 7 via #4387
