### ISSUE TITLE
[core] Refactor CPD integration

### ISSUE THREAD

**Issue by adangel** [pmd/pmd#4323]
Notes originally from #3809:
- reuse common infrastructure like text documents
- CPD programmatic API - goal is to reuse the same abstractions as PMD like FileCollector. No compatibility story planned for master. Also see #4204 
- Related to both items, maybe the cleanest approach would be to make CPD a PMD rule, and we could remove the programmatic API of CPD (keeping the CLI for convenience)

**Comment by oowekyala** [comment]
While it cannot be implemented as a rule yet, the hurdles you mention are the topic of #3920.

**Comment by oowekyala** [comment]
Also I want to eventually implement tree-based copy paste detection which would work by comparing trees instead of tokens. The most reasonable way to implement this is with #3920, because it still requires parsing files. I have an old prototype which gives much higher-quality results than CPD (https://github.com/oowekyala/pmd/tree/tree-clone-detection). This has the same challenges you mention about incremental analysis, but allowing one rule to process all files is not IMO a problem, as long as those rules that don't need to rerun use the violation cache.
