### ISSUE TITLE
[core] RFC: RuleSet Reorganization / Refactoring

### ISSUE THREAD

**Issue by adangel** [pmd/pmd#450]
This could be a task for 6.0.0:

Think about, how we could organize the available rules in rulesets more useful. See these [old discussions](https://sourceforge.net/p/pmd/discussion/188194/thread/b840897c/).

We could add additional "first-citizen" attributes to rules, such as:
* timeToFix -> see #329 
* category -> You could select rules by categories, such as "code style", "error prone", "performance", ... 
* changes to the ruleset schema, as suggested in [#437](https://github.com/pmd/pmd/pull/437#issuecomment-308161425)

I think, these additional attributes are generic and tool-agnostic enough, so that it makes sense to add them to "core PMD".

timeToFix and category would be useful for integration with other tools such as codacy, codeclimate, sonar, ... The tools probably would still need to map the PMD values to their own scale (e.g. timeToFix -> remediation_points, PMD category -> own category), but this metadata would be provided by PMD and could be stored with the other metadata of a rule (description, language, properties, ...).

The schema change could make it easier to modify ruleset xml, removing unnecessary duplication, moving the information about typresolution, dfa, metrics to the implementation and leaving only "real" metadata.
Maybe it makes even sense to distinguish between
* defining a new rule (now: rule-tag with class attribute)
* using a rule (now rule-tag with ref attribute)

The category could also be an easier way, to select interesting rules. If we allow a single rule to be in multiple categories (or we could tag rules), we could create "rule collections" for specific use cases: "introducing pmd" (kind of default configuration, what we currently have with maven-pmd-plugin: java-basic, java-empty, java-imports, java-unnecessary, java-unusedcode), "migrating junit3 to 4", "migrating from java5 to 8", ... Maybe these rule collections are just additional rulesets - so rules can appear in multiple rulesets.

**Comment by jsotuyod** [comment]
> Think about, how we could organize the available rules in rulesets more useful. See these old discussions.

I'm a huge fan of this. For quite some time I've been wanting to publish base rulesets people can use out of the box (ie: an Android ruleset would include not only the Android-specific rules, but also rules that help keep method and field count low, such as java-design/AccessorClassGenerator and java-design/AccessorMethodGenerator). Goes a long way to make a better quick-start / soft-landing for new users.

The current schema already allows for these things, we would just have to make sure these pre-defined rulesets are parsed differently when building the website. I'm not sure I'd go for a more in depth break-up here, since that would probably be very hard on any backwards compatibility / high cost migration; which would hamper adoption.

The rule reorganization will probably require it's own thread to discuss 'though. Maybe you could create a wiki page with a draft of how to reorganize them?

> We could add additional "first-citizen" attributes to rules, such as: ...

I'm ok with those too, but I tend to think more and more having the messages in the XML is not so cool and may need some rework... There are several rules now that provide a way too generic error message, and would benefit from being more precise. For instance, `java-unnecessary/UnnecessaryModifier` reports for extra `public`,  `static`,  and even some `finals` (but not all, we still have #411 and #412); and being more specific about which modifier and why is redundant on each case may be helpful. `java-basic/SimplifiedTernary` would also greatly benefit if we just said "this can be rewritten as XXX" instead of he current message.

**Comment by oowekyala** [comment]
> I'm not sure I'd go for a more in depth break-up here, since that would probably be very hard on any backwards compatibility / high cost migration

@jsotuyod I was just thinking about that, would it be possible to write an XSL transform to convert ruleset files from the old schema to the new using Saxon? We could for example warn the user that his ruleset is outdated and propose to convert it in the CLI and plugins. That could reduce the migration cost and let us make changes more freely.

**Comment by jsotuyod** [comment]
@oowekyala yes, theoretically possible assuming there are equivalencies... may not hold true for all changes we come up with (ie: new attributes / categories with no clear default). I'd still try to avoid it unless we have a very strong reason not to...

I think non the less, we are past due to start drafting this. PMD 6.0.0 is already shaping up very nicely. We still have [a bunch of open issues](https://github.com/pmd/pmd/milestone/12) but that list is getting smaller every week. Otherwise, we risk having to drop this for PMD 7.0.0

**Comment by oowekyala** [comment]
> we are past due to start drafting this

I agree, would be a shame to push that back. I'd like to add something to the discussion:

> The category could also be an easier way, to select interesting rules.

I think that's the most interesting point of this reform. The main use we may have for categories is for integration into the category systems of other tools, but they can potentially allow us to organise our rules more logically, and offer greater flexibility to select rules. The following may be overly ambitious, but some ideas may be worthwhile.

Categories are sets of rules, like rulesets, so we might as well draw a clear distinction right now. I think the following is a good start:
  * Categories *classify* rules according to the class of problems they tackle, e.g. "code style", "control flow", "error handling", "inheritance issues", "probable bugs", "performance"...
  * Rulesets define a subset of all rules to execute, for a specific *use case*, e.g. "default config", "introducing pmd", "migrating junit3 to 4" + custom rulesets

Imho the current ruleset organisation somewhat lacks cohesion and structure. The "design" and "basic" rulesets in particular comprise all sorts of rules that could be better classified with another category hierarchy. We could imagine a category tree such as the following:
```
+ Error handling
| - empty/EmptyCatchBlock
| - empty/EmptyFinallyBlock
| - basic/ReturnFromFinallyBlock
| - design/AvoidInstanceofChecksInCatchClause
| - design/PreserveStackTrace
| - strictexceptions/*
| ...

+ Control flow
| - basic/ForLoopShouldBeWhileLoop
| - basic/AvoidBranchingStatementAsLastInLoop
| - basic/SimplifiedTernary
| - design/ConfusingTernary
| - design/SimplifyBooleanExpressions
| - everything about switches

...
```
Well you get my point, most rules in these rulesets could be moved into more adapted categories. I think what might be best is define a "primary" category for each rule, and declare rules of the same primary category in the same (ruleset) xml. Then we might add additional categories with the attribute of the rule.  

Some reasons why we might want to do that:
* Keep everything related together, clearer internal structure
* Spot more easily which categories lack some rules
* More intuitive selection of rules for the user

If we could define several categories to a single rule, then we would still have a way to refer to all `emptyXXstatement` rules through a category reference, even though they are declared in different files. To implement that I guess we could have some kind of category index generator, which runs after the build and for example generates a single xml file listing all categories, the rules they contain, and the file in which the rule is declared to find its declaration at runtime.

Moreover, such secondary categories could provide a convenient alternative to the "controversial" ruleset. That ruleset, like "basic" and "design", groups rules of all sorts. I think it would be better to move them into their "primary" category, and tag them with the "controversial" category. The user could then ignore them while importing a category in his ruleset, for example:
```xml
<category ref="java/codestyle">
  <exclude ref="java/controversial" />
  <exclude ref="java/codestyle/SomeRule" />
</category>
```
Not importing the controversial category could even be the default behaviour of category imports.

Backwards compatibility could be kept, as this new category system could coexist with the existing standard rulesets. We could redefine the existing rulesets so that they do not *define* the rules but import them from categories. Users could still use the good ol' `rulesets/basic.xml/...` reference, which would point back to the rulesets. (At some point we might want to prevent that, for consistency, and make users import standard rules from categories and not rulesets).

We could then make standard rulesets with e.g. a default config for pmd, etc. That would make for a very easy landing for new users

...

Back to earth, we don't have to do all that for 6.0.0. It's time to start a draft, so here's my 2 cents on what's been previously been said:
* time2fix is not that complicated to add, we'd just have to divide the work and keep track of each other
* The category attribute could use category labels like what I have described. Here's a more complete draft:
  * Code style: things such as braces, modifier order, most rules from "unnecessary", redundant thingsetc.
  * Error handling: everything about exceptions
  * Control flow: everything about switch, if statements, loops, simplifiable boolean conditions, labeled statements, break and continue statements, etc.
  * Probable bugs: empty statements, NPEs, comparing objects with equals, unused assignments, etc.
  * Performance issues
  * Naming (conventions)
  * (Object oriented) design: god classes (and other problems -> metrics!), inheritance issues
  * Imports
  * Java logging
  * Jakarta Commons logging
  * Threading/ concurrency
  * Unused code
  
  "Controversial" should be a secondary category imo. We'd have to agree on the repartition of rules in these categories and perform changes to the xml. To allow users to select rules from categories, the best way I see is to use an index generator, with the downside that it would somewhat lengthen our build time.

* I don't think it's necessary to make a difference between defining rules and referencing a rule, enforcing stricter schema validation constraints could be sufficient imo

> There are several rules now that provide a way too generic error message, and would benefit from being more precise.

* @jsotuyod I think this can already be done with placeholders, can't it? Besides we must keep that for Xpath rules

> , moving the information about typresolution, dfa, metrics to the implementation and leaving only "real" metadata.

* I still think using a dedicated `xpath` element is a good idea. I'll try to make a XSLT which can convert the current xpath rule declaration to a `xpath` element. If that works, then the cost of this change will be null. The old way would still work as long as we don't change the implementation of XPath, which I think is not planned anytime; the new way could be automatically worked out by pmd with Saxon, and we reduce code duplication and implementation exposure. I'll get back to you when I've got some news

Besides that, I think it would be interesting to automatically detect dependencies in XPath like @jsotuyod suggested [here](https://github.com/pmd/pmd/pull/437#issuecomment-309141980). Although does typeresolution really need it since it's enabled by default? Other than that, metrics are not accessible to XPath yet, and dfa isn't either I think. Is there a need to do that for other languages than Java? Annotations could be enough for Java rules.

Sorry for the very long post... Last point: it might be interesting to use a Github project board to keep track of everything, since this will probably take some serious organisation

**Comment by adangel** [comment]
As I'm currently going through the rules: Another duplicate:
[controversial/UnnecessaryParentheses](http://pmd.sourceforge.net/snapshot/pmd_rules_java_controversial.html#unnecessaryparentheses) vs. [unnecessary/UselessParentheses](http://pmd.sourceforge.net/snapshot/pmd_rules_java_unnecessary.html#uselessparentheses)

**Comment by oowekyala** [comment]
Hi, 
I meant well with my previous post, but I had not paid enough attention to the linked thread and repeated a lot of info. Sorry about that... 

I think @ryan-gustafson has a point when he says categories we use for documentation or internal organisation should not influence the rule's user interface. So I guess we can forget about category references like I proposed in the above comment. They would probably be difficult to implement anyway.

Anyway based on everything that was said, I've tried to make a realistic draft in #610

What that draft does address:
* Rule reorganisation
* Ruleset agnostic rule references, like what's proposed in the linked thread

What that draft doesn't address:
* timeToFix attribute
* RulesetFactory refactoring
* @jsotuyod's idea about reworking messages in the XML
* Stricter validation constraints on the schema

P.S. I've fiddled a bit with the dedicated "xpath" element, and I think that won't be feasible. I've got an XSLT, but it would be very difficult to get a schema that makes sense with XSD 1.0 (without "xs:assert" elements). So, probably not worth the time

**Comment by jsotuyod** [comment]
I'm closing this, as the scope of the reorganization is now defined. Work continues on #610 as to how to reorganize the rules.

We may want to open new RFCs for PMD 7.0.0 regarding the points we left out for 6.0.0:

 * timeToFix attribute
 * RulesetFactory refactoring
 * reworking messages in the XML
 * Stricter validation constraints on the schema
