### ISSUE TITLE
[core] EnumeratedProperty<T> does not return a T as its value

### ISSUE THREAD

**Issue by oowekyala** [pmd/pmd#459]
**Description:** To use a rule property that can take its value in an enumeration, I think the preferred approach is an EnumeratedProperty. I create an EnumeratedProperty like this:
```java
private static final String[] LABELS = { "foo", "bar" };
enum Foo { FOO, BAR }
private static final Foo[] CHOICES = { Foo.FOO, Foo.BAR };

public static final EnumeratedProperty<Foo> FOO_DESCRIPTOR = new EnumeratedProperty<>(
    "fooChoice", "Choose a instance of Foo", LABELS, CHOICES, 0, 3.0f);
```
where the parameter `0` indicates the default index. But the value returned by `getProperty` is really weird:
* If the property was not explicitly given a value in the ruleset.xml, then `getProperty` returns `"foo"` (a String)
* Otherwise, `getProperty` returns an instance of `Foo`, which corresponds to the label given in the XML.

I would think it's abnormal that `getProperty` may return something other than a `Foo`, especially since it's an `EnumeratedProperty<Foo>`. Is that a bug or am I doing this wrong ?

**Comment by jsotuyod** [comment]
This is a bug. There seems to be plenty of work to do on type safety with properties in general. Lots of unchecked casts and usage of `Object`

Notice however that, even though `EnumeratedProperty` defines `new BasicPropertyDescriptorFactory<EnumeratedProperty>(Enumeration.class) {`, it's not constrained to the use of Java enums, but is actually intended for developers to define ad-hoc mappings between Strings (names), and whatever value they intend.

**Comment by jsotuyod** [comment]
I'm marking this for 6.0.0. Even though it's a bug, it implies an API change (changing types in a bunch of places to enforce type-safety).

**Comment by oowekyala** [comment]
Hum ok thanks
It would be great to make all that type safe, but I think the IDE plugins depend on that API?

**Comment by oowekyala** [comment]
@jsotuyod I've begun working on refactoring the properties API (see [this commit](https://github.com/oowekyala/pmd/commit/578bbf8f7bcb0ff5d9522d19260f13e32662cb19)). I think in order to make the API more typesafe and easily extensible we should change the way to represent multi valued properties. They're currently implemented as `AbstractProperties<T>` with `T` extending `Object[]`. The problem with that is that it forces a lot of casts to `Object[]` and to check the values inside as Objects... Lists are better candidates than arrays because they're parameterized.

The draft I made makes serious changes to the class hierarchy in the package. The separation between multi valued and uni valued properties moves from the bottom of the hierarchy to the top, with `AbstractMultiValueProperty<V> extends AbstractProperty<List<V>>` and `AbstractSingleValueProperty<T> extends AbstractProperty<T>`. Methods of `AbstractProperty` thus need no more always check if the property is univalued or multivalued, as these very different logics are separated in their own top level abstract classes.

Using this model we could definitely move away from needing `Object` and nearly all unchecked casts. I've moved a little further on the refactoring but I'd like comments before really committing to this strategy. What do you think?

**Comment by hooperbloob** [comment]
No issues with the changes, just ensure that the Eclipse plug-in still works after your refactoring. --- notifications@github.com wrote:From: Clément Fournier <notifications@github.com>To: pmd/pmd <pmd@noreply.github.com>Cc: Subscribed <subscribed@noreply.github.com>Subject: Re: [pmd/pmd] [core] EnumeratedProperty<T> does not return a T as its value (#459)Date: Sun, 25 Jun 2017 09:02:58 -0700@jsotuyod I've begun working on refactoring the properties API (see this commit). I think in order to make the API more typesafe and easily extensible we should change the way to represent multi valued properties. They're currently implemented as AbstractProperties<T> with T extending Object[]. The problem with that is that it forces a lot of casts to Object[] and to check the values inside as Objects... Lists are better candidates than arrays because they're parameterized.
The draft I made makes serious changes to the class hierarchy in the package. The separation between multi valued and uni valued properties moves from the bottom of the hierarchy to the top, with AbstractMultiValueProperty<V> extends AbstractProperty<List<V>> and AbstractSingleValueProperty<T> extends AbstractProperty<T>. Methods of AbstractProperty thus need no more always check if the property is univalued or multivalued, as these very different logics are separated in their own top level abstract classes.
Using this model we could definitely move away from needing Object and nearly all unchecked casts. I've moved a little further on the refactoring but I'd like comments before really committing to this strategy. What do you think?

**Comment by jsotuyod** [comment]
@oowekyala it looks really good indeed. I'm eager to see more!

I left you a bunch of comments to guide you as you move on. I know it's still very early, but I couldn't resist.

As @hooperbloob said, since you are changing APIs on a very hardcore way, before submitting a PR, check against [pmd-eclipse-plugin](https://github.com/pmd/pmd-eclipse-plugin) to make sure how bad it breaks, and make sure to submit a PR to that project too.
