### ISSUE TITLE
[java][codestyle] Parameters missing for rule ClassNamingConventions

### ISSUE THREAD

**Issue by stefanvacareanu7** [pmd/pmd#4641]
**Affects PMD Version:** 
6.55.0

**Description:**

In [the official documentation for rule ClassNamingConventions](https://docs.pmd-code.org/pmd-doc-6.55.0/pmd_rules_java_codestyle.html#classnamingconventions) there are specified multiple properties, while in [the XML file for this rule](https://github.com/pmd/pmd/blob/1021b3b7d4addb2ac2b5229124eb7ff1524337a7/pmd-java/src/main/resources/category/java/codestyle.xml#L245), there is none. 

As well, for [MethodNamingConventions](https://docs.pmd-code.org/pmd-doc-6.55.0/pmd_rules_java_codestyle.html#methodnamingconventions) there are many properties specified, while in [the XML](https://github.com/pmd/pmd/blob/1021b3b7d4addb2ac2b5229124eb7ff1524337a7/pmd-java/src/main/resources/category/java/codestyle.xml#L1054) there is one only.

Can you please add them?

Thank you!

**Comment by adangel** [comment]
Hi @stefanvacareanu7 ,
thanks for the report.

The properties are not defined in the XML file, but in the corresponding rule implementations, e.g. for ClassNamingConventions:

https://github.com/pmd/pmd/blob/2b0cadf0ed8ba29fd7207df61c4f08b13f375279/pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/ClassNamingConventionsRule.java#L25-L33

You can't use the XML ruleset files to figure out, which properties are possible. You need to use the documentation, which is generated from the rule implementation classes.

Since there is nothing wrong with the XML files, I'm closing this issue.

Regards,
Andreas

Related issues: #4295 #1335 #4187
