### ISSUE TITLE
[java] RuleSet description is missing. Future versions of PMD will require it.

### ISSUE THREAD

**Issue by Macarse** [pmd/pmd#470]
**Rule Set:** N/A

**Description:** N/A

**Code Sample demonstrating the issue:** N/A

**Running PMD through:** *Gradle*

I just upgraded to 5.8.0 and I am getting `RuleSet description is missing. Future versions of PMD will require it.` I do not see any mention to this in the [release notes](http://checkstyle.sourceforge.net/releasenotes.html)

Is this new?

**Comment by jsotuyod** [comment]
@Macarse there is no mention because there is really no change here. The description has always [been required in the XML Schema](https://github.com/pmd/pmd/blob/master/pmd-core/src/main/resources/ruleset_2_0_0.xsd#L11) and [the DTD](https://github.com/pmd/pmd/blob/master/pmd-core/src/main/resources/ruleset_2_0_0.dtd#L1), we simply added a notice for users not complying to it so they may do so with time, before we start to actually validate ruleset xmls against the schema definition.

Doing so will probably not happen before PMD 7.0.0, so everyone should have plenty of time to fix their rulesets before then.

Are you having any particular issue with this?

**Comment by Macarse** [comment]
@jsotuyod Not really. I started seeing a lot of those warnings since I run pmd in several modules.
As I didn't see anything about this in the release notes I decided to create this ticket.

I wonder why the description is required, I don't even see it in the report.

**Comment by jsotuyod** [comment]
@Macarse right now they aren't used, but we plan to start giving more visibility to where violations come from / some better insight into what rules are configured and how.
