### ISSUE TITLE
[core] Missing screenshot on "How to write a rule" doc

### ISSUE THREAD

**Issue by megascus** [pmd/pmd#480]
**Description:**
I can not see the image on this page.
https://pmd.github.io/pmd-5.8.1/customizing/howtowritearule.html
https://pmd.github.io/pmd-5.8.1/customizing/images/designer_screenshot.png

**Comment by adangel** [comment]
Thanks for reporting. The URL to the image is wrong on that site, it's actually https://pmd.github.io/pmd-5.8.1/images/designer_screenshot.png
So the `resources` folder is indeed deployed.

However, since the plan is, to revamp the documentation entirely for PMD 6.0.0 (see #405), I think, we won't fix it for any 5.8.x version.

**Comment by adangel** [comment]
I've fixed it for the online version of the documentation.
