### ISSUE TITLE
[core] PMD sarif schema file points to nonexistent location

### ISSUE THREAD

**Issue by dschach** [pmd/pmd#5201]
(Am submitting a pull request to fix this, but I do not know how to test it.)

**Affects PMD Version:** 

7.5.0

**Description:**

The sarif file generated by PMD has a schema file reference that is 404. GitHub has a recommended schema URL (https://json.schemastore.org/sarif-2.1.0.json) that seems better, and it points to the same version that PMD currently uses.

**Exception Stacktrace:**

```
404: Not Found
```

**Code Sample demonstrating the issue:**

```json
{
  "$schema": "https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json",
  "version": "2.1.0",
  "runs": [
    {
      "tool": {
        "driver": {
          "name": "PMD",
          "version": "7.5.0",
          "informationUri": "https://docs.pmd-code.org/latest/",
etc...
```

**Steps to reproduce:**

Please provide detailed steps for how we can reproduce the bug.

1.  Generate a sarif output PMD scan
2.  Inspect the file - it has a nonexistent `$schema` value

**Running PMD through:** *CLI*

**Comment by adangel** [comment]
It seems, the original location of the json schema has been moved to https://raw.githubusercontent.com/oasis-tcs/sarif-spec/main/sarif-2.1/schema/sarif-schema-2.1.0.json .
And there is a new version of Sarif coming up (2.2 -> https://github.com/oasis-tcs/sarif-spec/tree/main/sarif-2.2/schema )

Interesting is, that the "$id" of the schema from https://json.schemastore.org/sarif-2.1.0.json also points to the old "url" (https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json) ...

Checking the spec at https://docs.oasis-open.org/sarif/sarif/v2.1.0/sarif-v2.1.0.html, the schema location would be https://docs.oasis-open.org/sarif/sarif/v2.1.0/errata01/os/schemas/sarif-schema-2.1.0.json

Now we have 3 different locations for the schema - I didn't compare these. I guess, the latter is the most correct/updated version, since it is directly from oasis-open.


Just out of interest: How/where did you notice, that the URL is broken? Did any tool refuse to work with the report PMD created? (Maybe we can add a test...)

**Comment by dschach** [comment]
@adangel Sorry for late response. Found that the schema was 404 when I looked in a sarif file generated by PMD because I plan to parse it and make a markdown or html table. VSCode showed the error when opening the file.
