### ISSUE TITLE
[doc] ConsecutiveLiteralAppends with types other than string 

### ISSUE THREAD

**Issue by Reissner** [pmd/pmd#541]
**Rule:** ConsecutiveLiteralAppends (category java-performance)

**Description:**

If two basic objects are appended, (neither string) then a warning is issued, 
which should not be. 

**Code Sample demonstrating the issue:**

```
   	    evalStr.append('x');// pmd bug: warning: two consecutive times append literal
    	    evalStr.append(0);
  	    evalStr.append(",x");// pmd: no warning: ok 
   	    evalStr.append(i);

```

**Running PMD through:** *[CLI | Ant | Maven | Gradle | Designer | Other]*

**Comment by jsotuyod** [comment]
Definitely a bug, thanks for the report!

**Comment by jsotuyod** [comment]
I'm reviewing this again before attempting a fix, and I'm wondering... other than the rule says "Consecutively calling StringBuffer/StringBuilder.append with *String literals*", is there any reason you wouldn't write the code as `evalStr.append("x0,x").append(i)`?

I'm starting to think this may be more an issue with the message itself than with the check itself.

**Comment by Reissner** [comment]
I Think the name is the key: The rule shall be renamed: 
ConsecutivelyLiteralAppends-->ConsecutivelyStringLiteralAppends
or ConsecutivelyAppendsOfStringLiterals. 
I think, it is ok, to append literals of other types as e.g. 
append(0).append(4) 
but it is not ok to do so with strings: 
append("abc").append("def") which shall be written as append("abcdef")
Also *maybe* not ok, consecutive chars: 
append('a').append('b') *maybe* better written as append("ab") 
also 
append("ab").append('c') and append('a').append("bc") shall be rewritten append("abc") 

so the correct name should maybe 
ConsecutivelyStringOrCharLiteralAppends or something. 
And of course the implementation should be that like. :O)

**Comment by jsotuyod** [comment]
I don't see much difference in expecting `append('a').append('b')` to be written as `append("ab")` and expecting `append('%').append(0)` to be written as `append("%0")`...

Appending numbers is actually more expensive than appending string literals, since the size has to be computed and each character calculated on it's own. This requires a bunch of loops and an interesting amount of bitwise operations; while string appending requires checking the `length` and just copying char by char.

Therefore I'm more inclined to keep the rule name, and just alter the error description to include all literals.

**Comment by Reissner** [comment]
I did not think that integer literals are more expensive. 
I think you may be right. 
Maybe we can have a variant of the rule for each sight, but I can also live with yours.
