### ISSUE TITLE
[doc] Document rule chain

### ISSUE THREAD

**Issue by oowekyala** [pmd/pmd#597]
Part of #1139

Hi, I think some things ought to be better documented on our site:
- [x] the rulechain: the only information I could get is that it's faster for XPath rules. What is it, how does it work, should I use it? I'm genuinely curious about it

* What's the difference between normal rule execution?
* What's the benefit? --> performance

**Comment by jsotuyod** [comment]
@oowekyala actually the rulechain is faster in all cases / can be more flexible; but you need to code rules appropriately.

The main idea is that it can allow several rules to run on a single transversal of the AST (therefore, removing a lot of the overhead / `visit` invocations). It can also be used to enforce a certain visitation order (ie: first all fields, then methods) instead of visiting in the order of appearance.

The downside is that you have to write your rules having this in mind (ie: not calling `super.visit`). We can probably create an internal rule to enforce this point on our own code, probably part of #361 

For XPath rules there is really nothing to document. It's completely transparent to the developer that the rulechain is being used.

I guess this should at best be part of the docs on writing a Java rule, don't you think?

**Comment by oowekyala** [comment]
@jsotuyod Thanks for explaining! 

> We can probably create an internal rule to enforce this point on our own code, probably part of #361

That would be nice, if you think it's worth it

> I guess this should at best be part of the docs on writing a Java rule, don't you think?

Yeah I guess it's a detail about how rules are executed. By the way, how does PMD select the rules that are executed on the rulechain? Are all rules executed like so? Is that an opt-in mechanism? If that's the case, maybe metric rules could be good candidates

**Comment by jsotuyod** [comment]
The feature is opt-in, you use it by having your rule call any overload of [`addRuleChainVisit`](https://github.com/pmd/pmd/blob/master/pmd-core/src/main/java/net/sourceforge/pmd/Rule.java#L315-L329)

**Comment by oowekyala** [comment]
Isn't this already fixed?

https://pmd.github.io/latest/pmd_userdocs_extending_writing_java_rules.html#economic-traversal-the-rulechain

**Comment by oowekyala** [comment]
This is already documented. In pmd 7 we should revise this, but then, the whole documentation will need review
