### ISSUE TITLE
[apex, vf] Discussion - Rules

### ISSUE THREAD

**Issue by JAertgeerts** [pmd/pmd#633]
As the current set of rules is pretty limited, I want to open up a discussion on what other rules should be implemented so we can fork off new issues from this thread. Some rules might need some discussion.

There's a bunch of rules that both CheckMarx (security focused) & Code-Scan (code smell / best practice focused) currently have that aren't implemented in PMD. Do we want to crosscheck those and implement similar best practices?

**Comment by jsotuyod** [comment]
@JAertgeerts definitely! I think feature parity is a great start. We have plenty of rules they don't support, thanks to the amazing work of people such as @up2go-rsoesemann and @sgorbaty among others, but adding those we are missing would be great.

In the meantime, new rules proposals are welcomed, however, the best rules come from people that work daily on such technologies and now them deeply. I fear none of the current PMD maintainers are Salesforce developers, so we rely heavily on the community for this.

**Comment by up2go-rsoesemann** [comment]
@JAertgeerts sure we lack features of costly tools like Checkmarx and Codescan simply because this is (just) open source. Besides me and @sergeygorbaty (who worked for Salesforce.com back then) nobody contributed rules for Apex and VF. Our priorities for rules where

- very useful for most devs
- easy to port from Java rules
- the Apex AST (jorje) support this (Code-Scan uses a super advanced ANTLR parser)
- doable with a static, single file analysis (Checkmarx does dynamic analysis and knows the call graph)

It's great to see you jump into that arena. I'd love us to come closer to those other tools. As @jsotuyod mentioned. The PMD maintainers are not the right people to ask for more rules. This is something we have to bring into local Salesforce user groups or [speak about it at conferences (as I did @ last Dreamforce)](https://www.google.de/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&cad=rja&uact=8&ved=0ahUKEwjZzJPn-bPWAhXLtRQKHTOlCZsQtwIILDAB&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DbW7m6y6bEug&usg=AFQjCNFqj_CJxM7W_M0NgVWXMiC3QO93pQ). 

I will speak about PMD during the next Trailhead DX conference. If you contribute many new rules since then we might do a joint talk. Interested?

**Comment by JAertgeerts** [comment]
Thanks @jsotuyod  @up2go-rsoesemann for the input. Ideally we'd like to get at least closer to some of these commercial initiatives and provide an alternative. Whilst we're currently tied to the Apex AST and its limitations, a lot of rules are still missing to really drive best practice. 

Simplicity is key, so whatever we can do with this parser, we should. So your priorities are still very relevant.
 
Aside from pmd, there was an effort by some folks to develop a SonarQube plugin (https://github.com/fundacionjala/enforce-sonarqube-plugin). There's a good backlog of rules we can piggyback. Other than that, there's nothing.

It's a shame that most non-commercial SFDC initiatives have very little backing from the larger Salesforce community. I hope by adding some of my experience in SFDC and implementing some additional checks, the product gets more traction and more contributions.

 @up2go-rsoesemann I'd be interested, and I agree that for us to get more feedback we'll need to push and get this in the hands of people developing daily. I've already engaged the partners I work with to either provide a set of their best practices we can convert or contribute themselves. 

(Also, am I the only one who's missing an Apex linter???)

**Comment by mnunezdm** [comment]
Hi!
#### For VF:
- Should not contain style tag, CSS should be in a static resource?
- Adding Javascript rules?
#### For APEX:
- Methods too long?
- Lines too long?

**Comment by jsotuyod** [comment]
> * Adding Javascript rules?

For embedded JS snippets, this is in our roadmap in a more general way (ie: applies to JSP too), but requires #237. For standalone JS, you can already use the [PMD JS module](https://pmd.github.io/pmd-5.8.1/pmd-javascript/rules/index.html).

**Comment by rsoesemann** [comment]
@jsotuyod I recommend to close "feature-request" issues that are not followed by a PR (or ongoing communication) after 2 month.
