### ISSUE TITLE
[core] PMD Properties (dev-properties) breaks markup on CodeClimateRenderer

### ISSUE THREAD

**Issue by filipesperandio** [pmd/pmd#643]
**Rule Set:** java-bsic

**Description:** Some rules generate an XPath snippet that looks weird in the **bottom** of the report

**Code Sample demonstrating the issue:**
```java
public class Library {
	public void foo() {
		for (int i = 0; i < 10; i++) {
			for (int k = 0; k < 20; i++) {
				System.out.println("Hello");
			}
		}
	}
}
```

**Running PMD through:** `./run.sh pmd -d . -f codeclimate -R java-basic`
```js
{
  "type": "issue",
  "check_name": "JumbledIncrementer",
  "description": "Avoid modifying an outer loop incrementer in an inner loop for update expression",
  "content": {
    "body": "## JumbledIncrementer\n\nSince: PMD 1.0\n\nPriority: Medium\n\n[Categories](https://github.com/codeclimate/spec/blob/master/SPEC.md#categories): Style\n\n[Remediation Points](https://github.com/codeclimate/spec/blob/master/SPEC.md#remediation-points): 50000\n\nAvoid jumbled loop incrementers - its usually a mistake, and is confusing even if intentional.\n\n### Example:\n\n```java\n\n \npublic class JumbledIncrementerRule1 {\n\tpublic void foo() {\n\t\tfor (int i = 0; i < 10; i++) {\t\t\t// only references 'i'\n\t\t\tfor (int k = 0; k < 20; i++) {\t\t// references both 'i' and 'k'\n\t\t\t\tSystem.out.println('Hello');\n\t\t\t}\n\t\t}\n\t}\n}\n \n \n``` \n\n### [PMD properties](http://pmd.github.io/pmd-5.8.1/customizing/pmd-developer.html)\n\nName | Value | Description\n--- | --- | ---\nviolationSuppressRegex | | Suppress violations with messages matching a regular expression\nviolationSuppressXPath | | Suppress violations on nodes which match a given relative XPath expression.\nversion | 1.0 | XPath specification version\nxpath | \n \n//ForStatement\n [\n ForUpdate/StatementExpressionList/StatementExpression/PostfixExpression/PrimaryExpression/PrimaryPrefix/Name/@Image\n =\n ancestor::ForStatement/ForInit//VariableDeclaratorId/@Image\n ]\n \n | XPath expression\n"
  },
  "categories": [
    "Style"
  ],
  "location": {
    "path": "/Users/filipe/codeclimate/tmp/java/simple_java/src/main/java/Library.java",
    "lines": {
      "begin": 4,
      "end": 6
    }
  },
  "severity": "normal",
  "remediation_points": 50000
}
```

## JumbledIncrementer

Since: PMD 1.0

Priority: Medium

[Categories](https://github.com/codeclimate/spec/blob/master/SPEC.md#categories): Style

[Remediation Points](https://github.com/codeclimate/spec/blob/master/SPEC.md#remediation-points): 50000

Avoid jumbled loop incrementers - its usually a mistake, and is confusing even if intentional.

### Example:

```java

 
public class JumbledIncrementerRule1 {
\tpublic void foo() {
\t\tfor (int i = 0; i < 10; i++) {\t\t\t// only references 'i'
\t\t\tfor (int k = 0; k < 20; i++) {\t\t// references both 'i' and 'k'
\t\t\t\tSystem.out.println('Hello');
\t\t\t}
\t\t}
\t}
}
 
 
``` 

### [PMD properties](http://pmd.github.io/pmd-5.8.1/customizing/pmd-developer.html)

Name | Value | Description
--- | --- | ---
violationSuppressRegex | | Suppress violations with messages matching a regular expression
violationSuppressXPath | | Suppress violations on nodes which match a given relative XPath expression.
version | 1.0 | XPath specification version
xpath | 
 
//ForStatement
 [
 ForUpdate/StatementExpressionList/StatementExpression/PostfixExpression/PrimaryExpression/PrimaryPrefix/Name/@Image
 =
 ancestor::ForStatement/ForInit//VariableDeclaratorId/@Image
 ]
 
 | XPath expression

**Comment by filipesperandio** [comment]
Why is `PMD Properties` included in this format? (while it is not included in different formats)

**Comment by jsotuyod** [comment]
@filipesperandio that's a good question... and I'm not sure either.

The properties were added by @DavidRenz when revamping that renderer, possibly in an attempt to help users fix the violation in one place, either by getting all info to fix it on code, or to fine tune the rule's behavior.... This is also the only renderer to include the xpath expression used or examples, replicating the contents of the PMD website. We could simply add a link to the rule on PMD's site, but that would require an extra click.

There is no reason for all renderers to show the same info. There are huge differences between different formats, since not all are intended for the same use-cases / support all the features we would need (ie: the text report is intended for succinct reporting, unlike the XML / HTML ones, and in the upcoming 6.0.0 release, some formats such as XML / HTML will include stacktraces for analysis errors, but the CSV format will not since it would have issues with newlines)

The bottomline is: is there any reason why we wouldn't want any of these properties in this renderer?

**Comment by filipesperandio** [comment]
@jsotuyod I don't see the problem keeping it, but we should render them properly.

CodeClimate.com is pushing further into using PMD. So it would be nice to properly format this.
https://codeclimate.com/github/filipesperandio/simple_java/pull/1#readup-59c0255954c837000100001d
![screen shot 2017-09-22 at 4 26 12 pm](https://user-images.githubusercontent.com/316873/30760945-cbab359a-9fb2-11e7-8f77-0008f69f6b3b.png)


I am trying to fix this, but I not at all familiar with the code.

**Comment by jsotuyod** [comment]
@filipesperandio on that we agree!

The issue seems to arise from the newlines. The markup renderer on CodeClimate seems to take that literally, and exit the table... If so, this same problem can happen with any property, not only xpaths.

I wonder if escaping the newlines would work (that is, using `\\n` instead of `\n`), or we should strip newlines from all property values. Maybe you have better insight on which one would be best?

Non-withstanding, we should probably exclude from that table `version` and `xpath`, since they are internally generated, and we don't even list them on out own site on the properties list.

**Comment by filipesperandio** [comment]
@jsotuyod Interesting. So far I only faced problems with the markup with the `xpath` property. So taking `xpath` and `vesion` out would solve all the weirdness I saw - maybe not a 100% solution but seems easy enough with a big impact.

Would you suggest me a way to force those properties into the render through Unit Test? The class hierarchy there is kinda overwhelming to figure this out.
