### ISSUE TITLE
[java] JUnitTestsShouldIncludeAssertRule should support `this.exception` as well as just `exception`

### ISSUE THREAD

**Issue by blerner** [pmd/pmd#647]
**RuleSet**: JUnit

**Description**: Related to #285, the following variant on the code there will produce an error about missing assertions:

```java
public class DigitalAssetManagerTest {
  @Rule
  public final ExpectedException exception = ExpectedException.none();
  @Test
  public void throwsIllegalArgumentExceptionIfIconIsNull() {
    this.exception.expect(IllegalArgumentException.class);
    this.exception.expectMessage("Icon is null, not a file, or doesn't exist.");
    new DigitalAssetManager(null, null);
  }
}
```
If either of the `this.exception`s are changed to merely `exception`, then the reported error goes away.  While the code samples in https://github.com/junit-team/junit4/wiki/Rules don't display the use of `this.` as a general matter, it is semantically allowed.

This is run with v5.8.1 of PMD via the command line, so it's current behavior.

**Comment by blerner** [comment]
Bump?  This is still current with 6.2.0, and I'd love to be able to fix this bug in time for my next semester's students...  If I can help test a fix, I'd be happy to.

**Comment by jsotuyod** [comment]
@blerner thanks for your concern and sorry for the lack of response. I fear we had our hands full last year just wrapping up 6.0.0, and this year's start hasn't been easier on us.

The issue remains unscheduled, but any PRs are welcomed and will definitely help getting this in place for 6.3.0 (to be released by late April as scheduled). The definitive fix for this would put some pressure on symbol table / type resolution, but I think there is a simpler fix that could cover all except the most corner-cases and should be easy enough for anyone willing to tackle it.

The problem lies here:

https://github.com/pmd/pmd/blob/5156b1e8565b57a6d1351dad942b267cf51a93fc/pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/JUnitTestsShouldIncludeAssertRule.java#L178-L180

Instead of just checking if the subindex 0 is among expectables, we should check if subindex 0 is `this`, if so, we check index 1 against expectables, otherwise we keep checking index 0.

Similarly, when checking the method call itself on:

https://github.com/pmd/pmd/blob/5156b1e8565b57a6d1351dad942b267cf51a93fc/pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/JUnitTestsShouldIncludeAssertRule.java#L185

we should make sure to check with the `"this."` prefix if it was present.

Of course, a test case would have to be added under [JUnitTestsShouldIncludeAssert.xml](https://github.com/pmd/pmd/blob/master/pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/JUnitTestsShouldIncludeAssert.xml).

**Comment by blerner** [comment]
This *seems* to be fixed in 6.7.0, based on a really quick check just now.  But it would be good to have a real regression test in PMD to confirm this is a deliberate fix...

**Comment by orimarko** [comment]
I added a test and it failed to add assertion without `this.`

**Comment by jsotuyod** [comment]
@blerner according to #1457, it's not fixed. The PR is failing due to this test scenario. I guess this indeed needs fixing.

**Comment by oowekyala** [comment]
Some more info: the AST radically changes structure when a PrimaryExpression starts with `this`.
Without `this`, `exception.expect(...)` is parsed as 
```
PrimaryExpression
  PrimaryPrefix
    Name[@Image = "exception.expect"]
  PrimarySuffix
    Arguments
```
With `this`, `this.exception.expect(...)` is parsed as 
```
PrimaryExpression
  PrimaryPrefix[@ThisModifier = "true", @Image = null ]
  PrimarySuffix[@Image = "exception"]
  PrimarySuffix[@Image = "expect"]
  PrimarySuffix
    Arguments
```

The rule only handles the first parse tree for now, because it searches for a Name node:

https://github.com/pmd/pmd/blob/1d652fc81cfe3d380b5a586f8ea3539fafa42136/pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/JUnitTestsShouldIncludeAssertRule.java#L167

 which in the second parse tree doesn't exist (well it may, but much deeper in the tree, and so that's not what we're looking for).
