### ISSUE TITLE
[Jjva] SwitchStmtsShouldHaveDefault should be aware of enum types

### ISSUE THREAD

**Issue by blerner** [pmd/pmd#651]
**Rule Set:** design

**Description:** 
https://sourceforge.net/p/pmd/feature-requests/491/
and further discussion at 
https://sourceforge.net/p/pmd/discussion/188194/thread/468076db/

Students of mine got bit by this bug recently, and I noticed this old feature request that seems not to have migrated to this git repo.  Having a default case prevents intellij or eclipse from providing warnings about incomplete switch cases, when the enum definition changes. This seems to be a case of two useful tools fighting each other :-) Also, supporting this exemption helps pmd align with the [Google style guide for switch statements](https://google.github.io/styleguide/javaguide.html#s4.8.4-switch) more precisely.

(Not sure if this issue was discussed and abandoned, lost in the sf->git migration, or just ignored, so apologies if this is a duplicate...)

**Comment by jsotuyod** [comment]
@blerner thanks for migrating this. We didn't mass migrate issues, since several of the old ones had already become obsolete. We rely con the community to bring to our attentions those they still care about, just like you did.

This seems like a reasonable change. We will have to iterate this a bit, and will probably not make it for 6.0.0, still good to have it around.

**Comment by blerner** [comment]
Bump?  Is it possible somewhere in the 6.* timeframe, or only in 7.0 and beyond?

**Comment by jsotuyod** [comment]
@blerner I can't foresee any breaking API changes being introduced by this, so there should be no blockers to get it into a 6.X release. It's just a matter of getting it prioritized / a PR, and merged.

Given the current status of type resolution, checking if the variable used for the `switch` has a non-null type, and then just checking if that `Class<?>` corresponds to an enum `Enum.isAssignableFrom()` to whitelist a switch statement should be plausible (it wasn't back in 2012 when the original issue was submitted).

**Comment by oowekyala** [comment]
It would be nice to only whitelist the switch if every enum constant has its label. Similarly, we could have a rule detect unnecessary `default` cases if the switch is exhaustive.

The best implementation I can think of would be to add a method `isExhaustive` to `ASTSwitchStatement`, so that the code can be reused between the two rules, and they can be written in XPath.
