### ISSUE TITLE
[Java (Maybe others)] Missing rulesets from rulesets.properties

### ISSUE THREAD

**Issue by rtfpessoa** [pmd/pmd#652]
After checking the file `rulesets.properties` I found that some rulesets are missing.

* metrics.xml
* typeresolution.xml
* migrating_to_13.xml
* migrating_to_14.xml
* migrating_to_15.xml
* migrating_to_junit4.xml

Any reason for this to happen?
What is the best way for me to find all the rulesets? Search all the *.xml files? I am currently using the file rulesets.properties to find them but apparently might not be the bets way.

**Comment by adangel** [comment]
The `rulesets.properties` file is still the correct way.

* The ruleset metrics.xml contains currently only one new rule (DataClass) which will be new with PMD 6.0.0. The other rules are replacements for already existing rules. We are in the process to replace these rules with the metrics-based implementation. The new rule will be moved to a different ruleset. So, eventually, metrics.xml will disappear.

* The ruleset typeresolution.xml also contains  alternative rule-implementations for already existing rules. We are in the process to finally replace the rules with the typeresolution-based implementation, so this ruleset will also disappear eventually.

* The migrating rulesets you mention only contain rule references. All the original rule definitions are in the ruleset `migrating.xml`.

Note: This is the current status as of today. We plan to reorganize rules into rulesets, which represent concrete rule categories (instead of the vague "basic", "design", ... rulesets). This means, that the rulesets, that are referenced in `rulesets.properties` will change to use the new rulesets. The old rulesets will stay for backwards compatibility (e.g. custom rulesets could still use the "old" rulesets).

**Comment by rtfpessoa** [comment]
Ok, that makes sense. Thank you.
