### ISSUE TITLE
[core] List available rulesets from command line.

### ISSUE THREAD

**Issue by wsdjeg** [pmd/pmd#671]
I am writting a vim plugin for this tools, I need to list available rulesets from command line, does current version of pmd support this feature?

for example list available rulesets for java filetype.

```
pmd --list_rulesets java
```

`--list_rulesets` can be anything base on the rules of pmd's src.

**Comment by jsotuyod** [comment]
@wsdjeg I fear there is no support for such feature, since PMD has really no knowledge of it. PMD has no given set of supported languages. It uses a [`ServiceLoader`](https://docs.oracle.com/javase/8/docs/api/java/util/ServiceLoader.html) to detect which languages are currently available (in the classpath), and when given a ruleset, it merely applies convention mapping to convert references to paths, and attempts to load them...

You could `zipinfo -1 pmd-*.jar | grep "rulesets/.*\.xml"` given you know where pmd's libs are located... but these will list **all rulesets** (including the migration rulesets for different Java versions, deprecated rulesets such as typeresolution on PMD 6.0.0, etc.). Possibly, after #610 these will be much easier to detect / leave out given their file path.

Maybe an alternative would be to read the contents of `rulesets.properties` within those jars (an extra step, and maybe a little harder), which does contain a complete list of the "root" rulesets available, and no reference to the other rulesets, providing a more cannonical answer.

We push for people to create their own rulesets according to their needs and likes. Using complete rulesets with all default settings is generally a bad idea. We want to start providing more "user-ready" configurations as better quick starts with PMD, but those are intended just as that: a quick start.

I'm not sure what the plugin you are writing aims at, nor how it fits with the ruleset reorganization we are pushing for. Could you please provide some more detail?

**Comment by wsdjeg** [comment]
Thanks for your info, I will try to implement this feature in my plugin. :heart:

**Comment by adangel** [comment]
Currently, there is one API call available, that gives you all built-in rules (even those custom rules, that use the undocumented convention to place themselves in the rulesets.properties file):

[RuleSetFactory.getRegisteredRulesets()](https://github.com/pmd/pmd/blob/master/pmd-core/src/main/java/net/sourceforge/pmd/RuleSetFactory.java#L121)
