### ISSUE TITLE
[apex] Leverage Salesforce Apex Language Server?

### ISSUE THREAD

**Issue by up2go-rsoesemann** [pmd/pmd#677]
With their Eclipse IDE Salesforce just beta-released Apex Language Server https://developer.salesforce.com/docs/atlas.en-us.sfdx_ide2.meta/sfdx_ide2/sfdx_ide2_build_app_apex_language_server_protocol.htm to better support tools that need to understand Apex.

This could replace our clunky Jorje parser we currently use. In their Github repos their already is a new Jorje jar https://github.com/forcedotcom/salesforcedx-vscode/tree/develop/packages/salesforcedx-vscode-apex/out

I already contacted Salesforce to learn more. Could you leave this issue open so I can post updates and initiate further discussion?

**Comment by jsotuyod** [comment]
@up2go-rsoesemann feel free to do so on this ticket.

I'm a little hesitant on adopting the Apex Language Service for the time being:

1. it's still in beta, and not necessarily more mature than Jorje
2. it's online, meaning PMD may not work at times depending on external factors
3. it's still unclear to me how we as PMD maintainers could use such a service without a developer license of any kind from Salesforce
4. it will probably require users to setup extra config just to be able to use it (possibly a url and api key pair), meaning the usage of PMD for Apex will be very different from other languages

I'm not discarding it, I think we should follow it and try to get insight on Salesforce's plans / roadmap on both the Language Server and Jorje, to look for the best alternative.

**Comment by up2go-rsoesemann** [comment]
I agree that there might be many drawbacks and I don't think the Service at a whole might be the right thing for us. But as part of the GitHub repo there might be Jorje parser versions which will be updated more frequently and provide better ASTs than we currently have.  Back then when I contributed the Apex module I talked to Salesforce about real support for tooling providers and this is there first step into that future.

I just see this "issue" as an epic story card on our PMD kanban board as a reminder for me to keep an eye on it.

**Comment by jsotuyod** [comment]
@up2go-rsoesemann great! I assigned you the issue so you can keep an eye on it. Looking forward for updates!

**Comment by GiantCrocodile** [comment]
I'm not sure I'm techy enough about PMD to understand what you talk about in detail but if you discuss to use an online service for a component which is a must-have to run PMD locally I highly discourage this. Regarding privacy and copyright reasons and their respective laws it is a bad idea to submit code or information about code to unknown servers in some foreign countries.

This has been an issue in the past already where some developers of a quite commonly used IDE extension had the fabulous idea to submit code to external servers for auto completion without any information or warning.

**Comment by steals** [comment]
@up2go-rsoesemann @jsotuyod  Hello guys, I would like to clarify some notes about Apex Language Server (the correct name is Server and not Service). First of all it's not an online service, but you will need to run it locally. Actually it's an implementation of Language Server Protocol for Apex (see. https://github.com/forcedotcom/salesforcedx-vscode/wiki/Apex-Language-Server)
I believe Salesforce will not update old Jorje parser any more as they switched to a new one. In the near future (next summer) Salesforce is planning to introduce "switch" statement to Apex and I'm not sure if old parser will be able to parse files with new constructions, so I think it's needed to move to a new parser.

Also starting from this October all tools related to Salesforce DX (including this new parser) might be considered as stable (https://developer.salesforce.com/blogs/2017/10/salesforce-dx-is-now-generally-available.html).

P.s. I'm not Salesforce employee

**Comment by up2go-rsoesemann** [comment]
Thanks @steals for clarification. I will contact people at Salesforce to learn about their plans.

**Comment by up2go-rsoesemann** [comment]
Just a guick update. I asked Salesforce on Twitter and already got replies https://twitter.com/RobertSoesemann/status/935883326803664896

1. Language Server is a standalone offline thing
2 There is also an upgraded Jorje here https://github.com/forcedotcom/salesforcedx-vscode/tree/develop/packages/salesforcedx-vscode-apex/out

@jsotuyod maybe we can just replace the old version we have?

**Comment by vazexqi** [comment]
What @steals has said is correct.

1. The Apex LSP runs locally. It might need to make some calls online to get more information (for instance about sobjects, managed packages, etc) but everything else runs locally.
1. It uses Jorje underneath. The version of Jorje that is packaged with Force.com IDE will not be updated. But, the one for VS Code is constantly updated at https://github.com/forcedotcom/salesforcedx-vscode/tree/develop/packages/salesforcedx-vscode-apex/out. This is because, moving forward, our flagship IDE is shifting from Eclipse to VS Code.
1. The jar at https://github.com/forcedotcom/salesforcedx-vscode/tree/develop/packages/salesforcedx-vscode-apex/out is a über jar with all the dependencies packaged. If you want to use it like you did with the old jorje jar, you can.

Yes, I can see for PMD, it would be hard to just use the Apex LSP as-is since you already have your own protocol and expectations. So, you can continue to use what you had done before. As before, it won't be an officially supported approach, but we would not deliberately break you.

That being said, moving forward, all our tooling efforts will be focused on conforming to the Language Server protocol moving forward (http://langserver.org/).

If you want more information about the language server (specific to Salesforce), you can take a look at my presentation at https://www.salesforce.com/video/1765282/

**Comment by up2go-rsoesemann** [comment]
Thanks @vazexqi for this final clarification. We know know that the LSP is not the right thing for PMD but there is an inofficially updated Jorje we can use. 

@jsotuyod I close this one and opened a new issue to replace the old with the new Uber jar at https://github.com/pmd/pmd/issues/766

**Comment by jsotuyod** [comment]
@vazexqi @up2go-rsoesemann thanks for the input! We will keep looking at that jorje location for future updates.
