### ISSUE TITLE
[apex] ApexUnitTestClassShouldHaveAsserts - ApexMocks

### ISSUE THREAD

**Issue by cropredyHelix** [pmd/pmd#701]
**Rule Set:**
ApexUnitTestClassShouldHaveAsserts

**Description:**
If one writes unit tests using fflib ApexMocks, one may not have any asserts as "assertion" is done through the `verify` method.

**Code Sample demonstrating the issue:**

Example is an excerpt from `fflib_ApexMocksTest.cls` but applies to any testmethod that uses ApexMocks

Would require rule to be aware of variable of type `fflib_ApexMocks` and used with `.verify()` method. Not sure this is possible.

```
@isTest
static void whenVerifyCustomMatchersCanBeUsed()
{
	// Given
	fflib_ApexMocks mocks = new fflib_ApexMocks();
	fflib_MyList mockList = (fflib_MyList)mocks.mock(fflib_MyList.class);

	// When
	mockList.get(1);
	mockList.get(2);
	mockList.get(3);
	mockList.get(4);
	mockList.get(5);

	// Then
	((fflib_MyList.IList) mocks.verify(mockList, 3)).get((Integer)fflib_Match.matches(new isOdd()));
	((fflib_MyList.IList) mocks.verify(mockList, 2)).get((Integer)fflib_Match.matches(new isEven()));
}
```

**Running PMD through:** *[Other - Gearset]*

**Comment by jsotuyod** [comment]
@cropredyHelix thanks! We have already addressed a similar issue with Java, we certainly should.

**Comment by alan-morey** [comment]
Would this enhancement be limited to awareness of `ApexMocks.verify` only or would it be possible to configure the rule to recognize custom assert methods?

**Comment by jsotuyod** [comment]
@alan-morey what kind of custom assertions are you thinking of?

**Comment by alan-morey** [comment]
@jsotuyod I'm currently using a custom class  `Assert` that contains a set of static assertion methods useful for writing tests. The `Assert` class is really just a wrapper over the `System.assert` methods.

When I run pmd against my unit test source, I get reports that "Apex unit tests should System.assert() or assertEquals() or assertNotEquals()" for all my tests.

`ApexUnitTestClassShouldHaveAssertsRule` has hard coded what methods it considers to be assert methods:
https://github.com/pmd/pmd/blob/e7e5e13a7d4358ddb8e5cc95f9aa93622615e824/pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/bestpractices/ApexUnitTestClassShouldHaveAssertsRule.java#L24-L32

I would like to be able to add additional assert methods, through some rule configuration, so I don't get false positives when my tests use assert methods that are not the `System.assert*` methods.

**Comment by jsotuyod** [comment]
@alan-morey interesting.... yes, we can probably change that into a multivalue property and have those + verify as defaults; but let you customize it to add your own.

**Comment by rsoesemann** [comment]
Not sure if you guys want to keep a never ending list of "wishes". But I'd recommend to close such issues. This is a way to specific requirement. 

I recommend that @cropredyHelix basically supresses the rule for his test classes.

**Comment by jsotuyod** [comment]
@rsoesemann why wouldn't you support this? I mean, we do support `Mockito.verify` on Java...

https://github.com/pmd/pmd/blob/c49ae6b769e01064c336325c29416e7b5ab147c9/pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/JUnitTestsShouldIncludeAssertRule.java#L142-L159

Is there anything intrinsically wrong with this I'm failing to see?

**Comment by rsoesemann** [comment]
@jsotuyod I think we should NOT support it because it's a special case which will make the

1. The rule more complicated
2. The rule more likely to change when the different mock libs change their signature.
3. Make other developers to ask for covering more special cases.

I'm not an open source expert and if that is how to do it I am ok with leaving all this issues pending until some contributor picks them up. But since we added Apex there was not many contributors and I don't want to make those people happy. I simply can't.

**Comment by adangel** [comment]
Disclaimer: I have also no solution to the following dilemmas...

> The rule more complicated

Sure, every feature needs to be maintained. And somebody needs to implement it first. 
One advantage of implementing this is: PMD would simply work out of the box if someone uses ApexMocks. So it is a trade-off.

> leaving all this issues pending until some contributor picks them up

That's another point: If the OP doesn't come back and asking, when this will be fixed/implemented, then it for sure can't be something important. So we can close it, there is no real demand. However, if someone wants to contribute, it would be good, if there are some issues to be able to work on. So, an open source project should indeed maintain a pool of tasks. We could definitely do a better job in defining/specifying the tasks, so that it is easier for someone to pick them up.

**Comment by cropredyHelix** [comment]
OP here ... My workaround for this has been to suppress warnings for this violation in all of my apexmocks-based testmethods. Tedious but hardly the end of the world.
