### ISSUE TITLE
[doc] Front page links on the site are not rendering properly

### ISSUE THREAD

**Issue by oowekyala** [pmd/pmd#751]
![image](https://user-images.githubusercontent.com/24524930/33152791-cf5fe8dc-cfde-11e7-9a91-caac0d0d5a5c.png)

I noticed that adding a non-space character (eg `&nbsp;`) at the beginning of [this line](https://github.com/pmd/pmd/blob/cbef7a5602307c9671749da61a60792e89358e6f/docs/_includes/links.html#L10) makes the content appear.  Are these supposed to be hyperlinks for all the pages on the site? Is it an alternative to the sidebar?

**Comment by jsotuyod** [comment]
@oowekyala that's weird... I see it just fine https://pmd.github.io/pmd/

![screen shot 2017-11-22 at 7 27 33 pm](https://user-images.githubusercontent.com/802626/33152420-448da618-cfbb-11e7-8645-68bdc4dcbedc.png)

**Comment by oowekyala** [comment]
@jsotuyod It's at the very bottom of the page

**Comment by jsotuyod** [comment]
@oowekyala oh! now I see it! thanks!

**Comment by adangel** [comment]
This is actually the feature [Automated links](http://idratherbewriting.com/documentation-theme-jekyll/mydoc_hyperlinks.html#automatedlinks)

This include generates a list of link references in markdown syntax. If you add a "&nbsp;" before, then it's not a link ref anymore and the markdown renderer just renders it as text.

If the all the link references are syntactically correct, then they will not at all appear in the resulting html - only the links in the paragraphs of the page will be correct hyperlinks.

The problem here is, that we have in our sidebar some folderitems without an url (these elements have subfolderitems). This resulted in invalid references, such as `[]: ` - empty ref name and empty url - and broke all references.
