### ISSUE TITLE
[apex] StdCyclomaticComplexity, CyclomaticComplexity  not showing the place to hit

### ISSUE THREAD

**Issue by parksungrin** [pmd/pmd#765]
Please, prefix the report title with the language it applies to within brackets, such as *[java]* or *[apex]*. If not specific to a language, you can use *[core]*

**Rule Set:**
StdCyclomaticComplexity

**Description:**
The class <Class Name> has a Standard Cyclomatic Complexity of 4 (Highest = 12).
it will be great if which part has highest complexity.

**Code Sample demonstrating the issue:**

**Running PMD through:** *[CLI | Ant | Maven | Gradle | Designer | Other]*

**Comment by oowekyala** [comment]
Thanks for the suggestion! The rule StdCyclomaticComplexity is deprecated though, and it's replacement, CyclomaticComplexity, uses a different calculation to report classes. Instead of doing the average of the complexity of methods, it reports classes which have a very high total complexity. This avoids redundancy in the report, and allows to flag classes with numerous medium complexity methods. 

For both rules, if the highest complexity method is above the method reporting threshold, it's reported on its own anyway. StdCyclomaticComplexity is just dumber about it because when it reports classes, there are necessarily reported methods, including the maximum. 

I'm reluctant to change StdCyclomaticComplexity as it's deprecated. We could change CyclomaticComplexity though, and add the highest complexity method name *if* that method crosses the threshold. If it doesn't, there's no reason to point at it as all methods would have low complexity anyway. What do you think about that? 

This change could make it in version  6.1.0, but I think not before.  Btw I advise you to use CyclomaticComplexity as soon as you switch to 6.0.0, when it's out.

**Comment by jsotuyod** [comment]
@oowekyala `StdCyclomaticComplexity` was deprecated on 5.8.0, as we introduced `CyclomaticComplexity` on that release. He should already be able to make the switch, shouldn't he?

https://github.com/pmd/pmd/blob/master/docs/pages/release_notes_old.md#deprecated-rules

**Comment by oowekyala** [comment]
@jsotuyod IIRC the CyclomaticComplexity rule was in the metrics ruleset in 5.8.0. I didn't want to point to that ruleset since it's been removed in the upcoming release, but yes you're right, he could already make the switch ^^

**Comment by parksungrin** [comment]
Thank you for quick response. for CyclomaticComplexity , it looks like that methodReportLevel  doesn't work but classReportLevel works.

**Comment by oowekyala** [comment]
> It looks like that methodReportLevel doesn't work but classReportLevel works.

@parksungrin Could you expand on that? What ruleset is your CyclomaticComplexity from, and with which version of PMD? The rule has moved around quite a bit

**Comment by parksungrin** [comment]
Version which I uses :   pmd-apex-6.0.0-SNAPSHOT
I updated title to indicate apex

**Comment by oowekyala** [comment]
@parksungrin Could you provide a sample code showing the failure ?

**Comment by parksungrin** [comment]
@oowekyala  I have retest it and when CyclomaticComplexity  is only activated. it works fine.
Sorry for my confusion.
