### ISSUE TITLE
[java] Ignore CommentDefaultAccessModifier & DefaultPackage when Accessor*Rule's are turned on

### ISSUE THREAD

**Issue by vanniktech** [pmd/pmd#809]
What do you think of ignoring `CommentDefaultAccessModifier` & `DefaultPackage` when the Accessor*Rules are turned on?

In Android, we like to have things package-private in order to remove the creation of synthetic accessor methods and those two rules are just noise when the other one is activated.

**Comment by jsotuyod** [comment]
@vanniktech I don't think it's up to PMD to ignore / modify what the user defined in the ruleset.

A user may want to favor public or protected rather than package-private to remove accessor generators, and doing so by using `DefaultPackage` too should be ok.

As for `CommentDefaultAccessModifier`, it's asking for developers to be explicit on their decision to be package-private, regardless of the reason. I'm a long time Android developer and the rule was contributed by my own company as we wanted to enforce it (and I'm also the author of one of the accessor generator rules).

**Comment by jsotuyod** [comment]
As for `BeanMembersShouldSerialize`, the fact that you are using a `CompositeDisposable` is irrelevant. The rule is pretty dumb, it can't tell which classes are beans or not. It will simply require getters / setters on all fields that are not transient or static (setters not required for final fields).

I recommend you either remove the rule, or make use of either `violationSuppressXPath` or `violationSuppressRegex` to ignore classes that are not actually beans, such as your activity.

**Comment by vanniktech** [comment]
Alright sounds good.
