### ISSUE TITLE
[doc] New rule doc is missing shared suppression properties

### ISSUE THREAD

**Issue by jsotuyod** [pmd/pmd#813]
The new documentation on the rules is not documenting the usage of `violationSuppressXPath` and `violationSuppressRegex`. This is intentional as per:

https://github.com/pmd/pmd/blob/cd58d15bc2722a146ef3fa258d1523e46b91e9ca/pmd-doc/src/main/java/net/sourceforge/pmd/docs/RuleDocGenerator.java#L405-L408

However, there is no other place where such properties are properly documented for easy reference. I'd reconsider having this doc included on all rules.

**Comment by oowekyala** [comment]
Wouldn't the page about suppressing violations be the most sensible place to look for? They're already documented there btw

I fear displaying an entry for these properties for each and every rule would only introduce noise, since the description of these properties isn't overwhelmingly helpful either. Imho, this isn't a satisfying option

**Comment by jsotuyod** [comment]
@oowekyala that's a nice idea. We definitely need to get it back somewhere.

**Comment by oowekyala** [comment]
@jsotuyod [There's already that](https://pmd.github.io/pmd-6.0.0/pmd_userdocs_suppressing.html#violation-suppress-regex) and the following section, do you think it should be improved ?

**Comment by jsotuyod** [comment]
@oowekyala interestingly I didn't find it back when I looked for it... I'm closing this for the time being, but I'll keep thinking if we are not hiding it too much for users...
