### ISSUE TITLE
[java] JavaTypeDefinitionSimple.toString can cause NPEs

### ISSUE THREAD

**Issue by sniperrifle2004** [pmd/pmd#899]
**Affects PMD Version:**

6.0.1

**Rule:**

Not applicable

**Description:**

The current toString implementation of JavaTypeDefinitionSimple can cause NullPointerExceptions if one of the genericArgs is null (The call to shallowString will fail). I do not know why a null can be present in the genericArgs (Which if it is unexpected, would of course be the root cause), but preventing the NullPointerException is fairly trivial.

**Running PMD through:** *Maven*

**Comment by jsotuyod** [comment]
@sniperrifle2004 thanks for the report.

I agree that avoiding the NPE should be trivial, but I would still want to dig into why a generic arg can be null rather than simply sweep it under the carpet. Any chance you can provide us with a failing sample? Figuring out on which file's analysis it's failing should be fairly simple but let me know if you need assistance.

**Comment by sniperrifle2004** [comment]
I managed to in it down to a use of Collections.singleton on null, in a very specific generic context:

```java
import java.util.Collection;
import java.util.Collections;
import java.util.HashMap;
import java.util.Map;

public class SpecialMap<A extends SpecialMap.SelfReferringType<A>> {

	Map<TypeLink<?, ? super A>, Collection<?>> contents = new HashMap<>();

	public static class TypeLink<U, T> {}

	public static class SelfReferringType<T extends SelfReferringType<T>> {}

	public final void putNull(TypeLink<?, ? super A> field) {
		contents.put(field, Collections.singleton(null));
	}

}
```

I tried to further pin it down, but the other modifications would cause it to no longer fail.

**Comment by jsotuyod** [comment]
@sniperrifle2004 great! thanks a lot!
