### ISSUE TITLE
[core] PMD build failure on Windows

### ISSUE THREAD

**Issue by tkleiber** [pmd/pmd#928]
Please, prefix the report title with the language it applies to within brackets, such as [java] or [apex].
If not specific to a language, you can use [core].

**Affects PMD Version:** 
6.0.1

**Rule:**
-

**Description:**
Try a fresh build on the unzipped sources zip, as workaround for https://github.com/pmd/pmd/issues/461

**Code Sample demonstrating the issue:**

```
%MVN_HOME%\bin\mvn clean package -Dmaven.test.skip=true
```
```
[WARNING]
java.lang.IllegalArgumentException: character to be escaped is missing
        at java.util.regex.Matcher.appendReplacement(Matcher.java:809)
        at java.util.regex.Matcher.replaceAll(Matcher.java:955)
        at java.lang.String.replaceAll(String.java:2223)
        at net.sourceforge.pmd.docs.RuleDocGenerator.getRuleClassSourceFilepath(RuleDocGenerator.java:543)
        at net.sourceforge.pmd.docs.RuleDocGenerator.generateRuleSetIndex(RuleDocGenerator.java:389)
        at net.sourceforge.pmd.docs.RuleDocGenerator.generate(RuleDocGenerator.java:86)
        at net.sourceforge.pmd.docs.GenerateRuleDocsCmd.main(GenerateRuleDocsCmd.java:38)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:282)
        at java.lang.Thread.run(Thread.java:745)
```
```
[INFO] PMD Documentation Generator ........................ FAILURE [01:17 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 12:44 min
[INFO] Finished at: 2018-02-20T09:46:14+01:00
[INFO] Final Memory: 92M/730M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:java (d
efault) on project pmd-doc: An exception occured while executing the Java class.
 character to be escaped is missing -> [Help 1]
```

**Running PMD through:** *[CLI | Ant | Maven | Gradle | Designer | Other]*
Maven Build

**Comment by tkleiber** [comment]
This requires java 9, I have to build and use it with java 8, is this possible?
```
[INFO] --- maven-antrun-plugin:1.8:run (pmd-clean) @ pmd ---
[INFO] Executing tasks

main:
     [echo] PMD specific tasks: cleaning generated xdocs
[INFO] Executed tasks
[INFO]
[INFO] --- maven-enforcer-plugin:3.0.0-M1:enforce (enforce-versions) @ pmd ---
[WARNING] Rule 0: org.apache.maven.plugins.enforcer.RequireJavaVersion failed wi
th message:
Detected JDK Version: 1.8.0-101 is not in the allowed range [9,).
```

**Comment by adangel** [comment]
PMD requires Java9 for building, but for running, currently java7 is the minimum.

I don't think, that you can simply remove the enforcer (e.g. via `mvn clean package -Denforcer.skip=true`), since we use the new release-flag of java9, which allows us to avoid using toolchains/bootclasspath configurations. I would assume, that the compiler plugin complains then...

**Comment by adangel** [comment]
Yes, the compiler plugin will fail:

    [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:compile (default-compile) on project pmd-core: Fatal error compiling: invalid flag: --release

So, the easiest way to compile PMD is to just download and install java9 from http://www.oracle.com/technetwork/java/javase/downloads/index.html

**Comment by adangel** [comment]
I've now come around trying to build PMD under Windows again. Two issues are existing currently:

1. Test failures. Can be fixed via #937. Workaround: `-DskipTests`
2. Checkstyle failures. This happens, if you download the source zip file. Then all the files have LF (unix style) line endings, while checkstyle expects CRLF (Windows style) line endings. This is related to https://github.com/pmd/build-tools/pull/3 . It only happens, if the source-zip file is used. If the repository is cloned via git, then the "autocrlf"-feature fixes the line endings and makes sure, the files locally have CRLF endings, while in the repository only LF is stored. Workaround: do not execute the verify phase.

So, in order to build PMD under Windows, currently:

1. Use Java9
2. Run `mvn clean package -DskipTests`

**Comment by tkleiber** [comment]
Building 6.1.0 works too with the mentioned restrictions above.

**Comment by adangel** [comment]
Thanks for the feedback. I'll tackle now the checkstyle problem...
