### ISSUE TITLE
[visualforce] VfUnescapeEl thrown for non-strings 

### ISSUE THREAD

**Issue by MisterSquishy** [pmd/pmd#942]
**Affects PMD Version:** 
6.0.1
**Rule:**
VfUnescapeEl 
**Description:**
This error will be thrown for non-string attributes, which are not vulnerable and cannot be jsencoded. If we want to placate this warning, we have to cast to string on the server side so we can jsencode on the client, which is less secure than just using an integer/boolean/whatever
**Code Sample demonstrating the issue:**

```
components/test.component
<apex:component controller="testCon">
    <script type="text/javascript">
        console.log({!var});
    </script>
</apex:component>
```
```
classes/testCon.cls
public with sharing class testCon {
    public static integer var{get;set;}
}
```
PMD output
components\test.component:3:        Avoid unescaped user controlled content in EL

**Running PMD through:** *[Ant]*

**Comment by jsotuyod** [comment]
@MisterSquishy thanks for the report.

PMD doesn't currently perform multi-file analysis (and specially not multi-language, as this would require mixing Apex knowledge with VF).

However, I'm not sure I see the problem you describe. We can make this warning go just changing the VF code, no need to alter the data types in Apex. I can actually think of 2 ways around this.

1. You can do:

```
<apex:component controller="testCon">
    <script type="text/javascript">
        console.log(JSON.parse({!var}));
    </script>
</apex:component>
```
Which will be safe and honor the integer type.

2. You could also do:

```
<apex:component controller="testCon">
    <script type="text/javascript">
        console.log("{!var}");
    </script>
</apex:component>
```

But in the JS it will be a string rather than an integer (which in this particular case makes no difference, but may in other circumstances).

**Comment by MisterSquishy** [comment]
Makes sense--thanks for the tips!
