### ISSUE TITLE
[java] Detect identical catch statements

### ISSUE THREAD

**Issue by jsotuyod** [pmd/pmd#955]
Under Java 7 and later, it's possible to use multi-catch. We should have a rule detect such cases to help people migrate / reduce boilerplate.

Example:

```java
try {
  // do something
} catch (ClassNotFoundException e) {
  if (LOG.isLoggable(Level.FINE)) {
    LOG.log(Level.FINE, "Could not find class " + className + ", due to: " + e);
  }
} catch (NoClassDefFoundError e) {
  if (LOG.isLoggable(Level.FINE)) {
    LOG.log(Level.FINE, "Could not find class " + className + ", due to: " + e);
  }
}
```

can be reduced to:

```java
try {
  // do something
} catch (ClassNotFoundException | NoClassDefFoundError e) {
  if (LOG.isLoggable(Level.FINE)) {
    LOG.log(Level.FINE, "Could not find class " + className + ", due to: " + e);
  }
}
```

**Comment by oowekyala** [comment]
We currently don't have a concept of equality between nodes, so we can't compare subtrees to implement that rule. We could either compare the lexer tokens, or the AST. My guess, is that comparing tokens would be simpler to implement, and probably as correct, since identical catch blocks are often an exact copy-paste.
