### ISSUE TITLE
Can not run Designer

### ISSUE THREAD

**Issue by lonelyma1021** [pmd/pmd#962]
Affects PMD Version:6.1.0
Description:When I type "./run.sh designer" I got an error, but "./run.sh designerold" works. It seems that the class net.sourceforge.pmd.util.fxdesigner.Designer is missing.
Running PMD through: CLI on Ubuntu 17.10 with openJDK 1.8

**Comment by jsotuyod** [comment]
@lonelyma1021 I can't reproduce your issue.

1. How did you installed PMD? is it a binary distribution from SourceForge? Built from source?
2. Please check that the lib folder contains pmd-ui-6.1.0.jar

**Comment by lonelyma1021** [comment]
I just download the binary distribution from github, then unzip it. Cd to the bin derictory and type ./run.sh designer in terminal. I have try both  binary distribution from github and sourceforge, and get the same error. By the way, I have checked the lib folder, pmd-ui-6.1.0.jar is just there in the folder.Is it caused by Open JDK 1.8?

**Comment by adangel** [comment]
@lonelyma1021 Yes, indeed. The problem seems to be related to openjdk: with openjdk, javafx is not included. For my debian, there is the package `openjfx`, after I installed this package, the designer works.

You have the following options:
* Download the Oracle Java version from http://www.oracle.com/technetwork/java/javase/downloads/index.html . This includes JavaFX by default
* Install the package openjfx, e.g. try `sudo apt-get install openjfx`

For reference, the complete error message is:
`Error: Could not find or load main class net.sourceforge.pmd.util.fxdesigner.Designer`
I assume, the problem is actually loading the class, since the referenced JavaFX classes are not available.
